### PR TITLE
Add constraints to generate DB diagram

### PR DESCRIPTION
**Pull request by kinow**
These changes partially address #2483

**Requirements check-list**
- [X] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [X] Contains logically grouped changes (else tidy your branch by rebase).
- [X] Does not contain off-topic changes (use other PRs for other changes).
- [X] These changes are already covered by existing tests.
- [X] No change log entry required (e.g. change is small or internal only).
- [ ] I have opened a corresponding documentation PR at cylc/cylc-doc#XXXX.
- [ ] No documentation update required for this change.

The approach used is hijacking on the current approach for columns, because the constraints are not related to a column. The most common foreign key in our DB is `FOREIGN KEY(name, cycle)`, which does not relate to a single column, but to a couple of columns.

And still need to check if it would be possible to include comments to the tables as well. But here's what the diagram generated with this code looks like.

cylc-database

This is automatically generated, and we don't have much control on the layout. But we can still look at other tools, as the tables can probably be better organized.

### CODE REVIEW

**Comment by kinow** [comment]
Note to self: Some tables have a 1.1 relation, instead of 1.N. e.g.: `task_pool` & `task_late_flags`, `task_pool`, & `task_timeout_timers` (there can be more)

**Comment by kinow** [comment]
Interesting, we have functional tests to verify the database creation commands :grimacing: will fix those later. But once I fix the 1-to-1 relationship, it would be great somebody could have a look and see if that makes sense.

A few more notes about it:

- There is a risk - well pointed yesterday by @oliver-sanders - of issues with DB updates. Though I think adding a constraint won't break anything. But we still need to take that into consideration when review/testing it.
- If it breaks anything, or if it is not a good change to Cycl 8, we can simply get this generated diagram and close this issue. As this issue is not for adding constraints, but for documenting the DB schema (I reckon our DB scheme changes very rarely, and it's not hard to re-generate the diagram with some `git` diff-fu)

**Comment by oliver-sanders** [comment]
Are we good to go with this PR?

**Comment by matthewrmshin** [comment]
This is good in principle. The restart tests will need fixing.

**Comment by oliver-sanders** [comment]
I'm happy with the approach, Bruno, if you could stick up the script you are using to generate the graph onto the https://github.com/cylc/cylc-doc/issues/28 issue, we'll auto-generate the image when we attempt https://github.com/cylc/cylc-doc/issues/28.

**Comment by kinow** [comment]
Oh on my last day in Exeter I was testing another way to generate the documentation.

This other approach doesn't require touching cylc's db, though we have to write the dependencies in the script - which I think should be ok.

Will restart work on this next week. 

Bruno

**Comment by kinow** [comment]
Here's another approach, which hardcodes the relationships, but doesn't require any changes to the current SQLite schema, which reduces the risks of bugs/regressions in Cylc 8 for existing users :grimacing: 

If others are OK with that approach, this issue can then be closed.

**Comment by kinow** [comment]
Closing this one for the ticket in cylc-doc :+1:

**Comment by sadielbartholomew** [comment]
(cylc/cylc-doc#29 since I can't see it linked anywhere here)

**Pull request closed without merging**
