### PR TITLE
fix a typo in document

### PR DESCRIPTION
**Pull request by gmao-cda**
A simple one word fix for a typo...

**Check List**

- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor (**Not sure I should put my name in it**)
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [ ] Tests are included (or explain why tests are not needed) (**fix a typo in document. No change in code behavior**).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]

**Comment by hjoliver** [comment]
Thanks @gmao-cda !

**Comment by MetRonnie** [comment]
Hi @gmao-cda, sorry for not flagging it up at the time but please could you add yourself to `CONTRIBUTING.md` after all?

**Comment by MetRonnie** [comment]
I've opened it at #5502

**Comment by hjoliver** [comment]
(Sorry, I should have checked for that!)

**Pull request merged**
