### PR TITLE
add platform on reload for SUCCEEDED and FAILED tasks

### LINKED ISSUE #5063: job polling broken for failed jobs after restart
Cylc 8 Version of https://github.com/cylc/cylc-flow/issues/4516

> **tldr;**
>
> Failed tasks can be polled back to incorrect states on restart.
> ...

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by wxtim**
These changes close #5063 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.
- [ ] Merged bugfix onto master

### CODE REVIEW

**Comment by oliver-sanders** [comment]
(happy omitting tests for this one, we need to review polling logic at some point and develop a complete set of unit tests)

**Review by MetRonnie — APPROVED** [review]
LGTM

**Comment by oliver-sanders** [comment]
Changed base to 8.0.x to match the milestone.

**Comment by oliver-sanders** [comment]
Tried this with Dave's example from https://github.com/cylc/cylc-flow/issues/4513, I think I've managed to reproduce it on this branch. Will investigate and try again, could someone else have a crack.

**Comment by wxtim** [comment]
> Tried this with Dave's example from #4513, I think I've managed to reproduce it on this branch. Will investigate and try again, could someone else have a crack.

Actually closes #5063/

**Comment by MetRonnie** [comment]
I think #5063 is a duplicate of #4513, which is the 8.0.1 version of #4516

**Comment by MetRonnie** [comment]
I tried reproducing #4516 on 8.0.x, but don't think I could reproduce using `_remote_background_indep_tcp` platform

```
[scheduling]
    [[graph]]
        R1 = a:fail? => restart

[runtime]
    [[a]]
        script = sleep 60
        execution time limit = PT1S
        platform = _remote_background_indep_tcp
    [[restart]]
        script = """
            cylc stop "${CYLC_WORKFLOW_ID}" --now --now
            sleep 5
            cylc play "${CYLC_WORKFLOW_ID}" --host=localhost
        """
```

**Comment by wxtim** [comment]
> I tried reproducing #4516 on 8.0.x, but don't think I could reproduce using `_remote_background_indep_tcp` platform
> 
> ```
> [scheduling]
>     [[graph]]
>         R1 = a:fail? => restart
> 
> [runtime]
>     [[a]]
>         script = sleep 60
>         execution time limit = PT1S
>         platform = _remote_background_indep_tcp
>     [[restart]]
>         script = """
>             cylc stop "${CYLC_WORKFLOW_ID}" --now --now
>             sleep 5
>             cylc play "${CYLC_WORKFLOW_ID}" --host=localhost
>         """
> ```

TBH I did the testing manually - I couldn't get this auto restarter working well and used @dpmatthews 's example.

**Comment by wxtim** [comment]
Example I used

```
#!jinja2
[scheduling]
    [[graph]]
        R1 = "timeout-remote & timeout-local-slurm & timeout-local-bg"
[runtime]
    [[timeout-remote]]
        script = "sleep 600"
        platform = xce
        execution time limit = PT1S
    [[timeout-local-slurm]]
        script = "sleep 600"
        platform = spice
        execution time limit = PT1S
    [[timeout-local-bg]]
        script = "sleep 600"
        execution time limit = PT1S
```

Wait for all three to fail, then stop and restart the workflow.

**Comment by oliver-sanders** [comment]
> add platform on reload for SUCCEEDED and FAILED tasks

This issue is about "restart" rather than "reload" right?

**Review by oliver-sanders — APPROVED** [review]
Managed to reproduce with the `timeout-remote` platform in [Tim's example](https://github.com/cylc/cylc-flow/pull/5025#issuecomment-1216396777) on master, couldn't reproduce on this branch.

LGTM.

**Comment by oliver-sanders** [comment]
@wxtim  could you add a changelog.

**Comment by wxtim** [comment]
I've rebased this on the wrong branch. I'm taking that as an indication of tiredness. Will fix tomorrow. 😞

**Comment by wxtim** [comment]
@oliver-sanders  @MetRonnie  Please check that I haven't messed owt up with my foolish rebasing.

**Comment by oliver-sanders** [comment]
(letting tests pass)

**Pull request merged**
