### PR TITLE
scan: improve colour output

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Make the submitted colour more distinct from the running colour (can improve this when working on Tui)
* Use a hard-coded grey colour rather than "dim" as "dim" is not always grey.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Comment by wxtim** [comment]
#### Solarized Dark (my personal use)
image
 - I like it.
#### Solarized Light
image
#### Terminator "Orange on black"
image
#### Ambience
image
#### Terminator "Green on Black" (BBC Micro nostalgia here)
image

IMO it's easier to read in many themes, and no worse in _any_.

**Review by wxtim — APPROVED** [review]
Makes sense.

**Comment by datamel** [comment]
So, this is probably me being a little controversial. I think this is down to my aging eyesight but to me the colours of submitted and succeeded, to me are very difficult to distinguish. I know that the comparison is not foreground/background but for accessibility, I wonder if it would be possible to pick a colour for either submitted or succeeded that would make it a bit clearer?  
Looking at the colours on a contrast checker, there is basically no contrast ratio between these two colours: 
image
image

**Review by datamel — COMMENTED** [review]
I have run the change. I've made a comment about contrast between submitted and succeeded. Happy to approve this change if others feel I'm being a bit picky. Sorry if I am.

**Comment by oliver-sanders** [comment]
> I have run the change. I've made a comment about contrast between submitted and succeeded. Happy to approve this change if others feel I'm being a bit picky. Sorry if I am.

No fair enough.

Was going to sort out the colours and add in the other colour themes with future Tui work, but we might as well sort out `cylc scan` now, won't take long...

**Comment by oliver-sanders** [comment]
Ok, so I've been through the [256 colour palette](https://worldwidemann.com/content/images/2015/03/finalterm-colors.png) with a colour meter and `cylc scan` now has the most faithful replication of the design document possible without going to "true" colours.

Screenshot 2020-09-22 at 14 22 46

The contrast is now reasonable for most people, we will add other colour series to improve accessibility later on.

**Comment by datamel** [comment]
> Ok, so I've been through the [256 colour palette](https://worldwidemann.com/content/images/2015/03/finalterm-colors.png) with a colour meter and `cylc scan` now has the most faithful replication of the design document possible without going to "true" colours.
> 
> Screenshot 2020-09-22 at 14 22 46
> 
> The contrast is now reasonable for most people, we will add other colour series to improve accessibility later on.

Looks great, thanks. Sorry for being tricky!

**Review by datamel — APPROVED** [review]

**Comment by oliver-sanders** [comment]
> Looks great, thanks. Sorry for being tricky!

Not at all, you were very right.

**Comment by oliver-sanders** [comment]
Tested with greyscale backgrounds in my terminal, was worried that the submitted colour might be too pale but the switch to low colour mode saves it:

Kapture 2020-09-22 at 14 58 22

**Comment by datamel** [comment]
> Tested with greyscale backgrounds in my terminal, was worried that the submitted colour might be too pale but the switch to low colour mode saves it:
> 
> Kapture 2020-09-22 at 14 58 22

That is very jazzy!

**Comment by hjoliver** [comment]
Very nice @oliver-sanders :tada:

**Pull request merged**
