### PR TITLE
scan: workflow_params

### PR DESCRIPTION
**Pull request by oliver-sanders**
Required to solve https://github.com/cylc/cylc-uiserver/issues/223

* Add a workflow_params scan filter for reading the db workflow_params table
* This allows us to determine the workflow run UUID string when the
  scheduler is down (important for the UIS)

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Appropriate tests are included (unit and/or functional).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Review by wxtim — COMMENTED** [review]
- [x] Read code - looks sane.

Any thoughts on how to practically test this @oliver-sanders

**Comment by oliver-sanders** [comment]
> Any thoughts on how to practically test this @oliver-sanders

Try using it with your own workflows.

```
# untested

async def my_scan():
    async for flow in scan | workflow_params
        print(flow)

asyncio.run(my_scan())
```

**Comment by wxtim** [comment]
> > Any thoughts on how to practically test this @oliver-sanders
> 
> Try using it with your own workflows.
> 
> ```python
> # untested
> 
> async def my_scan():
>     async for flow in scan | workflow_params
>         print(flow)
> 
> asyncio.run(my_scan())
> ```

Thanks, that was enough to get me playing with. Now much more confident with my review.

**Review by wxtim — APPROVED** [review]
- [x] Sanity Checked
- [x] Played with, attempted to break it.

**Comment by wxtim** [comment]
Sorry @oliver-sanders , one post-hoc comment - suggestion for line ~36 of `cylc/flow/network/scan.py`:
```suggestion
.. autofunction:: workflow_params
```

**Comment by oliver-sanders** [comment]
Ooh, good point, had forgotten about that.

**Review by MetRonnie — APPROVED** [review]

**Pull request merged**
