### PR TITLE
Change UserInputError to InputError

### PR DESCRIPTION
**Pull request by hjoliver**
This is a small change with no associated Issue.

As I noted on Element chat (but got no response) `UserInputError`:
- sounds a bit insulting to the user
- the "User Input" bit is obvious (and therefore unnecessary) when it comes in response to a console command 
  - (Just `Error` would do, but the exception class name always gets printed...)

Just a quick search-and-replace one-liner:
```console
$ find cylc tests -type f | xargs perl -pi -e 's/UserInputError/InputError/g'
```

One 2-minute review will do if no one objects to the change. 

[UPDATE] Went with `InputError` rather than `CommandLineError` as originally suggested.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
UserInputError is used more widely than the CLI.

If the "User" part could be considered offensive (which I guess it could) then how 'bout dropping the "User" and going for "InputError"?

**Comment by hjoliver** [comment]
> (note need to check for imports of this exception in cylc-uiserver and cylc-rose)

Checked, no other use found.

**Comment by hjoliver** [comment]
> then how 'bout dropping the "User" and going for "InputError"?

Yep that's fine, and shorter.  Done.

**Review by oliver-sanders — APPROVED** [review]

**Comment by hjoliver** [comment]
Rebased and deconflicted. One review will do, IMO.

**Pull request merged**
