### PR TITLE
CLI option to disable log timestamps.

### PR DESCRIPTION
**Pull request by hjoliver**
Log timestamps are just visual garbage if you're following simple test suites during Cylc development.  This provides CLI access to our existing timestamp switch.

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.

- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
With `--no-timestamp`:
```
INFO - Suite server: url=tcp://niwa-1007885.niwa.local:43030/ pid=13872
INFO - Suite publisher: url=tcp://niwa-1007885.niwa.local:43043
INFO - Run: (re)start=0 log=1
INFO - Cylc version: 8.0a1
INFO - Run mode: live
INFO - Initial point: 1
INFO - Final point: 1
INFO - Cold Start 1
INFO - [foo.1] -submit-num=01, owner@host=niwa-1007885.niwa.local
INFO - [foo.1] -triggered off []
INFO - [foo.1] status=ready: (internal)submitted at 2020-06-04T09:08:42+12:00 for job(01)
INFO - [foo.1] -health check settings: submission timeout=None
INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
INFO - [foo.1] status=submitted: (received)started at 2020-06-04T09:08:43+12:00 for job(01)
INFO - [foo.1] -health check settings: execution timeout=None
INFO - [foo.1] status=running: (received)succeeded at 2020-06-04T09:08:43+12:00 for job(01)
INFO - Suite shutting down - AUTOMATIC
INFO - DONE
```

And without:
```
2020-06-04T09:08:23+12:00 INFO - Suite server: url=tcp://niwa-1007885.niwa.local:43057/ pid=13799
2020-06-04T09:08:23+12:00 INFO - Suite publisher: url=tcp://niwa-1007885.niwa.local:43006
2020-06-04T09:08:23+12:00 INFO - Run: (re)start=0 log=1
2020-06-04T09:08:23+12:00 INFO - Cylc version: 8.0a1
2020-06-04T09:08:23+12:00 INFO - Run mode: live
2020-06-04T09:08:23+12:00 INFO - Initial point: 1
2020-06-04T09:08:23+12:00 INFO - Final point: 1
2020-06-04T09:08:23+12:00 INFO - Cold Start 1
2020-06-04T09:08:23+12:00 INFO - [foo.1] -submit-num=01, owner@host=niwa-1007885.niwa.local
2020-06-04T09:08:23+12:00 INFO - [foo.1] -triggered off []
2020-06-04T09:08:24+12:00 INFO - [foo.1] status=ready: (internal)submitted at 2020-06-04T09:08:24+12:00 for job(01)
2020-06-04T09:08:24+12:00 INFO - [foo.1] -health check settings: submission timeout=None
2020-06-04T09:08:24+12:00 INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
2020-06-04T09:08:25+12:00 INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
2020-06-04T09:08:25+12:00 INFO - [foo.1] status=submitted: (received)started at 2020-06-04T09:08:24+12:00 for job(01)
2020-06-04T09:08:25+12:00 INFO - [foo.1] -health check settings: execution timeout=None
2020-06-04T09:08:25+12:00 INFO - [foo.1] status=running: (received)succeeded at 2020-06-04T09:08:25+12:00 for job(01)
2020-06-04T09:08:25+12:00 INFO - Suite shutting down - AUTOMATIC
2020-06-04T09:08:26+12:00 INFO - DONE
```

**Comment by hjoliver** [comment]
Briefly looked at unit testing this by extending `cylc/flow/tests/test_loggingutil.py`.  You can get the `caplog` fixture into test class methods like this:
```python
@pytest.fixture(autouse=True)
def inject_fixtures(self, caplog): 
    self._caplog = caplog 
```
Then in a test method:
```python
LOG.info("What could go") 
    assert self._caplog.records[0].message == "What could go"
```
However it doesn't seem to be possible to get the complete formatted log message from caplog (the timestamp is a LogRecord attribute). 

Might just have to do a small functional test...

**Comment by hjoliver** [comment]
2nd commit also removes *"at 2020-06-04T09:08:25+12:00"* for incoming task messages.
```
INFO - Suite server: url=tcp://niwa-1007885.niwa.local:43030/ pid=13872
INFO - Suite publisher: url=tcp://niwa-1007885.niwa.local:43043
INFO - Run: (re)start=0 log=1
INFO - Cylc version: 8.0a1
INFO - Run mode: live
INFO - Initial point: 1
INFO - Final point: 1
INFO - Cold Start 1
INFO - [foo.1] -submit-num=01, owner@host=niwa-1007885.niwa.local
INFO - [foo.1] -triggered off []
INFO - [foo.1] status=ready: (internal)submitted for job(01)
INFO - [foo.1] -health check settings: submission timeout=None
INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
INFO - [foo.1] status=submitted: (received)started for job(01)
INFO - [foo.1] -health check settings: execution timeout=None
INFO - [foo.1] status=running: (received)succeeded for job(01)
INFO - Suite shutting down - AUTOMATIC
INFO - DONE
```

**Comment by oliver-sanders** [comment]
> However it doesn't seem to be possible to get the complete formatted log message including the timestamp from caplog

That's because caplog is acting as a log handler rather than capturing the raw output of existing handlers.

**Comment by oliver-sanders** [comment]
Looks fine, tests ok.

**Comment by oliver-sanders** [comment]
I think this has been merged into the SoD PR (which should get merged very soon) so should we close this one to avoid conflicts?

**Comment by hjoliver** [comment]
> I think this has been merged into the SoD PR (which should get merged very soon) so should we close this one to avoid conflicts?

Yes I originally cherry-picked this from the SoD branch, but it looks like SoD will be merge soon so I'll close this...

**Pull request closed without merging**
