### PR TITLE
Incorporate jinja2filters into cylc.flow.jinja.filters, and use native namespaces

### LINKED ISSUE #2835: Make Jinja filters entry points
This is from one of the ideas (err.. actually it's a post-it in my workstation at work) after writing tests for the `parsec` package.

I realized that Cylc supports loading modules with Jinja2 from specific directories. While this works well, and provides extensibility to Cylc, I think it could be made more modular by entry points.

The idea is still a bit fuzzy in my mind, but I believe we could actually

1. remove the Jinja2filters from Cylc repository, and make it in its own module, published either via PYPI/Conda/Git/etc or downloaded by users + python setup.py install
2. use [entry points](https://packaging.python.org/specifications/entry-points/) to load existing implementations of jinja2 filters/extensions/etc

This would allow us to

1. allow us to release new versions of Jinja2filters without having to wait for a full release of Cylc
2. allow users to maintain their own modules (which could be uploaded to PYPI, Conda channels, internal repositories, Git, etc), and load them per environment/computer/cluster/etc

### PR DESCRIPTION
**Pull request by kinow**
Close #2835 

Hi,

Working on #3134 I had some hiccups with the `Jinja2Filters` after the CYLC_DIR is modified. It could be fixed there, but I prefer to keep these changes separated both for reviewers sake, and also for myself to manage feedback changes.

This pull request addresses this problem by

- Incorporating the dangling `Jinja2Fitlers` into `cylc` module, as `cylc.jinja2filters`
- Making the existing filters part of Cylc core (but happy to move to a separate project if others prefer)
- Removed the option to load `Jinja2Filters` from `CYLC_DIR` as that was broken (`CYLC_DIR` points to setuptools installation folder now, with only Python package data)
- Added `pkgutil` code in our `cylc/__init__.py` file, so that we could use [namespaces](https://packaging.python.org/guides/packaging-namespace-packages/)
- Loaded external filters from packages that used `cylc.jinja2filters`

The two last items means that users can still use the old approach of adding the folders somewhere to be loaded by Cylc, but can now also load filters by doing `pip install my-module`, assuming `my-module` contains:

1. `cylc/jinja2filters` package
2. `cylc` package **does not contain __init__.py**
3. there is some module inside the `cylc/jinja2filters` package that follows the convention of module_name == filters_name

Here's an example, that when installed with `pip install .` should make the `reverse_upper` available for Cylc workflows. It should be transparent for users, and give the same behavior as adding it to the  `Jinja2Filters` folder as before.

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
For the documentation, what I could come up with was:

```diff
diff --git a/doc/src/suite-config.rst b/doc/src/suite-config.rst
index 2416dadcd..51eb799ae 100644
--- a/doc/src/suite-config.rst
+++ b/doc/src/suite-config.rst
@@ -3297,8 +3297,8 @@ and tests.
 
 Cylc also supports custom Jinja2 globals, filters and tests. A custom global,
 filter or test is a single Python function in a source file with the same name
-as the function (plus ".py" extension) and stored in one of the following
-locations:
+as the function (plus ".py" extension). The filter can be stored in one of the
+following locations:
 
 - ``<cylc-dir>/lib/Jinja2[namespace]/``
 - ``[suite configuration directory]/Jinja2[namespace]/``
@@ -3306,6 +3306,10 @@ locations:
 
 where ``[namespace]/`` is one of ``Globals/``, ``Filters/`` or ``Tests/``.
 
+Alternatively, users can create a Python distribution package with the
+``cylc.jinja2filters`` package. Doing so, once the module is installed via
+``pip`` Cylc will be able to load the filter.
+
 In the argument list of filter or test function, the first argument is
 the variable value to be "filtered" or "tested", respectively, and
 subsequent arguments can be whatever else is needed. Currently there are three
```

Then I realized that the approach with setuptools will use only the _filters_ namespace of Jinja (leaving out _global_ and _tests_). Is that a problem?

**Comment by hjoliver** [comment]
> Then I realized that the approach with setuptools will use only the filters namespace of Jinja (leaving out global and tests). Is that a problem?

Can we not do the same kind of thing with global and tests, separately?

**Comment by kinow** [comment]
>Can we not do the same kind of thing with global and tests, separately?

Yes. There are three options to [load the plugins](https://packaging.python.org/guides/creating-and-discovering-plugins/) with setuptools (and this is a good exercise preparing for `xtriggers` future work):

1. We can keep using the approach from the doc linked above called _"Using namespace packages"_, but load from `cylc.jinja2filters.filters`, `cylc.jinja2filters.global`, and `cylc.jinja2filters.tests`. I think this would work, and we would know which filter goes to which scope. The `setup.py` requirements are only the [`packages=['cylc.jinja2filters']`](https://github.com/kinow/cylc-jinja2filters/blob/24276981b51bba19dd92356d61d8a51cf5321325/setup.py#L7) line.

2. Adopt the _"Using naming convention"_. Users need only a `setup.py` without needing to worry about package, but their modules would have to follow some naming convention such as `cylc_filter_filter_$FILTER_NAME`, or `cylc_filter_global_$FILTER_NAME`, or `cylc_filter_tests_$FILTER_NAME`, so that we know the scope. No other requirements for `setup.py`.

3. Or lastly as users to update their `setup.py`, with something similar to:

```python
setup(
    ...
    entry_points={
    'cylc.jinja2filters.filter': 'my_amazing_filter = crazy_module.subpackage.my_amazing_filter'}, # cylc.jinja2filters is an example, this could be any value for the dict key
    'cylc.jinja2filters.global': 'a_global_filter = crazy_module.tralala.a_global_filter'},
    'cylc.jinja2filters.tests': 'test_me = crazy_module.test_me'}
    ...
)
```

Then each key of that dictionary would be used to find the functions for each scope. 

These three options are listed in the [Python docs about plugins](https://packaging.python.org/guides/creating-and-discovering-plugins/), and any of them would work here. I think I prefer option #1 or #3.. but wouldn't mind if others preferred #2  (not slightly indecisive 😬 )

**Comment by hjoliver** [comment]
In case 1 (namespace packages) users just need to put their filters in the right package dir structure, right?  That sounds best to me.

There's a warning at bottom of this section https://packaging.python.org/guides/creating-and-discovering-plugins/#using-namespace-packages - but that seems to be about different ways of creating a namespace package, not complexity of use.

**Comment by kinow** [comment]
>In case 1 (namespace packages) users just need to put their filters in the right package dir structure, right? That sounds best to me.

Yup, that's correct.

>There's a warning at bottom of this section https://packaging.python.org/guides/creating-and-discovering-plugins/#using-namespace-packages - but that seems to be about different ways of creating a namespace package, not complexity of use.

I had a look over the documentation, then read the related PEP, but couldn't find any blockers for us to use this approach (I think I commented about it in the xtriggers issue). So far it's working fine. Yesterday I create a test suite to use the filter I created, and after `pip install .` in that filter project folder everything worked as expected. So so far so good 🤞

**Comment by kinow** [comment]
Just wait to see if @matthewrmshin has a different opinion on the approaches listed above. If he agrees on #1, will update the pull request.

@hjoliver what about the documentation? Update this pull request with something like the text block (in a git diff a few comments above) or leave it for later?

**Comment by hjoliver** [comment]
Yes we'll need documentation.  How about a new User Guide section on "Plugins", with a sub-section on how to make and use "Custom Plugins".  Then we can just link to that section from the xtrigger and Jinja chapters. Probably best to do it on this PR (once @matthewrmshin has agreed) while it's fresh in your mind.

**Comment by kinow** [comment]
Ooooh, good idea this plugins section! +1 !!! :tada:

**Comment by matthewrmshin** [comment]
Vote to support case 1.

**Comment by kinow** [comment]
I think we should be fine with case 1, and change it if necessary. This is the first case in Cylc using setuptools/pip for plugins, so we may have a few bumps, but eventually it will be production ready.

Pull request should be upgraded tomorrow morning NZ time.

**Comment by kinow** [comment]
Alright, the commits in this branch are not well organised yet, but have a working version of namespaces with `pkg-util`. Today already started preparing a version with native namespaces (https://github.com/kinow/cylc-flow/tree/incorporate-jinja2filters-2), but several tests failing at the moment, so I believe I missed something while moving files around.

**Comment by kinow** [comment]
Pull request updated. Now instead of `lib/cylc/`, we have `cylc/flow`. And the `cylc` folder is a native namespace package. i.e. it should not contain a `__init__.py`.

There are three other native namespaces used by parsec + jinja2, `cylc.flow.jinja.filters`, `cylc.flow.jinja.globals`, and `cylc.flow.jinja.tests`. I tested only `filters` with [this test project](https://github.com/kinow/cylc-jinja2filters/). It has a test suite in the README too (ignore the filters and globals as I did not implement proper filter/global variables).

Everything appears to be working fine. An quick way to review this change, is creating a new venv, then doing `pip install .`, followed by `pip show -f cylc-flow`. Then if you install that test project in the same venv, and do something like `pip show -f cylc-jinjafilters`, you should notice that it also includes files under the `cylc.flow.jinja.filters` package.

Travis is busy building it, and my last test will be with xtriggers. Just to make sure the `cylc.xtriggers` will work as well.

Cheers
Bruno

**Comment by kinow** [comment]
Added @matthewrmshin and @hjoliver as reviewers, but happy to take any extra reviews

**Comment by matthewrmshin** [comment]
Branch in conflict...

**Comment by matthewrmshin** [comment]
Codacy failure is genuine. (A class is imported twice as different names!) Otherwise, change looks OK despite the number of source files.

My brain has started to read `cylc.flow` as `cylc.flower`. (As Rose's namespace is already used in PyPI, perhaps we should package Rose as `cylc.flower` for PyPI :rose:!)

**Comment by kinow** [comment]
I might have added that duplicate import while moving files, sorry. Pull request updated, also rebased to fix latest conflict.

**Comment by hjoliver** [comment]
You've addressed @matthewrmshin's comments so I'll take this as approved, and we can get onto rebasing the other PRs.  (Note I wouldn't do this if we were closer to cylc-8 production).

**Pull request merged**
