### PR TITLE
Cycle point format colon restriction

### LINKED ISSUE #3369: Bug on master, with ':' in cycle point format?
[UPDATE: THIS EXAMPLE SUITE AND TRACEBACK IS WRONG - SEE BELOW]
```
[cylc]
    cycle point format = %Y-%m-%dT%H:%MZ  # ERROR
    #cycle point format = %Y%m%dT%H%M  # OK
[scheduling]
    initial cycle point = 2020
    [[dependencies]]
        [[[T00]]]
            graph = "foo"
```
Here's the error:
```
$ cylc run --no-detach five
            ._.                                                       
            | |                 The Cylc Suite Engine [8.0a0]         
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY.
      .___! |              It is free software, you are welcome to    
      !_____!             redistribute it under certain conditions;   
                        see `COPYING' in the Cylc source distribution. 
                                                                       
2019-09-16T11:26:14+12:00 WARNING - deprecated graph items were automatically upgraded in 'suite definition':
2019-09-16T11:26:14+12:00 WARNING -  * (8.0.0) [scheduling][dependencies][X][graph] -> [scheduling][graph][X] - for X in:
        T00
2019-09-16T11:26:14+12:00 INFO - Suite server: url=tcp://niwa-1007885.niwa.local:43082/ pid=13249
2019-09-16T11:26:14+12:00 INFO - Run: (re)start=0 log=1
2019-09-16T11:26:14+12:00 INFO - Cylc version: 8.0a0
2019-09-16T11:26:14+12:00 INFO - Run mode: live
2019-09-16T11:26:14+12:00 INFO - Initial point: 2020-01-01T00:00Z
2019-09-16T11:26:14+12:00 INFO - Final point: None
2019-09-16T11:26:14+12:00 INFO - Cold Start 2020-01-01T00:00Z
2019-09-16T11:26:14+12:00 ERROR - R/2020-01-01T12:00Z/P1D, point format %Y-%m-%dT%H:%MZ: equal adjacent points: 2020-01-01T12:00Z => 2020-01-01T12:00Z.
        Traceback (most recent call last):
          File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 253, in start
            self.run()
          File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/scheduler.py", line 1523, in run
            if self.pool.release_runahead_tasks():
          File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/task_pool.py", line 284, in release_runahead_tasks
            point = sequence.get_next_point(point)
          File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/cycling/iso8601.py", line 544, in get_next_point
            self._check_and_cache_next_point(point, next_point)
          File "/home/oliverh/cylc/cylc-flow/venv/lib/python3.7/site-packages/cylc/flow/cycling/iso8601.py", line 554, in _check_and_cache_next_point
            next_point, point
        cylc.flow.exceptions.SequenceDegenerateError: R/2020-01-01T12:00Z/P1D, point format %Y-%m-%dT%H:%MZ: equal adjacent points: 2020-01-01T12:00Z => 2020-01-01T12:00Z.
2019-09-16T11:26:14+12:00 CRITICAL - Suite shutting down - R/2020-01-01T12:00Z/P1D, point format %Y-%m-%dT%H:%MZ: equal adjacent points: 2020-01-01T12:00Z => 2020-01-01T12:00Z.
2019-09-16T11:26:15+12:00 INFO - DONE
SequenceDegenerateError: R/2020-01-01T12:00Z/P1D, point format %Y-%m-%dT%H:%MZ: equal adjacent points: 2020-01-01T12:00Z => 2020-01-01T12:00Z.
```

@dwsutherland the following does not set `sub_num` if `submit_num` is `None`:
https://github.com/cylc/cylc-flow/blob/master/cylc/flow/job_pool.py#L186-L188

The fact that this only seems to be triggered by a (valid) cycle point format with a `:` between hours and minutes suggests another error somewhere in splitting an ID perhaps?

### PR DESCRIPTION
**Pull request by dwsutherland**
These changes close #3369 

Also gave more information for both `:` and `/` when caught by the validation:
```
(flow) sutherlander@graphic-vbox:jox$ cylc validate jox
IllegalValueError: (type=cycle point format) [scheduler]cycle point format = %Y%m%dT%H:%MZ - (Illegal character: ":". Datetimes are used in Cylc file paths.)
```
```
(flow) sutherlander@graphic-vbox:jox$ cylc validate jox
IllegalValueError: (type=cycle point format) [scheduler]cycle point format = %Y%m%dT%H/%MZ - (Illegal character: "/". Datetimes are used in Cylc file paths.)
```

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Is covered by existing tests.
- [x] No change log entry required.
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
:+1:, need to update the docs in `cylc.flow.cfgspec.suite` which suggest `:` is legal.

Ran a scan on our site, didn't get any hits so I don't think this requires an entry in the migration guide.

**Comment by dwsutherland** [comment]
>  need to update the docs in cylc.flow.cfgspec.suite which suggest : is legal.

@oliver-sanders: Done, check that you are ok with the wording.

**Review by hjoliver — COMMENTED** [review]
Looks good, but coverage low. I've put a quick unit test PR up to your branch.

**Comment by dwsutherland** [comment]
> Looks good, but coverage low. I've put a quick unit test PR up to your branch.

Merged, thanks!

**Review by hjoliver — APPROVED** [review]

**Comment by hjoliver** [comment]
One review will do.

**Pull request merged**
