### PR TITLE
graphql: stabilise ID iteration order

### LINKED ISSUE #5366: linear ancestors not so linear
A nasty bug in the ancestor ordering which causes whole bunches of tasks to disappear from the UI!

For the following workflow:

```ini
[scheduling]             
    [[graph]]            
        R1 = A & B       
                         
[runtime]                
    [[A]]                
    [[A1]]               
        inherit = A      
    [[A2]]    
        inherit = None, A    
    [[a11]]    
        inherit = A1    
    [[a22]]    
        inherit = A2    
    [[B]]    
    [[B1]]    
        inherit = B    
    [[b]]    
        inherit = B1  
```

And this GraphQL request (run through GraphiQL):

```graphql
query {
  workflows {
    familyProxies {
      id
      ancestors {
        id
      }
    }
  }
}
```

I get this response:

```json
{
  "data": {
    "workflows": [
      {
        "id": "~/fam-test/run1",
        "familyProxies": [
          {
            "id": "~/fam-test/run1//1/B",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/B1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              },
              {
                "id": "~/fam-test/run1//1/B"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/A"
              },
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/A2",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
          {
            "id": "~/fam-test/run1//1/root",
            "ancestors": []
          }
        ]
      }
    ]
  }
}
```

What's interesting here is the difference between the ancestor order of A1 and B1:

```json
          {
            "id": "~/fam-test/run1//1/A1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/A"
              },
              {
                "id": "~/fam-test/run1//1/root"
              }
            ]
          },
```

```json
          {
            "id": "~/fam-test/run1//1/B1",
            "ancestors": [
              {
                "id": "~/fam-test/run1//1/root"
              },
              {
                "id": "~/fam-test/run1//1/B"
              }
            ]
           }
```

Despite having identical inheritance structures, the inheritance order is reversed with the `root` family at the bottom of one list and the top of the other.

Strangely it seems to be the family `A2` which introduces this behaviour with the `inherit = None` bit.

Because the UI relies on this field to compute the family tree things get confused and the tree ends up with three "root" notes, `A`, `B` & `root` which should be impossible (because there should only be one "root" node, and it should be called `root`!).

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by oliver-sanders**
> Sibling: https://github.com/cylc/cylc-ui/pull/1230

* A couple of ID lists were being converted to sets which caused the return order to become jumbled.
* Switch to a function which removes duplicates whilst maintaining order
* Closes #5366

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` Changelog entry added in cylc-ui.
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by wxtim — COMMENTED** [review]
It looks sane enough, but could you not use dictionary keys (ordered from 3.7) instead of a set?

Profiling makes `uniq` written this way look a bit faster, although it's only a comparison of 2 linears

image
image


I tried following the instructions in #5336 but couldn't re-create the original bug.

**Comment by oliver-sanders** [comment]
> but could you not use dictionary keys

Like this?

```python
ids = {key: None for key in ids}.keys()
```

**Comment by oliver-sanders** [comment]
Yes, that is remarkably efficient, I'll need to check through the code as `keys()` objects are a bit different to the standard containers, but I expect it will be fine.

**Comment by oliver-sanders** [comment]
> Went through the uses which are all iteration so dict.keys should be just fine, nice.

Sorry, the tests flagged that the items in the list aren't necessarily strings, or even `__hash__`able so the `dict.keys` approach don't work for all :(

I don't think the iteration time spent here is too big an issue compared to the graphql overheads, nice suggestion though.

**Comment by wxtim** [comment]
> 

Sorry, should have spotted that caveat .
I think I read something like at Python 2 `set([1, 2, 3])` is implementation-wise almost exactly the same as `{i: None for i in [1, 2, 3]}`, but they've diverged at Python.

**Review by dwsutherland — APPROVED** [review]
LGTM 👍

**Review by wxtim — APPROVED** [review]
- [x] Read Code
- [x] Accept that tests are in the UI in effect
- [x] Manual testing

**Pull request merged**
