### PR TITLE
`cylc vip/vr`: do not pass rose options to `cylc play`

### PR DESCRIPTION
**Pull request by MetRonnie**
Follow-up to #6068

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No dependency changes 
- [x] Tests are not included as it is not feasible
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by oliver-sanders — COMMENTED** [review]
LGTM

**Review by wxtim — COMMENTED** [review]
Looks sensible. Kicking self.

**Comment by MetRonnie** [comment]
Just codecov upload failing

**Review by oliver-sanders — APPROVED** [review]

**Comment by wxtim** [comment]
D'OH!

**Pull request merged**
