### PR TITLE
fixed missing symlink for tutorial workflow

### PR DESCRIPTION
**Pull request by wxtim**
This is a small change with no associated Issue.

Small change to tutorial workflow discovered during work on https://github.com/cylc/cylc-doc/pull/383

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Appropriate tests are included (unit and/or functional).
- [x] No change log entry required (ancilliary data).

- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
@wxtim how do I force it to use the data file?

**Comment by wxtim** [comment]
> @wxtim how do I force it to use the data file?

Tricky, since this is meant to allow for an external data source being flaky: I think that the following might do the trick
```diff
     badsites = []
     fails = True
     obs = None
+    first_try = True
     while dist < 1 and fails:
         try:
+            if first_try:
+                first_try = False
+                raise NoDataException
             obs = synop_grab(site_id, cycle_point)
             fails = False
         except NoDataException:
```

**Comment by oliver-sanders** [comment]
I tried this:

```python
def main(site_id, api_key=None):
    cycle_point = os.environ['CYLC_TASK_CYCLE_POINT']

    # Try to get the information from SYNOPS.
    dist = 0.0
    badsites = []   
    fails = True
    obs = None
    while dist < 1 and fails:
        try:
            obs = synop_grab(site_id, cycle_point)
            fails = False
        except NoDataException:
            badsites.append(f'{int(site_id):05d}')
            site_id, dist = get_nearby_site(site_id, badsites)

    obs = None
    if obs is None:
        # if api_key:
        #     print('Attempting to get weather data from DataPoint...')
        #     data = get_datapoint_data(site_id, cycle_point, api_key)
        # else:
        if True:
            print('No API key provided, falling back to archived data')
            data = get_archived_data(site_id, cycle_point)

        obs = extract_observations(data)
```

And got this:

```console
$ cylc cat-log cylc-forecasting-workflow//20220131T1000Z/get_observations_camborne -f e
...
FileNotFoundError: [Errno 2] No such file or directory: '~/cylc-run/cylc-forecasting-workflow/run1/data/20220131T1000Z/3808.json'

**Comment by wxtim** [comment]
@oliver-sanders  - that's not related to my changes, that looks like the archived data.

**Comment by oliver-sanders** [comment]
Retried:

```console
$ cylc cat-log cylc-forecasting-workflow//20220201T0300Z/get_observations_aldergrove -f o
Workflow : cylc-forecasting-workflow/run1
...

Requests Returned: 03917,2022,02,01,03,00,AAXX 01034 03917 45489 /2712 10097 20078 30134 40211 56011 333 55300 20000 88/15==

No API key provided, falling back to archived data
['~/cylc-run/cylc-forecasting-workflow/run1', 'data', '20220201T0300Z', '3917.json']
Opening File: ~/cylc-run/cylc-forecasting-workflow/run1/data/20220201T0300Z/3917.json
2022-02-01T10:00:22Z INFO - started

$ cylc cat-log cylc-forecasting-workflow//20220201T0300Z/get_observations_aldergrove -f e
Traceback (most recent call last):
  File "~/cylc-run/cylc-forecasting-workflow/run1/bin/get-observations", line 234, in <module>
    os.environ.get('API_KEY'))
  File "~/cylc-run/cylc-forecasting-workflow/run1/bin/get-observations", line 222, in main
    data = get_archived_data(site_id, cycle_point)
  File "~/cylc-run/cylc-forecasting-workflow/run1/bin/get-observations", line 106, in get_archived_data
    return json.load(open(path, 'r'))['SiteRep']['DV']['Location']
FileNotFoundError: [Errno 2] No such file or directory: '~/cylc-run/cylc-forecasting-workflow/run1/data/20220201T0300Z/3917.json'
2022-02-01T10:00:29Z CRITICAL - failed/ERR
```

**Comment by wxtim** [comment]
by setting `obs = None` you've ignored the entire 3rd party data bit, the only bit of the code that is meaningfully working (and failing) is 
```python
        if True:
            print('No API key provided, falling back to archived data')
            data = get_archived_data(site_id, cycle_point)

        obs = extract_observations(data)
```

**Comment by oliver-sanders** [comment]
Ok, attempt 2, I tried with this diff:

```diff
diff --git a/bin/get-observations b/bin/get-observations
index 16bcc04..2ebd06c 100755
--- a/bin/get-observations
+++ b/bin/get-observations
@@ -175,6 +175,7 @@ def synop_grab(site_id, time):
 
 def get_nearby_site(site_id, badsites):
     """Use Pythagoras to find the next nearest site."""
+    print(f'get_nearby_site({site_id}, {badsites})')
     lat, lon = reference_lat_long(site_id)
     src = Path(os.environ['CYLC_WORKFLOW_RUN_DIR']) / 'etc/met-office-sites.dat'
     info = Path(src).read_text()
@@ -206,6 +207,7 @@ def main(site_id, api_key=None):
     while dist < 1 and fails:
         try:
             obs = synop_grab(site_id, cycle_point)
+            raise NoDataException('whatever')
             fails = False
         except NoDataException:
             badsites.append(f'{int(site_id):05d}')
```

And inspected the obs output to ensure it was going via the get_nearby_site interface:

```console
$ cylc cat-log 'tutorial/cylc-forecasting-workflow/run1//20220202T1700Z/get_observations_aldergrove'
...
get_nearby_site(3091, ['03917', '03918', '03923', '03911', '03915', '03916', '03105', '03111', '03132', '03136', '03134', '03148', '03047', '03041', '03031', '03044', '03062', '03066', '03068', '03065', '03063', '03072', '03080', '03088', '03091'])
...
```

Yep, all good.

**Review by oliver-sanders — APPROVED** [review]

**Review by hjoliver — APPROVED** [review]
(One-liner, I'll take @oliver-sanders word for it!)

**Pull request merged**
