### PR TITLE
stop: fix tracebacks

### LINKED ISSUE #4758: `cylc stop` traceback
- [ ] **Bug 1:** When trying to stop multiple workflows that are already stopped

    ```
    $ cylc stop foo bar
    WorkflowStopped: bar is not running
    Task exception was never retrieved
    future: <Task finished name='Task-2' coro=<run() done,
        defined at ~/github/cylc-flow/cylc/flow/scripts/stop.py:181> exception=WorkflowStopped('foo')>
    Traceback (most recent call last):
    File "~/github/cylc-flow/cylc/flow/network/__init__.py", line 78, in get_location
        contact = load_contact_file(workflow)
    File "~/github/cylc-flow/cylc/flow/workflow_files.py", line 610, in load_contact_file
        raise ServiceFileError("Couldn't load contact file")
    cylc.flow.exceptions.ServiceFileError: Couldn't load contact file

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 214, in run
        pclient = get_client(workflow_id, timeout=options.comms_timeout)
    File "~/github/cylc-flow/cylc/flow/network/client_factory.py", line 55, in get_client
        return get_runtime_client(get_comms_method(), workflow, timeout=timeout)
    File "~/github/cylc-flow/cylc/flow/network/client_factory.py", line 49, in get_runtime_client
        return WorkflowRuntimeClient(workflow, timeout=timeout)
    File "~/github/cylc-flow/cylc/flow/network/client.py", line 131, in __init__
        host, port, _ = get_location(workflow)
    File "~/github/cylc-flow/cylc/flow/network/__init__.py", line 80, in get_location
        raise WorkflowStopped(workflow)
    cylc.flow.exceptions.WorkflowStopped: foo is not running
    ```

- [ ] **Bug 2:** When trying to stop at multiple cycles/tasks for the same workflow

    ```
    $ cylc stop datetime-cycling //2000 //2001
    Traceback (most recent call last):
    File "~/.conda/envs/cylc8/bin/cylc", line 33, in <module>
        sys.exit(load_entry_point('cylc-flow', 'console_scripts', 'cylc')())
    File "~/github/cylc-flow/cylc/flow/scripts/cylc.py", line 675, in main
        execute_cmd(command, *cmd_args)
    File "~/github/cylc-flow/cylc/flow/scripts/cylc.py", line 285, in execute_cmd
        entry_point.resolve()(*args)
    File "~/github/cylc-flow/cylc/flow/terminal.py", line 226, in wrapper
        wrapped_function(*wrapped_args, **wrapped_kwargs)
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 263, in main
        rets = call_multi(
    File "~/github/cylc-flow/cylc/flow/network/multi.py", line 29, in call_multi
        return asyncio.run(call_multi_async(*args, **kwargs))
    File "~/.conda/envs/cylc8/lib/python3.9/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "~/.conda/envs/cylc8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
    File "~/github/cylc-flow/cylc/flow/network/multi.py", line 88, in call_multi_async
        async for (workflow_id, *args), result in unordered_map(
    File "~/github/cylc-flow/cylc/flow/async_util.py", line 460, in unordered_map
        yield task._args, task.result()
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 187, in run
        raise Exception('Multiple TODO')
    Exception: Multiple TODO
    ```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Closes #4758

### CODE REVIEW

**Review by hjoliver — COMMENTED** [review]
If I try to stop two non-existent workflows on this branch:
```console
$ cylc stop foo bar
foo
Done
bar
Done
```

Shouldn't we distinguish between **stopped** and **not even installed**?

In this case, the `ServiceFileError` is caught and raised as `WorkflowStopped` in `network/__init__.py`, without checking the workflow is actually "stopped", or at least installed.

**Comment by oliver-sanders** [comment]
> In this case, the ServiceFileError is caught and raised as WorkflowStopped in network/__init__.py by the get_location function, without checking the workflow is actually "stopped", or at least installed.

This behaviour is a bit of a pain, e.g. https://github.com/cylc/cylc-flow/pull/4748.

Perhaps we should update this logic to raise a "workflow does not exist error" (note this will be raised by orphan jobs left running after the workflow is removed)

**Review by MetRonnie — COMMENTED** [review]
Other than Hilary's comment, manually testing ok. Perhaps a functional test would not go amiss?

**Comment by oliver-sanders** [comment]
Drafting this whilst I ponder on the consequences of changing the exception to handle the workflow does not exist case.

**Comment by oliver-sanders** [comment]
On a job host with `communications method = poll` it is not really possible to tell whether the workflow is running or not, or whether it even exists on the workflow host which makes it hard to truly differentiate these error cases.

That said, if possible it would be good to differentiate in this case, e.g. consider a workflow with "broadcast" tasks being ported to a polling job host. The error `WorkflowStopped` would not lead the porter to the issue.

**Comment by oliver-sanders** [comment]
Telling stopped from non-existent workflows, whilst simple in some cases is tricky in others and somewhat off topic for this issue.

Would be nice to do, one of the possible advantages would be assisting the porting of workflows to polling job hosts where `cylc` commands will currently fail with a confusing `WorkflowStopped` message.

Unfortunately in light of the above it might not be possible without changing the way we manage polling job hosts I.E. putting back the `contact2` file to allow them to tell when the parent workflow is running. This would work, but with the caveat that if the scheduler is killed or fails to remote-tidy it will continue to look like it's running from the remote's perspective (as a polling job host can't just SSH back to the scheduler host to check if it's still running, if we could do that the host would use TCP/SSH+TCP comms).

**Comment by oliver-sanders** [comment]
Have bumped the rest to an 8.1.0 issue - https://github.com/cylc/cylc-flow/issues/4798 - because It's not that quick a fix.

**Review by MetRonnie — APPROVED** [review]
Hasn't changed since my last review, right?

> Other than Hilary's comment, manually testing ok. Perhaps a functional test would not go amiss?

**Comment by hjoliver** [comment]
I'll merge this. Patch coverage is 100% anyway.

**Pull request merged**
