### PR TITLE
Replace O(N) lookup with O(1) for task outputs (master)

### LINKED ISSUE #3255: Speed up dependency checks for large numbers of outputs
We ran into a case where suites were taking a very long time to validate.  This was covered in #1776 and follow on tickets, but didn't quite solve the problem.  We tracked the behavior down to an O(N**2) operation in the number of task outputs.

Steps to reproduce: Have a very large number of task outputs (~1000)? in the graph that will be loaded.

Our solution was to replace a list with a set in the taskdef initialization that allowed checking for membership to be done in O(1) time instead of O(N) time (PR to follow)

### PR DESCRIPTION
**Pull request by matthewrmshin**
These changes close #3255. Supersedes #3268.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Appropriate tests are included (unit and/or functional).

- [x] Appropriate change log entry included.

- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Can you remove 746931d from this PR please (shouldn't go onto master)

**Comment by kinow** [comment]
Travis failures

```
./tests/authentication/05-full-control.t                        (Wstat: 0 Tests: 12 Failed: 3)
  Failed tests:  10-12
./tests/reload/17-graphing-change.t                             (Wstat: 0 Tests: 13 Failed: 1)
  Failed test:  13
```

**Comment by matthewrmshin** [comment]
@oliver-sanders and @kinow I'll look into those soon.

**Comment by matthewrmshin** [comment]
Removed 746931dad1d4e3fead2439a2f6a878a3054b34fd and squashed the `CHANGES.md` changes into one.

**Comment by matthewrmshin** [comment]
Test now good.

**Pull request merged**
