### PR TITLE
state totals fixes

### LINKED ISSUE #4157: cycle point status with workflow pause
Small bug in the GraphQL deltas which causes cycles to show as running when all tasks have finished.

In this example the cycle "8" shows up as running even though `a.8` has succeeded:

ui-fam-state

It is likely that the pause is the issue here as the status corrects itself once unpaused. Perhaps the "root" family state is being updated one iteration after the task state?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by dwsutherland**
These changes close #4157
image

Also fixes incorrect state totals (caused by only the deltas, and not the store totals, being collected).
Although I have noticed additional `succeeded` every now and then, which I will hunt down eventually but is only visible in TUI.

image

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]
:+1:

**Review by kinow — APPROVED** [review]
Tested the UI, on `master` got the states with different values than the ones displayed in the tree view, and also some weird state for the toolbar.

With this PR, the toolbar behaves correctly, and the states in GScan and in the tree view are matching. Great job @dwsutherland !

**Comment by kinow** [comment]
Got the issue I had seen on `master` again after trying a little more. Everything else seems to work fine, and this issue appears to be related to how we update the UI state after executing a mutation. Leaving it as approved as the code looks OK and the UI is working OK (cannot tell anything is wrong with stateTotals).

Will leave it to @oliver-sanders to finish the review :+1:

**Review by oliver-sanders — APPROVED** [review]
🍾

**Pull request merged**
