### PR TITLE
Check job not in prep already before triggering.

### LINKED ISSUE #4665: trigger: duplicate submit
In some niche circumstance it is possible for a trigger to action an additional submit of a task resulting in a submission failure.

Here's an example log where `cylc trigger <id>//5/a` resulted in a submission failure:

```
[5/a waiting(runahead) job:00 flows:1] spawned                     
[5/a waiting(runahead) job:00 flows:1] => waiting                  
[5/a waiting job:00 flows:1] => waiting(queued)                    
[5/a waiting(queued) job:00 flows:1] => waiting                    
Queue released: 5/a                                                
[5/a waiting job:00 flows:1] => preparing                          
[5/a preparing job:01 flows:1] host=hostname                       
[5/a preparing job:01 flows:1] => waiting                          
[5/a waiting job:01 flows:1] => waiting(queued)                    
[5/a waiting(queued) job:01 flows:1] queued, trigger again to submit now.    
Command succeeded: force_trigger_tasks(['5/a'], reflow=False, flow_descr=None)       [5/a waiting(queued) job:01 flows:1] => waiting                    
Queue released: 5/a                                                
[5/a waiting job:01 flows:1] => preparing                          
[5/a preparing job:02 flows:1] host=hostname                       
Unhandled jobs-submit output: 2022-02-08T15:01:43Z|5/a/01|0|105417    
Unhandled jobs-submit output: 2022-02-08T15:01:43Z|5/a/01|[STDOUT] 105417    
[jobs-submit cmd] cylc jobs-submit --path=/bin --path=/usr/bin --path=/usr/local/bin --path=/sbin --path=/usr/sbin --path=/usr/local/sbin -- '$HOME/cylc-run/two/log/job' 4/a/01 5/a/01 6/a/01
    [jobs-submit out] 2022-02-08T15:01:44Z|5/a/02|1                
[5/a preparing job:02 flows:1] (internal)submission failed at 2022-02-08T15:01:44Z
[5/a preparing job:02 flows:1] submission failed
[5/a preparing job:02 flows:1] => submit-failed                    
[jobs-submit cmd] cylc jobs-submit --path=/bin --path=/usr/bin --path=/usr/local/bin --path=/sbin --path=/usr/sbin --path=/usr/local/sbin -- '$HOME/cylc-run/two/log/job' 5/a/02
    FileNotFoundError: [Errno 2] No such file or directory: '~/cylc-run/two/log/job/5/a/02/job'                                                                           [jobs-submit cmd] cylc jobs-submit --path=/bin --path=/usr/bin --path=/usr/local/bin --path=/sbin --path=/usr/sbin --path=/usr/local/sbin -- '$HOME/cylc-run/two/log/job' 5/a/02
    [jobs-submit out] 2022-02-08T15:01:46Z|5/a/02|1
[5/a submit-failed job:02 flows:1] (internal)submission failed at 2022-02-08T15:01:46Z
[5/a submit-failed job:02 flows:1] submission failed
[5/a submit-failed job:02 flows:1] (received-ignored)started at 2022-02-08T15:01:47Z for job(01) != job(02)
```

Note the job submission number has been incremented.

Additional debug info:

```console
$ cylc cat-log two//5/a -s 1 -f a
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:52:41Z|5/a/01|0|68887
2022-02-08T14:52:41Z [STDOUT] 68887
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:53:48Z|5/a/01|0|72325
2022-02-08T14:53:48Z [STDOUT] 72325
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:55:03Z|5/a/01|0|77284
2022-02-08T14:55:03Z [STDOUT] 77284
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:55:52Z|5/a/01|0|81072
2022-02-08T14:55:52Z [STDOUT] 81072
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:56:37Z|5/a/01|0|86453
2022-02-08T14:56:37Z [STDOUT] 86453
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T14:58:01Z|5/a/01|0|92401
2022-02-08T14:58:01Z [STDOUT] 92401
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T15:00:33Z|5/a/01|0|98519
2022-02-08T15:00:33Z [STDOUT] 98519
[jobs-submit ret_code] 0
[jobs-submit out] 2022-02-08T15:01:08Z|5/a/01|0|101649
2022-02-08T15:01:08Z [STDOUT] 101649
[jobs-submit cmd] cylc jobs-submit --path=/bin --path=/usr/bin --path=/usr/local/bin --path=/sbin --path=/usr/sbin --path=/usr/local/sbin -- '$HOME/cylc-run/two/log/job' 4/a/01 5/a/01 6/a/01
[jobs-submit ret_code] 1
[jobs-submit out] 2022-02-08T15:01:44Z|5/a/02|1
[jobs-submit cmd] cylc jobs-submit --path=/bin --path=/usr/bin --path=/usr/local/bin --path=/sbin --path=/usr/sbin --path=/usr/local/sbin -- '$HOME/cylc-run/two/log/job' 5/a/02
[jobs-submit ret_code] 1
[jobs-submit out] 2022-02-08T15:01:46Z|5/a/02|1
$ cylc cat-log two//5/a -s 2 -f a
file not found: ~/cylc-run/two/log/job/5/a/02/job-activity.log
```

Note the second `jobs-submit cmd` entry in the `job-activity.log`. Why are there so many `jobs-submit` lines at the top?

I haven't developed a deterministic way to reproduce this yet, however, firing triggers off at random appears to trigger the bug more times than not.

```ini
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    runahead limit = P3
    [[graph]]
        P1 = """
            a
        """

[runtime]
    [[a]]
        script = sleep 1
```

```console
$ cylc play <id>
$ for x in $(seq 1 10); do cylc trigger <id>//$x/a; done
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #4665

Don't retrigger a task that is already preparing for job submission.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Added test.
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
I'm not sure how to reliably/repeatedly test this. Tasks do not stay in the `preparing` state for very long.

**Comment by hjoliver** [comment]
(unrelated flaky test failure)

**Comment by oliver-sanders** [comment]
Looks good, makes sense.

This is the sort of thing we should be able to cover with an integration test, I'll take a look.

**Review by oliver-sanders — APPROVED** [review]

**Review by MetRonnie — APPROVED** [review]
Confirmed the new test fails on master, passes on this branch

**Pull request merged**
