### PR TITLE
uid: warn if the run number is provided as a cycle

### LINKED ISSUE #4923: Detection of worklfow//task ID errors
This from an early Cylc 8 user (no training yet):

> I think your `cat-log` command is broken for printing out outputs/errors from a particular task. It has:
>
```console
$ cylc cat-log -f o waikanae//run1/setup
file not found: /home/xxx/cylc-run/waikanae/run1/log/job/run1/setup/NN/job.out
```
> when it should be
```console
/home/xxx/cylc-run/waikanae/run1/log/job/1/setup/NN/job.out
```
> At least based on the folders named - i.e. the second `run1` should just be `1`

We should be able to detect erroneous positioning of the double `//` in the command line above, since cycle points can't (currently at least!) be called `run1`, and print an informative error message.

### PR DESCRIPTION
**Pull request by oliver-sanders**
* E.G. workflow//run/cycle rather than workflow/run//cycle.
* Closes #4923

Screenshot from 2022-06-22 13-12-58

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Does not need tests (why?).
- [x] No change log entry required (minor change)
- [x] No documentation update required.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]
Nice, thanks @oliver-sanders :+1:

**Comment by dwsutherland** [comment]
Did we not generalize to checking whether it is a valid cycle point because it would involve parsing in the workflow def/config?

**Comment by hjoliver** [comment]
Yeah, but I guess without parsing the workflow config we could check for valid integer or ISO8601 datetime (assuming those are the only valid cycle point types, but that's fine for now). Might be worth it as a follow-up @oliver-sanders ?

**Comment by oliver-sanders** [comment]
> Did we not generalize to checking whether it is a valid cycle point

Invalid cycle points will get detected when they are passed through the internal `get_point` interface.

The UUID system does not attempt to validate cycle points, partly because it's a simple string parser, string in, string out, but also because:

* We don't know what cycle mode to use without parsing the workflow configuration.
* We may support more cycle formats one day, we could potentially support arbitrary parameters as cycle points.

**Pull request merged**
