### PR TITLE
Support nested subworkflows.

### PR DESCRIPTION
**Pull request by hjoliver**
REQUIRES #4821 
Supersedes #4477

A new job shell function to make it easy for users to run and manage subworkflows defined in sub-directories of the main workflow's source directory.
- these get installed with the main workflow (just like any main workflow source file)
- the installed subworkflow source is a template to create each subworkflow instance on the fly (one for each main workflow cycle point)
- the nesting is convenient for:
   - installing the subworkflow template automatically as part of the main workflow 
   - intuitive grouping under the main workflow
   - targeting main and subworkflows together, with cylc commands
 

NOTE:
- no change to any scheduler code (but relies on #4821)
- now **detaching** subworkflows, so (I think) it can be made to work with workflow migration

This is a small change with no associated Issue.

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
**Working example**

```console
$ tree hydro/
hydro/
├── flow.cylc
└── sub-wf
    └── flow.cylc
```

Main workflow:
```ini
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[graph]]
        P1 = "foo => sub => bar"
[runtime]
    [[foo, bar]]
        script = sleep 10
    [[sub]]
        script = cylc__job__subworkflow sub-wf 1/post
```

Sub-workflow:
```ini
[scheduling]
   [[graph]]
       R1 = "pre => proc => post"
[runtime]
   [[pre, post, proc]]
       script = "sleep $((10 + RANDOM % 10))"
```

**Comment by hjoliver** [comment]
Easy management and housekeeping, e.g.:

```
$ cylc stop hydro/run1/*  # stop hydro/run1 and any subworkflows
$ cylc clean hydro/run1/*  # clean up subworkflows of hydro/run1
```

**Comment by hjoliver** [comment]
**Limitations**

Subworkflow instances are not installed with `cylc install` (the template they are created from is, with the main workflow), so:
- their locations aren't individually configurable via symlink-dirs (however, the whole run-directory will be wherever the main run directory is symlinked to)
- installation hooks are bypassed, so subworkflows can't use `rose-suite.conf`...
- other?

**Review by oliver-sanders — COMMENTED** [review]
Sub workflows are a tricky problem, I completely understand (and support) the desire (I have use cases too), however, I don't think we can "neatly" package them as a solution at this point in time. We would need to develop much more advanced integration until which time users will need to be aware of the implementation details in order to understand how to work with them. For example what do the task statuses mean, how do you shut the workflow(s) down, how to identify/handle graph execution issues in sub-workflows, etc.

So I would be inclined to put this in the docs rather than implement it in the job script until we're ready to make this a formal & supported Cylc feature. Anyone who uses this approach really needs to understand what it is doing. The long-term solution will definitely require a different interface so this isn't an approach we can iterate to perfection.

The difference between `parent, parent/sub` and `parent/controller, parent/sub` is marginal. With UID `'parent/*'` allows them to be controlled as a block either way around so there isn't really any functional difference.

On the implementation side here are some pros and cons for the detatch/no-detach implementation detail:

#### No-Detach

pros:
* task:running means sub-workflow running.
* task:succeed means sub-workflow:succeeded which provides a handy shortcut for sub-workflow:finish-all which is otherwise hard to do (although if "all" tasks are expected to succeed `root:succeed-all => fin` is a valid approach)
* `cylc stop --kill` and `cylc kill` will work on the sub-workflows, kinda (workflow [events] could potentially niceify this sort of thing).
* Potentially compatible-ish with auto retries and `cylc trigger` (which could resume the workflow run).

cons:
* Workflow exit codes don't necessarily match data outcome expectations.
* Not great for branched workflows.
* Blocks workflow migration.

#### Detach:

pros:
* Permits workflow migration.
* Helps prevent workflow servers getting inundated with sub-workflows by allowing load balancing to kick in.

cons:

* task:running means sub-workflow task has not yet reached the desired state, however, does not convey whether the sub-workflow is able to reach that state at all (e.g. it could have stalled, or the task failed, this state will *not* make it back to the parent workflow even if the sub-workflow is configured to shutdown in this eventuality).
* `cylc stop`, `cylc stop --kill` and `cylc kill` don't really do what the user wants/expects.

#### Some problems to consider:

1. How to differentiate "restarting" a sub-workflow from "re-running" a sub-workflow.
2. How to feed sub-workflow info back to the UI (short to mid term), if we use xtriggers then #4582 would work but we can't achieve this with a standalone task (task metadata would be an option but it is static).
3. How to differentiate sub-workflow not is running / stalled / whatever from targetted task(s) have not reached the desired state yet.
4. How to integrate with `cylc install` features, perhaps the sub-workflow installation should be implemented within `cylc install` (special logic for sub-workflows)
   * symlink-dirs
   * run numbers
   * easy reinstallation?

**Comment by hjoliver** [comment]
Note my final commit overlapped your review, and tweaked the model a bit to report not-running+not-finished as failed. 

Some of the concerns above are arguably not important if sub-workflows are (as they really should be) treated as a monolithic task in the main workflow (and of course are appropriate for use in that way) ... in which case, if the sub-workflow fails or stops without finishing for any reason, then it is "failed" and retriggering it in the main workflow should run it again from scratch (although I was experimenting with restarts too without commenting on that).

However, I generally agree. Particularly that anyone using this approach must understand exactly what the implications are) and had also been thinking about the various points above.

Plus: https://github.com/cylc/cylc-flow/pull/4821#issuecomment-1119081989

And: this shell function is not really Cylc-integrated in anyway so I can just go for a workflow bin script for now, for my current sub-workflow users.  So, closing this!!!!

**Pull request closed without merging**
