### PR TITLE
Use different variable names in nested loops

### PR DESCRIPTION
**Pull request by kinow**
Very little risk, but just to avoid accidentally using the incorrect `name` or `cycle` variable. Also updates docstrings.

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Already covered by existing tests.

- [x] No change log entry required (why? e.g. invisible to users).

- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Let me check for more flaky tests... if these tests pass locally (or have passed in my fork's build) will raise another PR to move them to `flakytests` directory.

**Comment by kinow** [comment]
One test is being fixed by @hjoliver 's recent PR. But the other one is not, and also is not in the flaky tests. Should we move it to the `flakytests` dir?

```
===(     184;587  2/3  2/5  0/3  1/2  0/3 )=============================sort: cannot read: broadcast.log: No such file or directory
--- broadcast.log.sorted	2019-08-26 07:25:40.607546000 +0000
+++ broadcast.ref	2019-08-26 07:21:59.510149999 +0000
@@ -0,0 +1,34 @@
+20100808T00 bar BCAST is BAR
+20100808T00 baz BCAST is ROOT
+20100808T00 foo BCAST is FOO
+20100808T00 m1 BCAST is ENS1
+20100808T00 m2 BCAST is ENS1
+20100808T00 m3 BCAST is ENS1
+20100808T00 m4 BCAST is ENS1
+20100808T00 m5 BCAST is ENS1
+20100808T00 m6 BCAST is ENS1
+20100808T00 m7 BCAST is M7
+20100808T00 m8 BCAST is M8
+20100808T00 m9 BCAST is M9
+20100808T00 n1 BCAST is ENS
+20100808T00 o1 BCAST is ENS
+20100808T00 qux BCAST is ROOT
+20100808T00 wibble BCAST is ROOT
+20100808T00 wobble BCAST is ROOT
+20100809T00 bar BCAST is BAR
+20100809T00 baz BCAST is BAZ
+20100809T00 foo BCAST is ROOT
+20100809T00 m1 BCAST is ENS1
+20100809T00 m2 BCAST is M2
+20100809T00 m3 BCAST is ENS1
+20100809T00 m4 BCAST is ENS1
+20100809T00 m5 BCAST is ENS1
+20100809T00 m6 BCAST is ENS1
+20100809T00 m7 BCAST is M7
+20100809T00 m8 BCAST is M8
+20100809T00 m9 BCAST is M9
+20100809T00 n1 BCAST is ENS
+20100809T00 o1 BCAST is ENS
+20100809T00 qux BCAST is ROOT
+20100809T00 wibble BCAST is ROOT
+20100809T00 wobble BCAST is ROOT
--- -	2019-08-26 07:25:40.732292046 +0000
+++ select-broadcast-events.out	2019-08-26 07:25:40.707495999 +0000
@@ -12,4 +12,3 @@
 +|*|m7|[environment]BCAST|M7
 +|*|m8|[environment]BCAST|M8
 +|*|m9|[environment]BCAST|M9
--|20100808T00|foo|[environment]BCAST|FOO
--- -	2019-08-26 07:25:40.827316263 +0000
+++ select-broadcast-states.out	2019-08-26 07:25:40.783457999 +0000
@@ -5,5 +5,6 @@
 *|m8|[environment]BCAST|M8
 *|m9|[environment]BCAST|M9
 *|root|[environment]BCAST|ROOT
+20100808T00|foo|[environment]BCAST|FOO
 20100809T00|baz|[environment]BCAST|BAZ
 20100809T00|m2|[environment]BCAST|M2
    stdout and stderr stored in: /tmp/travis/cylctb-20190826T071549Z/broadcast/00-simple
    suite logs can be found under: /home/travis/cylc-run/cylctb-20190826T071549Z/broadcast/00-simple/log/suite/
[07:25:40] ./tests/broadcast/00-simple.t .................................................... Failed 4/5 subtests
```

**Comment by matthewrmshin** [comment]
The `tests/broadcast/00` is way too complex for its own good. It becomes flaky when there is a client timeout.

**Comment by hjoliver** [comment]
> The `tests/broadcast/00` is way too complex for its own good. It becomes flaky when there is a client timeout.

Should it be moved to the `flaky/` dir then?

**Pull request merged**
