### PR TITLE
Remove unused code in cylc.flow.config (template keys)

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

I had submitted a pull request to Cylc UI Server for upgrading JupyterHub & Tornado, and also ran the IDE linter to make sure there was nothing else that needed changing after upgrading. Did not find anything, and last step was running `vulture`, which also did not find anything.

Then just for curiosity ran it against Cylc Flow, and it found many possible unused variables/code. I checked just this one and quickly prepared a PR before going back to deltas in the UI, but there might be others 👍 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Comment by kinow** [comment]
One review should do I think. This variable appears to be unused after this commit: https://github.com/cylc/cylc-flow/commit/63d2995c09c76f6e2ef96d2ac016b6a78819b7f3

**Comment by hjoliver** [comment]
I think I recall commenting on this last week in one of @MetRonnie's PRs, so he may have already removed the code. Lemme check...

**Comment by hjoliver** [comment]
The comment is in the batch system / job-runner issue, here: https://github.com/cylc/cylc-flow/issues/3910#issuecomment-740993877

**Comment by kinow** [comment]
> 
> 
> The comment is in the batch system / job-runner issue, here: [#3910 (comment)](https://github.com/cylc/cylc-flow/issues/3910#issuecomment-740993877)

Ah! He fixed it already! Let me close this one. Thanks @hjoliver !

**Comment by hjoliver** [comment]
Yes he has deleted it in #3992

**Pull request closed without merging**
