### PR TITLE
Update protobuf and pyzmq

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] Appropriate change log entry included.
- [x] No documentation update required.
- [ ] Created an issue at [cylc-flow conda-forge repository](https://github.com/conda-forge/cylc-flow-feedstock) with version changes (if you changed dependencies in `setup.py`, see `recipe/meta.yaml`).

### CODE REVIEW

**Comment by kinow** [comment]
Changes in [`protobuf` 3.13](https://github.com/protocolbuffers/protobuf/releases/tag/v3.13.0)

```
    JSON format conformance fixes:
        Reject lowercase t for Timestamp json format.
        Print full_name directly for extensions (no camelCase).
        Reject boolean values for integer fields.
        Reject NaN, Infinity, -Infinity that is not quoted.
        Base64 fixes for bytes fields: accept URL-safe base64 and missing padding.
    Bugfix for fields/files named "async" or "await".
    Improved the error message when AttributeError is returned from getattr
    in EnumTypeWrapper.
```

And in [`pyzmq` 19](https://pyzmq.readthedocs.io/en/latest/changelog.html):

```

    Cython backend: Build Cython extensions with language level “3str” (requires Cython 0.29)
    Cython backend: You can now cimport zmq
    Asyncio: Fix memory leak in Poller
    Log: Much improved logging in zmq.log (see Asynchronous Logging via PyZMQ)
    Log: add python -m zmq.log entrypoint
    Sources generated with Cython 0.29.15

```

**Comment by kinow** [comment]
Re-compiled the `.proto` file, but looks like it only added a new comment :laughing: 

```
protoc --experimental_allow_proto3_optional -I=./ --python_out=./ data_messages.proto
```

Version

```
protoc --version
libprotoc 3.13.0

```

**Comment by kinow** [comment]
If CI passes, and reviewers approve, I'll create the PR in cylc-flow-feedstock :+1:

**Comment by dwsutherland** [comment]
> looks like it only added a new comment 😆

Well done! will check soon... But tests passing so meh

**Review by oliver-sanders — APPROVED** [review]

**Review by dwsutherland — APPROVED** [review]
@kinow - I think I'm a little wary about not having a fixed protobuf version, as we'd have to trust they don't put breaking changes between subversions.. And people use the latest sub-version binary when generating the module..

We'll see how it goes.. 👍

**Comment by kinow** [comment]
> @kinow - I think I'm a little wary about not having a fixed protobuf version, as we'd have to trust they don't put breaking changes between subversions.. And people use the latest sub-version binary when generating the module..
> 
> We'll see how it goes.. +1

Ah, I realized just now that I used a version range instead of the latest version pinned. It will be a good experiment to see if anything happens with their patch updates, but hopefully that should work :crossed_fingers: 

Creating the sibling PR for Conda. Thanks @dwsutherland !

**Comment by dwsutherland** [comment]
> Ah, I realized just now that I used a version range instead of the latest version pinned. It will be a good experiment to see if anything happens with their patch updates, but hopefully that should work 🤞

Given that there release page is still at 3.13.0 .. It'll likely be fine..
https://github.com/protocolbuffers/protobuf/releases

**Pull request merged**
