### PR TITLE
Use correct variable to avoid traceback

### LINKED ISSUE #3242: Traceback on calling cylc check-versions five
**Describe the bug**

Running `cylc check-versions five` results in a traceback due to the wrong variable used in the code (method receives `opts`, we use `options` in the code).

**Release version(s) and/or repository branch(es) affected?**

`master` and `8.x` I believe. `7.8` is [fine](https://github.com/cylc/cylc-flow/blob/0cc4b468b5ff01a6af201a2dad6b2851b2a8c79c/bin/cylc-check-versions).

**Steps to reproduce the bug**

On `master`, run `cylc check-versions $valid-suite`

**Expected behavior**

Not a traceback, maybe the normal output (which I am not familiar with, sorry).

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by kinow**
This closes #3242 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] These changes are already covered by existing tests.
- [x] No change log entry required (e.g. change is small or internal only).
- [x] No documentation update required for this change.

### CODE REVIEW

**Comment by kinow** [comment]
> No change log entry required (e.g. change is small or internal only).

No change since 7.8.x as 8.x is not released yet... but happy to add an entry to the changelog if others think we need to document this one.

Found a few more issues running the code linters at work while writing some unit tests (IDE update with new features in the linter integration), but that's the last one of the day :+1:

**Comment by kinow** [comment]
(@matthewrmshin also kicked this one three times, together with that other PR, and Travis is annoyingly failing :/)

**Comment by matthewrmshin** [comment]
(Looks like the same 2 tests failing!)

**Comment by hjoliver** [comment]
Approved.  @matthewrmshin - merge at will (I presume T-CI fail is unrelated) ... I'm off to :sleeping_bed: ...

**Comment by kinow** [comment]
Thanks @hjoliver !

**Pull request merged**
