### PR TITLE
Add `BroadcastCyclePoint` type to schema

### PR DESCRIPTION
**Pull request by MetRonnie**
This is a small change with no associated Issue.

Needed for proper mutation form validation - https://github.com/cylc/cylc-ui/pull/1073

The Broadcast cycle point option can be a cycle point or `*` (supports either of those two but not cycle point globs)

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Does not need tests (why?).
- [x] Change log entry included
- [x] No documentation update required.
- [ ] [if bugfix] PRs raised to both master and the relevant bugfix branch.

### CODE REVIEW

**Comment by MetRonnie** [comment]
> The Broadcast cycle point option can be a cycle point or `*` (supports either of those two but not cycle point globs)

Or can it? This was the impression I got from the descriptions

**Comment by MetRonnie** [comment]
(Test failure due to failed coverage fetch only)

**Comment by oliver-sanders** [comment]
> Or can it? This was the impression I got from the existing code but it isn't explicitly stated

I think `*` is just a marker for "all cycles" not a glob.

https://github.com/cylc/cylc-flow/blob/0e0d1a6d2d4f1d918b41e5463775a08671d727fc/cylc/flow/broadcast_mgr.py#L250-L255

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
@datamel Could you try this out? Try using the broadcast mutation edit form in the UI, you should find that the broadcast cycle point option can be a cycle point or `*` (supports either of those two but not cycle point globs)

**Comment by datamel** [comment]
@MetRonnie, have you this working in the gui? I get an Invalid Cycle Point for `*`.

**Comment by MetRonnie** [comment]
Working for me, only errors when I add a space or letter etc. to make it invalid
demo7

**Comment by datamel** [comment]
Thanks, maybe I have something up with my build. I get an invalid cycle point and then if I add a space I get a Cannot contain spaces error. I will re-build and see if I can spot my mistake.

**Review by datamel — APPROVED** [review]
A fresh environment has solved my problems with this. Thanks @MetRonnie.

**Comment by MetRonnie** [comment]
@datamel If you're happy with my conflict-resolve merge commit then hit the merge button

**Pull request merged**
