### PR TITLE
Remove upper pin on setuptools

### PR DESCRIPTION
**Pull request by MetRonnie**
Once a new version of `packaging` has been released:
- https://github.com/pypa/setuptools/issues/3802#issuecomment-1427689516

**Check List**

- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] PR should be raised against `8.1.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Rather than upper-pinning we should be able to exclude the broken releases explicitly.

**Comment by MetRonnie** [comment]
Currently waiting on next release of setuptools

**Comment by MetRonnie** [comment]
Released, kicking tests

**Comment by MetRonnie** [comment]
Swarm build steps failed because the new version is not available on conda yet

**Comment by MetRonnie** [comment]
Waiting for https://github.com/conda-forge/setuptools-feedstock/pull/318, not sure what's the hold-up there

**Comment by oliver-sanders** [comment]
Merged.

**Comment by MetRonnie** [comment]
Functional test failure due to random homebrew flake, I'm not bothering to re-run it myself

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
