### PR TITLE
flaky test: cylc-poll/16-execution-time-limit.t

### PR DESCRIPTION
**Pull request by oliver-sanders**
WIP: pending on Travis results

### CODE REVIEW

**Comment by oliver-sanders** [comment]
The test is failing as the "health check settings" log line is missing the `execution timeout` component:

```
2019-05-14T10:40:39Z INFO - [foo.1] -health check settings: submission timeout=None, polling intervals=PT2S,...
```

Running locally I see

```
2019-05-14T11:26:44+01:00 INFO - [foo.1] -health check settings: execution timeout=PT10S, polling intervals=PT10S,...
```

**Comment by oliver-sanders** [comment]
Is polling working correctly here?

For the following globalrc:

```ini
[hosts]
   [[localhost]]
        task communication method = poll
        submission polling intervals = PT2S
        execution polling intervals = PT1M
        [[[batch systems]]]
            [[[[background]]]]
                execution time limit polling intervals = PT5S'
```

Submission polling occurs ~PT2S after submission as expected:

```
2019-05-14T10:40:39Z INFO - [foo.1] status=ready: (internal)submitted at 2019-05-14T10:40:39Z for job(01)
2019-05-14T10:40:39Z INFO - [foo.1] -health check settings: submission timeout=None, polling intervals=PT2S,...
2019-05-14T10:40:42Z INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-14T10:40:44Z))
2019-05-14T10:40:44Z INFO - [foo.1] status=submitted: (polled)submitted at 2019-05-14T10:40:39Z for job(01)
```

But then we get another poll PT2S later:

```
2019-05-14T10:40:44Z INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-14T10:40:46Z))
2019-05-14T10:40:46Z INFO - [foo.1] status=failed: (polled)failed at 2019-05-14T10:40:45Z for job(01)
```
I would have expected the next poll after either:

* execution polling intervals = PT1M
* execution time limit + execution time limit polling intervals = PT5S + PT5S

**Comment by hjoliver** [comment]
Rep WIP label: you can mark a PR as a Draft now when you post it (built in GitHub functionality).

**Comment by hjoliver** [comment]
> The re-run passed?! 

Yeah, that is weird!!  (And no doubt is why we didn't notice that we'd broken the test.  (I think a recent-ish change by Matt tidied up the health check log line format ... might have been that one).

**Comment by hjoliver** [comment]
> Is polling working correctly here? 

Current behaviour for "polling intervals" is documented as "Each list value is used in turn until the last, which is used repeatedly until finished." ... so a single value will be used repeatedly, not just once.

**Comment by hjoliver** [comment]
I just tried https://github.com/cylc/cylc-flow/issues/2894#issuecomment-492447397 (for this test, without your fix) ... cannot get it to fail locally or on Travis if repeatedly run alone.  There must be some load dependence (timing).  But why doesn't it always fail due to the bad log line above?!

**Comment by matthewrmshin** [comment]
(In my experience, this test tends to fail only in a busy environment - hence I have tuned up the tolerance to 10s previously, but may be it is failing due to some other reasons now?)

**Comment by oliver-sanders** [comment]
> Re WIP label: you can mark a PR as a Draft now when you post it (built in GitHub functionality). And then it can't be merged until "un-drafted".

Sadly Travis doesn't run for drafts.

**Comment by oliver-sanders** [comment]
> Current behaviour for "polling intervals" is documented as "Each list value is used in turn until the last, which is used repeatedly until finished." ... so a single value will be used repeatedly, not just once.

But should the submission polling continue once the job has started executing?

**Comment by kinow** [comment]
>Sadly Travis doesn't run for drafts.

I think it does, but does not appear as a check in the pull request. It should be available in your own Travis CI for your fork - if enabled.

**Comment by hjoliver** [comment]
> 
> 
> > Re WIP label: you can mark a PR as a Draft now when you post it (built in GitHub functionality). And then it can't be merged until "un-drafted".
> 
> Sadly Travis doesn't run for drafts.

You can enable Travis for branches in your fork though (that's what I do).

**Comment by hjoliver** [comment]
> 
> 
> > Current behaviour for "polling intervals" is documented as "Each list value is used in turn until the last, which is used repeatedly until finished." ... so a single value will be used repeatedly, not just once.
> 
> But should the submission polling continue once the job has started executing?

Ah, presumably not!

**Comment by oliver-sanders** [comment]
> Ah, presumably not!

@matthewrmshin I've got a bad feeling this flaky test may be revealing a [polling bug](https://github.com/cylc/cylc-flow/pull/3163#issuecomment-492191315).

Hopefully I'm wrong. Does the reported behaviour make sense to you?

**Comment by matthewrmshin** [comment]
Calculation all done under `cylc.flow.task_events_mgr` `TaskEventsManager._reset_job_timers` - when messages, etc are handled. Spot any bug?

**Comment by oliver-sanders** [comment]
Is that a yes or a no?

**Comment by matthewrmshin** [comment]
Not that I'm aware of, but someone may find one.

**Comment by hjoliver** [comment]
> But should the submission polling continue once the job has started executing?

Test suite says no:
```
(venv) [oliverh@thug-life cylc-flow]$ cylc view --stdout foo
[scheduling]
  [[dependencies]]
     graph = foo
[runtime]
  [[foo]]
     script = sleep 30
     [[[job]]]
        batch system = background_10
        submission polling intervals = PT2S
```
Where I engineered a 10-sec submission delay like this:
```
[oliverh@thug-life cylc-flow]$ diff cylc/flow/batch_sys_handlers/background*                                                                                                         
66c66
<                     (r'''/usr/bin/sleep 10 && exec%s "$0" <'/dev/null' >"$0.out" 2>"$0.err"''' %
---
>                     (r'''exec%s "$0" <'/dev/null' >"$0.out" 2>"$0.err"''' %
```
Result:
```
(venv) [oliverh@thug-life cylc-flow]$ cylc run --no-detach foo
            ._.                                                       
            | |                 The Cylc Suite Engine [8.0a0]         
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY.
      .___! |              It is free software, you are welcome to    
      !_____!             redistribute it under certain conditions;   
2019-05-16T09:34:02+12:00 INFO - Suite server: url=tcp://niwa-1007885.niwa.local:43047/ pid=18007
2019-05-16T09:34:02+12:00 INFO - Run: (re)start=0 log=1
2019-05-16T09:34:02+12:00 INFO - Cylc version: 8.0a0
2019-05-16T09:34:02+12:00 INFO - Run mode: live
2019-05-16T09:34:02+12:00 INFO - Initial point: 1
2019-05-16T09:34:02+12:00 INFO - Final point: 1
2019-05-16T09:34:02+12:00 INFO - Cold Start 1
2019-05-16T09:34:02+12:00 INFO - [foo.1] -submit-num=01, owner@host=niwa-1007885.niwa.local
2019-05-16T09:34:03+12:00 INFO - [foo.1] status=ready: (internal)submitted at 2019-05-16T09:34:03+12:00 for job(01)
2019-05-16T09:34:03+12:00 INFO - [foo.1] -health check settings: submission timeout=None, polling intervals=PT2S,...
2019-05-16T09:34:06+12:00 INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-16T09:34:08+12:00))
2019-05-16T09:34:07+12:00 INFO - [foo.1] status=submitted: (polled)submitted at 2019-05-16T09:34:03+12:00 for job(01)
2019-05-16T09:34:08+12:00 INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-16T09:34:10+12:00))
2019-05-16T09:34:09+12:00 INFO - [foo.1] status=submitted: (polled)submitted at 2019-05-16T09:34:03+12:00 for job(01)
2019-05-16T09:34:10+12:00 INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-16T09:34:12+12:00))
2019-05-16T09:34:11+12:00 INFO - [foo.1] status=submitted: (polled)submitted at 2019-05-16T09:34:03+12:00 for job(01)
2019-05-16T09:34:12+12:00 INFO - [foo.1] -poll now, (next in PT2S (after 2019-05-16T09:34:14+12:00))
2019-05-16T09:34:13+12:00 INFO - [foo.1] status=submitted: (polled)submitted at 2019-05-16T09:34:03+12:00 for job(01)
2019-05-16T09:34:13+12:00 INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
2019-05-16T09:34:14+12:00 INFO - [foo.1] status=submitted: (received)started at 2019-05-16T09:34:13+12:00 for job(01)
2019-05-16T09:34:14+12:00 INFO - [foo.1] -health check settings: execution timeout=None
2019-05-16T09:34:33+12:00 INFO - [client-command] put_messages oliverh@niwa-1007885.niwa.local:cylc-message
2019-05-16T09:34:34+12:00 INFO - [foo.1] status=running: (received)succeeded at 2019-05-16T09:34:33+12:00 for job(01)
2019-05-16T09:34:34+12:00 INFO - Suite shutting down - AUTOMATIC
2019-05-16T09:34:34+12:00 INFO - DONE
```

i.e. submission polling stops once the job starts executing.  Phew :grin:

**Comment by matthewrmshin** [comment]
Yes, but I've no idea if the logic breaks down under a very busy environment or not.

**Comment by hjoliver** [comment]
Hmmm, I wouldn't have thought so.  Hopefully its just timing assumptions in the test suite, which compares expected and actual times.  (Otherwise, a nasty one to debug!)

**Comment by hjoliver** [comment]
> > Ah, presumably not!
> 
> @matthewrmshin I've got a bad feeling this flaky test may be revealing a [polling bug](https://github.com/cylc/cylc-flow/pull/3163#issuecomment-492191315).
> 
> Hopefully I'm wrong. Does the reported behaviour make sense to you?

I've just looked back above at your reported behaviour ... I don't see any evidence there that submission polling continues after the job starts executing, just that it polls multiple times (which is expected, until the job starts executing).  But maybe you accidentally omitted the evidence?

**Comment by oliver-sanders** [comment]
I think I've convinced myself that this is OK.

Have updated the test to use the first log line matching submitted or failed to remove tests dependence on race conditions. Seems to pass consistently for me, lets see how it performs under load.

**Comment by hjoliver** [comment]
Arghhh!!! it failed.

**Comment by oliver-sanders** [comment]
"£$%^&*

Well at least it failed consistently, progress?

**Comment by oliver-sanders** [comment]
Test still flaky...

**Comment by oliver-sanders** [comment]
I cannot see a way forward with this approach ATM :(

**Pull request closed without merging**
