### PR TITLE
fix todos

### PR DESCRIPTION
**Pull request by oliver-sanders**
Mop up a few TODOs.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Review by wxtim — APPROVED** [review]
Again, thanks for fixing my mistakes.
Looks like the functional test failure is in cylc-rose. I think that moving those fn'l tests to Cylc Rose is perhaps higher up my list of things to do, to avoid this sort of thing happening in future....
I've had a poke at it on master, but the error message
```
PluginError: Error in plugin cylc.pre_configure.rose
unexpected char '#' at 10
```
isn't massively helpful.

Not sure what is going on with the bash tests.

**Comment by oliver-sanders** [comment]
> Not sure what is going on with the bash tests.

Broken on this branch, should pass now.

**Comment by wxtim** [comment]
I think codecov makes a valid point about some of the unchecked testing sections...

**Comment by oliver-sanders** [comment]
Codecov results keep going up until the last test has reported back, atm the results are incomplete...

**Review by datamel — APPROVED** [review]

**Comment by oliver-sanders** [comment]
(Codecov has got in a twist with files not touched in this PR)

**Pull request merged**
