### PR TITLE
Death to the word "suite".

### PR DESCRIPTION
**Pull request by hjoliver**
Change command name `cylc get-suite-contact` to `cylc get-scheduler-contact` (for obvious reasons).

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [ ] Appropriate tests are included (unit and/or functional).
- [x] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Comment by hjoliver** [comment]
Motivation: "suite" appears all over `cylc play` stdout, in the new user guide overview section just after we promote the Cylc 8 terminology changes.

Now:
shot

(The odd-looking workflow name reflects a small bug...)

**Comment by MetRonnie** [comment]
Why not `cylc get-workflow-contact`?

**Comment by hjoliver** [comment]
> Why not `cylc get-workflow-contact`?

Because the "workflow" is an abstraction that exists even when the scheduler isn't running (and therefore isn't contactable).

**Comment by hjoliver** [comment]
I'll co-opt this branch for the full suite -> workflow conversion.

**Comment by hjoliver** [comment]
Actually, cleaner to do this with a new PR.

**Pull request closed without merging**
