### PR TITLE
fix no rose vars in cylc view

### PR DESCRIPTION
**Pull request by wxtim**
This PR closes an issue documented in the PR.

## Issue Description

Cylc view does not have access to the Cylc Rose command line options (`-O`, `-S`, `-D`), when it ought to have.

## PR Information

I have added the Cylc Rose CLI options to `cylc view`. It works manually, but ought to be tested in Cylc Rose.

Question - do we want to test the Cylc Rose option adder in this repo by looking at the `--help` output?

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Tests are **not** included because they should be in Cylc Rose; https://github.com/cylc/cylc-rose/pull/209
- [x] `CHANGES.md` entry not included - this is not a change that can affect users
- [x] Cylc doc update considered - not required.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by MetRonnie — APPROVED** [review]
LGTM

**Comment by wxtim** [comment]
> > Question - do we want to test the Cylc Rose option adder in this repo by looking at the --help output?
> 
> Can do that in the cylc-rose repo where there should be some e2e tests for this?

See the link against the "tests" checklist item.

**Review by oliver-sanders — APPROVED** [review]

**Comment by oliver-sanders** [comment]
>  If this is a bug fix, PR should be raised against the relevant ?.?.x branch.

Please finish checklist.

**Review by oliver-sanders — CHANGES_REQUESTED** [review]
wrong branch

>  If this is a bug fix, PR should be raised against the relevant ?.?.x branch.

Please finish checklist.

**Review by oliver-sanders — APPROVED** [review]

**Comment by wxtim** [comment]
All  failures caused by hitting codecov rate limits.

**Pull request merged**
