### PR TITLE
Fix task_action_timers table houskeeeping 7.8.x

### PR DESCRIPTION
**Pull request by hjoliver**
7.8.x companion of #3596 

These changes partially address #xxxx
These changes close #xxxx
This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Appropriate tests are included (unit and/or functional).

- [ ] Appropriate change log entry included.

- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Code changes OK. Just waiting on Travis.

**Comment by hjoliver** [comment]
(I'll add the change log entries post-merge to avoid triggering another build - forgot to do that on both PRs).

**Comment by hjoliver** [comment]
Tests all passed, pushing a skip-ci change log update now...

**Comment by hjoliver** [comment]
(Done).

**Comment by kinow** [comment]
I think it's safe to merge right @hjoliver ? The other PR got the two reviews, and this one is the same code change, only different being the changelog? WDYT?

**Pull request merged**
