### PR TITLE
Clean other remotes after error.

### LINKED ISSUE #4935: cylc clean: continue if remote clean fails?
If `cylc clean` can't clean a remote job platform used (or attempted) by the target workflow, it should continue on and clean other job platforms, ~~and locally~~, rather than abort immediately.

I'm reasonably sure this is a bug and not a feature(?)

E.g. install and run a workflow that uses a non-existent job platform, then try to clean it.

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #4935 

If `cylc clean` fails to clean a remote platform, continue on to other remote platforms but do not clean locally.

@oliver-sanders - you've suggested going further than this https://github.com/cylc/cylc-flow/issues/4935#issuecomment-1169950186 - but I think that's a potential follow-up. This quick-fix will be a significant improvement as-is - OK?

**Requirements check-list**
- [ ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [ ] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
> you've suggested going further than this https://github.com/cylc/cylc-flow/issues/4935#issuecomment-1169950186 - but I think that's a potential follow-up. This quick-fix will be a significant improvement as-is - OK?

I don't think #4935 is much of an issue (at least not much of an 8.0.0 issue) so happy with whatever.

**Comment by oliver-sanders** [comment]
LGTM; just needs a test.

**Comment by hjoliver** [comment]
> I don't think https://github.com/cylc/cylc-flow/issues/4935 is much of an issue (at least not much of an 8.0.0 issue) so happy with whatever.

I agree it's a small issue. #4949 is more important, and this sort of caused that (i.e., a remote clean failure in one workflow prevented cleaning of a bunch of others at the same time). However, it still a bug (cleaning a valid remote should not  depend on whether or not we try to clean an invalid one first) and easy to fix.

**Comment by hjoliver** [comment]
However, as this one is not very important and it's not clear to me how to effectively test it, I'll bump it back to 8.x

**Comment by oliver-sanders** [comment]
Been draft for a while!

In the mean time this functionality has been implemented as part of other work. Remote cleans are now performed in parallel with any errors reported at the end, so one failed remote clean no longer blocks others.

**Pull request closed without merging**
