### PR TITLE
Tree view - sort by definition order boolean now honored

### LINKED ISSUE #3698: cylc-gui - tasks momentarily out of sequence
Since upgrading from 7.8.0 to 7.8.6, I'm noticing a new visual oddity with our GUI when running a rather large suite.  For 2-10 seconds the tasks in a family will appear out of sequence:
image
Then the sequence restores itself:
image

It is not a major problem, but it is quite distracting and can lead to confusion when it changes.  It's almost as though an underlying object converts from a Dict to an OrderedDict, and because our suite is so stupidly large, we catch it in the act.

Thanks for your time and hard work!

Glenn

### PR DESCRIPTION
**Pull request by GlennCreighton**
These changes close #3698 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (made earlier).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Quickly wrote a suite with some random letters and numbers as tasks/families.

On `7.8.x`, there are indeed only 2 states. Sorted alphabetically/natural in ascending order, and in descending order. The default status gets one of these two.

On this PR, I get three different states.

GIFrecord_2020-09-03_195815


Thanks @GlennCreighton !

**Comment by GlennCreighton** [comment]
thanks for the confirmation...glad to help!

**Comment by GlennCreighton** [comment]
@oliver-sanders i see i was assigned to this, please let me know if you need anything further of me

**Comment by hjoliver** [comment]
> @oliver-sanders i see i was assigned to this, please let me know if you need anything further of me

@GlennCreighton - your assignment after the fact is a just for the record, reflecting the fact that you did in fact do the work :+1:

**Review by oliver-sanders — APPROVED** [review]

**Review by oliver-sanders — APPROVED** [review]
Cracked out the Cylc7 GUI (hello again old friend), seems to work as expected.

Completely forgot that `sort by definition order` defaulted to `True`.

**Pull request merged**
