### PR TITLE
schema: fix formatting in docstring

### PR DESCRIPTION
**Pull request by oliver-sanders**
The docstring matters here because it gets fed through to the UI via API-On-The-Fly.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]
:+1:

**Comment by MetRonnie** [comment]
This isn't working for me

**Comment by hjoliver** [comment]
Huh. I recall doing a manual test that implied this would work...

...yep:
```console
(venv) foo@bar $ python -c 'from cylc.flow.network.schema import Flow; print(Flow.__doc__); print(Flow().__doc__)'
An integer or one of all, new or none.
An integer or one of all, new or none.
```

**Comment by hjoliver** [comment]
Same result as you in the UI though.

**Pull request merged**
