### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by kinow**
A few imports not used. Hopefully Travis will pass with no issues, and no flaky tests failing :grimacing: 

I think one review will do?

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Already covered by existing tests.

- [x] No change log entry required (why? e.g. invisible to users).

- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
:+1: I will raise a PR to move this to flaky tests dir

**Comment by hjoliver** [comment]
> +1 I will raise a PR to move this to flaky tests dir

Hang on a bit, I'll take a closer look at the test - it's a new one that I only wrote a few days ago ...  disappointing if that's flaky!

**Comment by kinow** [comment]
Sure thing, and just to have a record on an issue, the failure was:

```
./tests/reload/22-remove-task-cycling.t

/travis/build/cylc/cylc-flow/bin/cylc-message', 'host': 'travis-job-f1fd9c65-54a9-4dff-9cfb-f808cc4cb59c'}}
2019-08-26T06:52:43Z DEBUG - zmq:recv {'data': [True, 'Messages queued: 1'], 'user': 'travis'}
==== /tmp/travis/cylctb-20190826T064454Z/reload/22-remove-task-cycling/suite-state.log-contains-ok.stderr ====
Missing lines:
bar, 2, waiting
Test File:
bar, 1, succeeded
foo, 1, succeeded
bar, 2, succeeded
foo, 2, succeeded
foo, 3, succeeded

```

**Comment by hjoliver** [comment]
I think I can see how the test can be flaky; I'll merge this and put up a fix soon.

**Pull request merged**
