### PR TITLE
`cylc clean`: rename `--force` to `--yes`

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes partially address #4673 and #4618 

The `--force` behaviour is more of a `--yes` than `--force`, so rename it.

`--force` can come back later if we want to allow users to override the current "cannot clean" scenarios - see #4450

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Appropriate tests included
- [x] Appropriate change log entry included.
- [x] Docs PR: https://github.com/cylc/cylc-doc/pull/403

### CODE REVIEW

**Comment by oliver-sanders** [comment]
> partially address https://github.com/cylc/cylc-flow/issues/4673 and https://github.com/cylc/cylc-flow/issues/4618

What's left?

**Comment by MetRonnie** [comment]
The second task on #4673

As for #4618, I've changed the multi workflow clean message
```diff
-Would remove the following workflows:
+Would clean the following workflows:
```
which is better because it doesn't explicitly say the whole run dir will be removed when you're only doing `--rm subdir`, but it still kinda implies it, so have left the issue open

**Comment by oliver-sanders** [comment]
So closes https://github.com/cylc/cylc-flow/issues/4618

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
I still think the prompt message is a bit alarming for targeted clean, perhaps the prompt could do with a slight rethink

**Comment by oliver-sanders** [comment]
I think it's ok, to explain better we would need something like a dry run listing exactly what we would expect to be removed where (perfectly possible).

**Comment by oliver-sanders** [comment]
Very small scope, can single review this.

**Pull request merged**
