### PR TITLE
Define a local "at" platform

### PR DESCRIPTION
**Pull request by hjoliver**
This is a small change with no associated Issue.

Some local tests were being skipped with `requires batch:at`

One review should do @oliver-sanders 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Ah, this was very much purposeful.

Atrun is an external batch submission system which is not pre-installed on all OS's and may require extra configuration to function. So, similar to slurm, pbs, etc developers are left to configure their own local test platforms (i.e. by adding those lines to their own `global.cylc` files).

**Comment by hjoliver** [comment]
Well `at` is required for "Linux Standard Base" system compliance: https://refspecs.linuxfoundation.org/LSB_1.0.0/gLSB/command.html ... which I believe includes Debian-based and Red Hat based distros, and it should run "out of the box" on those systems.  But perhaps not on all distros.

BTW `atrun` is apparently not a thing anymore.  This ancient [article](https://www.linuxjournal.com/article/4087) (year 2000) says:
> Linux has separate dæmons for at and cron. Old versions of Linux used a program called “atrun”, which was run in root's crontab once a minute to execute at requests

**Comment by oliver-sanders** [comment]
Sadly MacOS has atrun installed and disabled in such a cunning way that I can't figure out how to turn it on!

**Comment by hjoliver** [comment]
OK I'll close this sucker.

**Pull request closed without merging**
