### PR TITLE
More flaky tests

### PR DESCRIPTION
**Pull request by matthewrmshin**
These changes partially address #2894

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] These changes are already covered by existing tests.
- [x] No change log entry required (e.g. change is small or internal only).
- [x] No documentation update required for this change.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Looks like these are failing on Travis CI:
* `database/01` and `database/02`: The database entry contains the full host name running the Travis job instead of the string `localhost`.
* `restart/39` and `restart/40`: Reason unknown. An expected line is no longer in the log? I'll add some diagnostics in.

**Comment by kinow** [comment]
>Looks like these are failing on Travis CI

It doesn't make any sense that these tests (especially the one about the travis host name being used instead of localhost) didn't fail before. I saw the Travis failure some hours ago, but looks like you just pushed a change.

Will review once Travis is done building (and has hopefully passed this time :) )

**Comment by kinow** [comment]
Hmm, one failure. Not related?

```
2019-07-25T22:54:49Z INFO - Processing 1 queued command(s)
	+       set_stop_cleanly(kill_active_tasks=True)
2019-07-25T22:54:49Z INFO - Suite shutting down - REQUEST(CLEAN)
2019-07-25T22:54:50Z INFO - DONE
    stdout and stderr stored in: /tmp/travis/cylctb-20190725T223135Z/restart/40-auto-restart-force-stop
[22:54:23] ./flakytests/restart/40-auto-restart-force-stop.t ........ Failed 1/4 subtests 
	(less 3 skipped subtests: 0 okay)
```

**Comment by dwsutherland** [comment]
Definitely flaky... passed on my machine..

**Comment by matthewrmshin** [comment]
Finally pass with a workaround!

**Comment by matthewrmshin** [comment]
All of them are to do with host name. For some reason, our logic is now returning the literal string `localhost` instead of the fully qualified domain name.

**Pull request merged**
