### PR TITLE
setup.cfg: renamed cylc-flow + reduced summary

### PR DESCRIPTION
**Pull request by matthewrmshin**
Cylc is now Cylc-Flow.
Description can only be a one line summary.

### CODE REVIEW

**Comment by kinow** [comment]
Are we going to get `cylc-flow` in PYPI as well?

**Comment by matthewrmshin** [comment]
Yes. The rename in this change will do that automatically.

**Comment by kinow** [comment]
Cool. The author of beautifulsoup keeps two names too. I've always used bs4 for laziness. But I prefer to maintain a single name... just in case users ever complain that they'd like to pip install just cylc. Then one alternative could be yo copy bs4's approach (no idea if he just upliads it twice?)

**Comment by matthewrmshin** [comment]
I guess we should have `pip install cylc-flow` to install just this project, but `pip install cylc` will be replaced with a meta-project that installs the Pythonic web UI components as well?

**Comment by kinow** [comment]
Oh that's a good idea as well. I think that's possible. Haven't tried it before,  but it should work.

**Pull request merged**
