### PR TITLE
Store cycle point tz in DB for restart

### LINKED ISSUE #3462: Problems with DST change and cylc restart
If you start a suite in one timezone (a fixed offset from UTC) it will continue running using that timezone regardless of any timezone change due to daylight savings (we should make sure this is clear in the documentation). Therefore, if you stop a suite and restart it you should expect it to continue using the original timezone. However, this is not what happens at present (problem showed up with a suite which got migrated between servers).

I used this suite for testing (with 7.8.4):
```ini
[cylc]
    UTC mode = False # No problem is this is set to True
[scheduling]
    initial cycle point = now
    [[special tasks]]
        clock-trigger = daily(PT0M)
    [[dependencies]]
        [[[T23]]]
            graph = daily
[runtime]
    [[daily]]
        script = true
```

Example output illustrating the problem below.
Note the change in cyclepoint for future cycles after the restart.
Also note that, after the restart, I don't appear to be able to interact with the existing task without using wildcards (the same happens in the GUI).

```
$ export TZ=UTC
$ cylc run test.tz --host=localhost
<snip>
$ cylc dump test.tz
last_updated=1575634329.66
namespace definition order=['daily', 'root']
newest cycle point string=20191206T2300Z
newest runahead cycle point string=None
oldest cycle point string=20191206T2300Z
reloading=False
run_mode=live
state totals={'waiting': 1}
states=['waiting']
status_string=running
suite_urls={'suite': '', 'root': '', 'daily': ''}
time zone info={'hours': 0, 'string_basic': 'Z', 'string_extended': 'Z', 'minutes': 0}
daily, 20191206T2300Z, waiting, unspawned
$ cylc show test.tz 20191206T2300Z/daily
title: (not given)
description: (not given)
URL: (not given)

prerequisites (- => not satisfied):
  (None)

outputs (- => not completed):
  - daily.20191206T2300Z expired
  - daily.20191206T2300Z submitted
  - daily.20191206T2300Z submit-failed
  - daily.20191206T2300Z started
  - daily.20191206T2300Z succeeded
  - daily.20191206T2300Z failed

other:
  o  Clock trigger time reached ... False
  o  Triggers at ... 2019-12-06T23:00:00Z
$ cylc stop test.tz
$ export TZ=BST-1
$ cylc restart test.tz --host=localhost
<snip>
$ cylc dump test.tz
last_updated=1575634369.05
namespace definition order=['daily', 'root']
newest cycle point string=20191206T2300Z
newest runahead cycle point string=None
oldest cycle point string=20191206T2300Z
reloading=False
run_mode=live
state totals={'waiting': 1}
states=['waiting']
status_string=running
suite_urls={'suite': '', 'root': '', 'daily': ''}
time zone info={'hours': 1, 'string_basic': '+01', 'string_extended': '+01:00', 'minutes': 0}
daily, 20191206T2300Z, waiting, unspawned
$ cylc show test.tz 20191206T2300Z/daily  # Why doesn't this work?
No matching tasks found: 20191206T2300Z/daily
$ cylc show test.tz 20191206T2300*/daily
title: (not given)
description: (not given)
URL: (not given)

prerequisites (- => not satisfied):
  (None)

outputs (- => not completed):
  - daily.20191206T2300Z expired
  - daily.20191206T2300Z submitted
  - daily.20191206T2300Z submit-failed
  - daily.20191206T2300Z started
  - daily.20191206T2300Z succeeded
  - daily.20191206T2300Z failed

other:
  o  Clock trigger time reached ... False
  o  Triggers at ... 2019-12-07T00:00:00+01:00
$ cylc trigger test.tz 20191206T2300*/daily
$ cylc dump test.tz
last_updated=1575634467.15
namespace definition order=['daily', 'root']
newest cycle point string=20191207T2300+01
newest runahead cycle point string=None
oldest cycle point string=20191207T2300+01
reloading=False
run_mode=live
state totals={'waiting': 1}
states=['waiting']
status_string=running
suite_urls={'suite': '', 'root': '', 'daily': ''}
time zone info={'hours': 1, 'string_basic': '+01', 'string_extended': '+01:00', 'minutes': 0}
daily, 20191207T2300+01, waiting, unspawned
```

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #3462

Save the cycle point time zone to the suite database upon `cylc run` (setting it to the local time zone if it isn't set in `suite.rc`), and make sure the suite always reloads & restarts using the same cycle point time zone and UTC mode value.

Backport of #3614

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Appropriate tests are included (unit and functional).
- [x] Appropriate change log entry included.
- [x] (7.8.x branch) I have updated the documentation in this PR branch.

### CODE REVIEW

**Comment by MetRonnie** [comment]
#### Unit tests

All passing for me locally apart from `lib/cylc/tests/test_graphing.py` as I don't have graphviz installed in my python2 conda env.

#### Functional tests

In progress...

**Comment by MetRonnie** [comment]
Marking as draft, will need to investigate a few test failures

**Review by wxtim — APPROVED** [review]
- [x] Read.
- [x] Played with testing for `process_cycle_point_tz`
- [x] Played with testing for `process_utc_mode` 
- [x] Proof of pudding test running workflows

**Review by oliver-sanders — APPROVED** [review]
:+1:

Tested manually, looks good.

**Pull request merged**
