### PR TITLE
reload: fix submission errors for jobs awaiting preparation

### PR DESCRIPTION
**Pull request by oliver-sanders**
Closes https://github.com/cylc/cylc-flow/issues/4974    

When we reload a workflow we create new TaskProxy instances for all non-active tasks in the pool and replaces the previous instances with these new ones. The job submission pipeline maintains references to the pre-reload TaskProxy's which means if the workflow is reloaded whilst a tasks is going through job prep the pre-reload task gets submitted but the post-reload task is left in the pool. This results in submission issues as the submit number between the two instances are one off.

For busy workflows where the job submission pipeline is constantly churning away this bug is almost guaranteed to strike with any reload operation.

This PR attempts to resolve this issue by:
1. Ensuring job submission is fed the same TaskProxy instance as present in the task pool.
2. Incrementing the job submission number at preparation time (rather than after job submit).

Explanation:

1. scheduler: re-compute pre_prep_tasks for each iteration    
       
   * Addresses https://github.com/cylc/cylc-flow/issues/4974    
   * Tasks which are awaiting job preparation used to be stored in    
     `Scheduler.pre_prep_tasks`, however, this effectively created an    
     intermediate "task pool" which had nasty interactions with reload.    
   * This commit removes the pre_prep_tasks list by merging the listing    
     of these tasks in with TaskPool.release_queued_tasks (to avoid    
     unnecessary task pool iteration).    
   * `waiting_on_job_prep` now defaults to `False` rather than `True`.    
       
2. job: increment the submission number at preparation time                           
          
   * Addresses https://github.com/cylc/cylc-flow/issues/4974      
   * Job submission number used to be incremented *after* submission      
     (i.e. only once there is a "submission" of which to speak).      
   * However, we also incremented the submission number if submission      
     (or preparation) failed (in which cases there isn't really a      
     "submission" but we need one for internal purposes).      
   * Now the submission number is incremented when tasks enter the      
     "preparing" state.      
   * This resolves an issue where jobs which were going through the      
     submission pipeline during a reload got badly broken in the scheduler      
     (until restarted).   
   * It also makes the scheduler logs nicer as the submission number for
     preparing tasks now matches that of the subsequent submitted or
     submit-failed outcome.

Testing this one is a nightmare, I can't really see a way to do it meaningfully. Look at the issue for example tests which demonstrates how tasks could get 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [ ] Already covered by existing tests, cannot really test this
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
This leaves one remaining question of reload safety:

https://github.com/cylc/cylc-flow/blob/d4938dd40320b423241b1bd3feaa693da8d043ac/cylc/flow/task_pool.py#L858-L861

Should preparing tasks be included here? I think there is the potential for preparation to begin with pre-reload settings but possibly to receive post-reload settings later on?

**Comment by hjoliver** [comment]
> It also makes the scheduler logs nicer as the submission number for
preparing tasks now matches that of the subsequent submitted or
submit-failed outcome.

:+1: must admit this annoyed me!

**Comment by hjoliver** [comment]
Your explanation sounds reasonable, but the functional tests aren't happy.

> This leaves one remaining question of reload safety:...

While thinking about how to test this, I discovered this bug: #4987

**Comment by hjoliver** [comment]
(Agreed good to have this fix in 8.0 if we can nail it in time).

**Comment by oliver-sanders** [comment]
> the functional tests aren't happy.

Couple of small breaks, will investigate, expect I can shift them quickly.

> (Agreed good to have this fix in 8.0 if we can nail it in time).

Unfortunately I think this is 8.0 essential as at the moment `cylc reload` is almost guaranteed to break workflows every time.

**Comment by oliver-sanders** [comment]
I had got my if/elif branches the wrong way around, [fixed](https://github.com/cylc/cylc-flow/compare/9adab1f761d9c568dfe2179e3de1c1fadb60759f..56f9bf1fd954f241637ba456e684b5e03b07418d), think that should hold it.

**Comment by hjoliver** [comment]
> This leaves one remaining question of reload safety:
> 
> https://github.com/cylc/cylc-flow/blob/d4938dd40320b423241b1bd3feaa693da8d043ac/cylc/flow/task_pool.py#L858-L861
> 
> Should preparing tasks be included here? I think there is the potential for preparation to begin with pre-reload settings but possibly to receive post-reload settings later on?
 
I think we include `preparing` here because pre-reload settings are fixed once written to the job file. Presumably it's possible to reload a preparing task before it writes the job file, though.  Maybe we should have a separate warning for `preparing` tasks: *may be active with pre-reload settings*.

**Review by hjoliver — APPROVED** [review]
Makes sense to me, and the tests are happy now.

**Comment by hjoliver** [comment]
(The failed functional test is just codecov upload)

**Review by dwsutherland — APPROVED** [review]
Works, tests passed, code makes sense.. 
From what I can see, the order of events in the main loop is:
- **Do reload if flagged** (reloads task pool at this point (along with DB and store etc))
- **Process the command queue:**
 -- reload command sets up new config, then reconfigures broadcasts, pool (just config), tasks events, and DB... Which flags reload.
- Releases/computes runahead (**uses new pre-reload pool with post reload config**)
- Proc Pool Processed
- Checks triggers (xtrigger etc), and sets expired tasks
- **Releases queued tasks** (`self.release_queued_tasks()` changed with this PR) (still pre-reload pool)
- . . .
- Processes queued task messages 
- **Processes the command queue (Again)**
- Processes task events
- DB, data-store, health checks ...etc

END LOOP  

Probably a bigger issue to look into the ideal order of events, however there's (intentionally or otherwise) a number of things that happen between processing a reload command (reconfiguring) and reloading the task pool.. 

Would it be better to do the reload straight after processing the reload command (setting up the new config)? 
Because at present tasks are potentially released/prepped between setting up a new config and reloading the task pool. Perhaps the first two steps can be switched? (or does it not matter?)

**Comment by oliver-sanders** [comment]
> Probably a bigger issue to look into the ideal order of events

Definitely, this code is fragile as the order will be critical to particular niche behaviours so would need some time to unravel :(

**Review by wxtim — APPROVED** [review]
Looks legit and much nicer than my original solution 👍🏼

**Pull request merged**
