### PR TITLE
Extra log file replication fix

### LINKED ISSUE #4298: Extra log files in log viewer dropdown when running multiple jobs (GUI)
**Describe the bug**
Extra log files show up in log viewer dropdown when running multiple jobs.

**Release version(s) and/or repository branch(es) affected?**
7.9.3

**Steps to reproduce the bug**
Add a file name to "extra log files".  Run the job more than once, check log viewer dropdown shows duplicates.

**Expected behavior**
Dropdown should only show each log in the "extra log files" list once.

**Screenshots**

image

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

I've got a fix for this if you would like it.  Problem is on line 829 of task_job_mgr.py, solution is to add a quick check that the file is not in the list before appending, e.g. 
image

### PR DESCRIPTION
**Pull request by GlennCreighton**
These changes close #4298

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Does not need tests (trivial change).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Hello, thank you for this fix, looks good.

Your commit isn't showing up as associated with your GitHub account, you might need to [configure your name and email with git](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git).

You can reset the author on your commit something like this:

```console
# fix .gitconfig
$ git checkout <branch>
$ git commit --amend --reset-author  # fix commit author
$ git push origin HEAD -f  # override the commit on this branch
```

**Comment by GlennCreighton** [comment]
Hi @oliver-sanders, I followed your instructions to fix my user/email.  It looks like it showed up here - let me know if I need to do anything further.  Thanks!

**Review by oliver-sanders — APPROVED** [review]
Hi @GlennCreighton, thanks for this contribution.

I've replicated your bug and confirmed this fixes it.

**Review by wxtim — APPROVED** [review]
Thank you @GlennCreighton !

**Pull request merged**
