### PR TITLE
Replace unicode character in `cylc show` output

### PR DESCRIPTION
**Pull request by MetRonnie**
For some reason, the `U+2999` "Dotted Fence" character is not displaying on my RHEL9 terminal despite working before in RHEL7.

image

My font is JetBrains Mono, but changing back to the default font doesn't help.

Replaced with `U+2506` "Box Drawings Light Triple Dash Vertical" as it seems to be more widespread.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No dependency changes 
- [x] Tests updated
- [x] No changelog entry as minor
- [x] No docs needed
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]
Possibly an improvement anyway, in terms of how it looks.

**Review by oliver-sanders — APPROVED** [review]
Looked it up.

The previous icon was Unicode v3 (added in the 2000s), this PR changes it to an icon in Unicode v1 (added in the 90s).

So, I guess, try to keep to older Unicode icons (have just checked the Tui icons, they are all v1).

**Comment by oliver-sanders** [comment]
@MetRonnie, to fix the test failure:

```
# update the screenshot
CYLC_UPDATE_SCREENSHOTS=true pytest tests/integration/tui/test_show.py::test_show

# test the result is stable
pytest tests/integration/tui/test_show.py::test_show

git add -u; ...
```

**Comment by hjoliver** [comment]
(Unrelated flaky macos test fail)

**Pull request merged**
