### PR TITLE
remove unnecessary execute permissions

### PR DESCRIPTION
**Pull request by oliver-sanders**
Quickie, we have a few erroneously executable files in the repo.

Found a couple of old tests in parsec which aren't being run, kept one because I felt sorry for it, binned the other (much better unit tests already running).

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Ha, just gone through yesterdays issues and found that @kinow had put this up for Hacktober fest.

Sorry!

Closes #3382

**Comment by kinow** [comment]
No worries @oliver-sanders! There are still other issues for the hacktoberfest :)

Looks good to me. Just kicked Travis.

**Comment by kinow** [comment]
One job passed, now kicked the sensitive tests one (twice).

**Comment by hjoliver** [comment]
Kicked the flakies again.

**Comment by hjoliver** [comment]
(Approved!)

**Comment by oliver-sanders** [comment]
> No worries @oliver-sanders! There are still other issues for the hacktoberfest :)

The real joke is I did this whilst poking round Cylc looking for hacktoberfest issues!

**Comment by kinow** [comment]
> > No worries @oliver-sanders! There are still other issues for the hacktoberfest :)
> 
> The real joke is I did this whilst poking round Cylc looking for hacktoberfest issues!

You better wait for October 1st then. So that your PR's will count for claiming the swag :rocket:

**Pull request merged**
