### PR TITLE
Update .mailmap

### PR DESCRIPTION
**Pull request by hjoliver**
Fix `.mailmap` syntax

This is a small change with no associated Issue.

Before:
```console
$ git shortlog -sen
  6124  Hilary Oliver <h.oliver@niwa.co.nz>
  2966  Hilary Oliver <hilary.j.oliver@gmail.com>
  1534  Matt Shin <matthew.shin@metoffice.gov.uk>
  1487  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
   877  Ben Fitzpatrick <ben.fitzpatrick@metoffice.gov.uk>
   683  Andrew Clark <andrew.clark@metoffice.gov.uk>
   621  Ronnie Dutta <61982285+MetRonnie@users.noreply.github.com>
   587  Tim Pillinger <26465611+wxtim@users.noreply.github.com>
   269  Bruno Kinoshita <kinow@users.noreply.github.com>
   240  Mel Hall <37735232+datamel@users.noreply.github.com>
   181  Sadie Bartholomew <sadie.bartholomew@metoffice.gov.uk>
   157  Bruno Kinoshita <bruno.kinoshita@niwa.co.nz>
   107  David Sutherland <david.sutherland@niwa.co.nz>
   102  Declan Valters <declan.valters@ed.ac.uk>
    87  Martin Ryan <martin.ryan@bom.gov.au>
    56  Luis Kornblueh <luis.kornblueh@zmaw.de>
    52  Kerry Day <kerry.day@metoffice.gov.uk>
    52  Tomek Trzeciak <tomasz.trzeciak@metoffice.gov.uk>
    46  Tim Whitcomb <tim.whitcomb@nrlmry.navy.mil>
    43  Prasanna Challuri <Prasanna.Challuri@niwa.co.nz>
    33  Samuel Gaist <samuel.gaist@idiap.ch>
    29  David Matthews <david.matthews@metoffice.gov.uk>
    16  Tim Pillinger <tim.pillinger@metoffice.gov.uk>
    14  Scott Wales <scott.wales@unimelb.edu.au>
    13  Thomas Coleman <thomas.coleman@bom.gov.au>
    10  Gilliano Menezes <gillianomenezes@gmail.com>
     9  github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
     8  John Haiducek <jhaiduce@gmail.com>
     6  Jonny Williams <jonny.williams@niwa.co.nz>
     6  Lois Huggett <lois.huggett@metoffice.gov.uk>
     5  Bruno Kinoshita <brunodepaulak@yahoo.com.br>
     4  Hilary Oliver <hilary.oliver@niwa.co.nz>
     3  Alexander Paulsell <alexander.paulsell@nrlmry.navy.mil>
     3  Annette Osprey <a.osprey@reading.ac.uk>
     3  Hilary Oliver <hilary@Megan-Olivers-MacBook-Pro.local>
     3  Jonathan Thomas <jonathan.thomas@bom.gov.au>
     3  Rosalyn Hatcher <r.s.hatcher@reading.ac.uk>
     2  Alex Reinecke <alex.reinecke@nrlmry.navy.mil>
     2  Dima Veselov <d.veselov@itransition.com>
     2  Domingo Manubens Gil <domingo.manubens@ic3.cat>
     2  Hilary Oliver <hilary@localhost.localdomain>
     2  Ivor Blockley <ivor.blockley@bom.gov.au>
     2  Milton Woods <m.woods@bom.gov.au>
     1  Andrew Huang <huang.andrew12@gmail.com>
     1  Chandin Wilson <chandin.wilson@noaa.gov>
     1  Hilary Oliver <holiver@eld084.desktop.frd.metoffice.com>
     1  Kevin Pulo <kev@pulo.com.au>
     1  Martin Dix <martin.dix@csiro.au>
```
After:
```console
$ git shortlog -sen
  9101  Hilary Oliver <hilary.j.oliver@gmail.com>
  1534  Matt Shin <matthew.shin@metoffice.gov.uk>
  1487  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
   877  Ben Fitzpatrick <ben.fitzpatrick@metoffice.gov.uk>
   683  Andrew Clark <andrew.clark@metoffice.gov.uk>
   621  Ronnie Dutta <ronnie.dutta@metoffice.gov.uk>
   603  Tim Pillinger <tim.pillinger@metoffice.gov.uk>
   431  Bruno Kinoshita <kinow@apache.org>
   240  Mel Hall <mel.hall@metoffice.gov.uk>
   181  Sadie Bartholomew <sadie.bartholomew@metoffice.gov.uk>
   107  David Sutherland <david.sutherland@niwa.co.nz>
   102  Declan Valters <declan.valters@ed.ac.uk>
    87  Martin Ryan <martin.ryan@bom.gov.au>
    56  Luis Kornblueh <luis.kornblueh@zmaw.de>
    52  Kerry Day <kerry.day@metoffice.gov.uk>
    52  Tomek Trzeciak <tomasz.trzeciak@metoffice.gov.uk>
    46  Tim Whitcomb <tim.whitcomb@nrlmry.navy.mil>
    43  Prasanna Challuri <Prasanna.Challuri@niwa.co.nz>
    33  Samuel Gaist <samuel.gaist@idiap.ch>
    29  David Matthews <david.matthews@metoffice.gov.uk>
    14  Scott Wales <scott.wales@unimelb.edu.au>
    13  Thomas Coleman <thomas.coleman@bom.gov.au>
    10  Gilliano Menezes <gillianomenezes@gmail.com>
     9  github-actions[bot] <github-actions@noreply.github.com>
     8  John Haiducek <jhaiduce@gmail.com>
     6  Jonny Williams <jonny.williams@niwa.co.nz>
     6  Lois Huggett <lois.huggett@metoffice.gov.uk>
     3  Alexander Paulsell <alexander.paulsell@nrlmry.navy.mil>
     3  Annette Osprey <a.osprey@reading.ac.uk>
     3  Jonathan Thomas <jonathan.thomas@bom.gov.au>
     3  Rosalyn Hatcher <r.s.hatcher@reading.ac.uk>
     2  Alex Reinecke <alex.reinecke@nrlmry.navy.mil>
     2  Dima Veselov <d.veselov@itransition.com>
     2  Domingo Manubens Gil <domingo.manubens@ic3.cat>
     2  Ivor Blockley <ivor.blockley@bom.gov.au>
     2  Milton Woods <m.woods@bom.gov.au>
     1  Andrew Huang <huang.andrew12@gmail.com>
     1  Chandin Wilson <chandin.wilson@noaa.gov>
     1  Kevin Pulo <kev@pulo.com.au>
     1  Martin Dix <martin.dix@csiro.au>
```

### CODE REVIEW

**Comment by hjoliver** [comment]
One review will do.

**Comment by MetRonnie** [comment]
If you add `'.mailmap'` here it will run the test (we should have been doing this originally)
https://github.com/cylc/cylc-flow/blob/914faef429da725dee6eca6db69e5263e1b8cabe/.github/workflows/shortlog.yml#L3-L8

**Comment by hjoliver** [comment]
:+1:  done.

**Review by MetRonnie — APPROVED** [review]

**Review by oliver-sanders — APPROVED** [review]

**Comment by oliver-sanders** [comment]
check contributor list passed, merging.

**Pull request merged**
