### PR TITLE
Fix spawning bug.

### LINKED ISSUE #4729: task pool: is_task_prereqs_not_done attribute error bug
Traceback from a restarted workflow with no evidence of user interaction (in the restart):

```
2022-03-02T15:15:28Z ERROR - 'NoneType' object has no attribute 'is_task_prereqs_not_done'
    Traceback (most recent call last):                                              
      File "/path/to/cylc/flow/scheduler.py", line 618, in run_scheduler    
        await self.main_loop()    
      File "/path/to/cylc/flow/scheduler.py", line 1547, in main_loop    
        self.release_queued_tasks()    
      File "/path/to/cylc/flow/scheduler.py", line 1269, in release_queued_tasks    
        self.pre_prep_tasks += self.pool.release_queued_tasks(    
      File "/path/to/cylc/flow/task_pool.py", line 765, in release_queued_tasks    
        self.spawn_on_all_outputs(itask)    
      File "/path/to/cylc/flow/task_pool.py", line 1296, in spawn_on_all_outputs    
        self.add_to_pool(c_task)    
      File "/path/to/cylc/flow/task_pool.py", line 173, in add_to_pool    
        if itask.is_task_prereqs_not_done() and not itask.is_manual_submit:    
    AttributeError: 'NoneType' object has no attribute 'is_task_prereqs_not_done' 
```

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #4729

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [x] No documentation update required.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Looks sensible.

**Comment by hjoliver** [comment]
This is a trivial enough change that it probably doesn't need a test (wishful thinking?).  Otherwise I'll have to figure out how to get a no-spawn result at that point in the code.

**Review by oliver-sanders — APPROVED** [review]
Would be good to have a test here, at least to prevent regression, however, I can't figure out how to get Cylc to hit this line.

**Comment by hjoliver** [comment]
(Same)

**Review by MetRonnie — APPROVED** [review]
> Would be good to have a test here, at least to prevent regression...

One option could be add these type annotations:
```diff
diff --git a/cylc/flow/task_pool.py b/cylc/flow/task_pool.py
index a2441dc8e..dd0c78a28 100644
--- a/cylc/flow/task_pool.py
+++ b/cylc/flow/task_pool.py
@@ -717,17 +717,19 @@ class TaskPool:
 
         return point_itasks
 
-    def _get_hidden_task_by_id(self, id_):
+    def _get_hidden_task_by_id(self, id_: str) -> Optional[TaskProxy]:
         """Return runahead pool task by ID if it exists, or None."""
         for itask_ids in list(self.hidden_pool.values()):
             with suppress(KeyError):
                 return itask_ids[id_]
+        return None
 
-    def _get_main_task_by_id(self, id_):
+    def _get_main_task_by_id(self, id_: str) -> Optional[TaskProxy]:
         """Return main pool task by ID if it exists, or None."""
         for itask_ids in list(self.main_pool.values()):
             with suppress(KeyError):
                 return itask_ids[id_]
+        return None
 
     def queue_task(self, itask: TaskProxy) -> None:
         """Queue a task that is ready to run."""
@@ -1253,7 +1255,9 @@ class TaskPool:
             if itask.identity == self.stop_task_id:
                 self.stop_task_finished = True
 
-    def spawn_on_all_outputs(self, itask, completed_only=False):
+    def spawn_on_all_outputs(
+        self, itask: TaskProxy, completed_only: bool = False
+    ) -> None:
         """Spawn on all (or all completed) task outputs.
 
         If completed_only is False:
```

**Comment by oliver-sanders** [comment]
Ok, none of us can replicate the circumstances or come up with a test, the fix looks reasonable, lets do it.

**Pull request merged**
