### PR TITLE
7.8.x: slurm: sbatch output/error: handle % character

### PR DESCRIPTION
**Pull request by matthewrmshin**
Back port of #3531. The `%` character in `--output=...` and `--error=...` needs escape.

This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Appropriate tests are included (unit and/or functional).

- [x] Appropriate change log entry included.

- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
Just occurred to me we will need yet another PR, against `7.9.x`.

**Comment by matthewrmshin** [comment]
Raised #3538 for the 7.9.x port.

**Comment by kinow** [comment]
Sorry, I think another recent change introduced a conflict to this PR.

**Comment by matthewrmshin** [comment]
Updated.

**Comment by kinow** [comment]
Two approvals and Travis happy. LGTM

**Pull request merged**
