### PR TITLE
Forwards compatible fs search

### LINKED ISSUE #3518: Forwards compatiblity cylc scan issue.
When executing cylc scan in cylc 7 with workflows running in cylc 8, an error occurs, as discussed in issue https://github.com/cylc/cylc-flow/issues/3516.

Make cylc scan skip workflows running in newer versions of cylc: list these suites in --debug mode.

### PR DESCRIPTION
**Pull request by datamel**
These changes partially address #3516
These changes close #3518
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] Does not need tests (why? manually tested for now. No current unit tests for port_scan.py - possibly worth adding some?).

### CODE REVIEW

**Comment by datamel** [comment]
> (again, Travis failing, but I don't this this PR would cause those (?))
Thanks @dwsutherland, these tests pass locally for me and they pass travis on my fork on github. There are a few tests consistently failing travis on cylc/cylc-flow that happen to call cylc scan in them,  
slightly worried I have done something wrong somewhere along the line - I'll get to the bottom of it eventually!

**Comment by hjoliver** [comment]
@datamel - in your last commit (which may be just an experiment of some kind?) `from cylc_version import CYLC_VERSION` - that will import that version of cylc running the scan, not the version of the target suite.

**Comment by datamel** [comment]
> @datamel - in your last commit (which may be just an experiment of some kind?) from cylc_version import CYLC_VERSION - that will import that version of cylc running the scan, not the version of the target suite.

Yes, I realised that after push! Doh - should not experiment while tired!!

**Comment by datamel** [comment]
So, the problem is related to the change, in that I can get it passing travis by hard coding a cylc version but getting it from the contact file results in travis fail. 
Do you think that it is some kind of inverse race condition where travis isn't getting the contact file in time? Although I have tried adding sleeps in some failing tests and that hasn't made a difference. Bit of a pain debugging when it is passing locally and passing travis on my fork! Sorry PR looks a total mess, happy to delete and resubmit or just rebase when I get it working!

**Comment by hjoliver** [comment]
Hmmm, that is interesting!  Need to think about it...

**Comment by hjoliver** [comment]
@datamel - if you look on Riot ("general" room) I posted how to run only the failing tests on Travis.  Can you try that, and push to this branch?  (In case the problem only occurs under load).

**Comment by hjoliver** [comment]
That's really strange, as 7.8.x still loads the contact file.  The only difference is your branch accesses the loaded data earlier.

**Comment by datamel** [comment]
> That's really strange, as 7.8.x still loads the contact file.  The only difference is your branch accesses the loaded data earlier.

Yep, couldn't see why that would have been making a difference, which is why I tried adding a sleep to give it time! 
Great fix - useful one to have up my sleeve. Thanks for all your help @hjoliver and @kinow, problem solved :)

**Comment by hjoliver** [comment]
Two approvals; test now passing.

**Pull request merged**
