### PR TITLE
no preparing data-store jobs, decrement submit-num on restart

### LINKED ISSUE #4994: data store: preparing jobs appearing on restart
Reported by @MetRonnie on Element.

"Preparing" is a task state not a job state, we should see preparing tasks but never preparing jobs (jobs represent submissions, they have IDs and can be queried).

It looks like this only happens on restart but that will need to be confirmed properly. The data store loads in jobs from the DB and ~is probably being tricked by the submit number being higher than expected as a result of https://github.com/cylc/cylc-flow/pull/4984~ - https://github.com/cylc/cylc-flow/issues/4994#issuecomment-1191355838

The code needs to be patched to prevent these preparing jobs from being spawned somewhere around here:

https://github.com/cylc/cylc-flow/blob/e085c222a3712a95d5c0504ba208d7f554858c43/cylc/flow/data_store_mgr.py#L883-L886

XUinUpHfovaqAsrvxfKhTvtM
HsFtrEzqcAmKPYuQaVLLelah

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by dwsutherland**
These changes close #4994

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
I have written an integration test at https://github.com/dwsutherland/cylc-flow/pull/7

Turned out to be tricky. I couldn't figure out how to successfully test that the job gets put in the data store on the second try

**Review by hjoliver — APPROVED** [review]
LGTM, tested as working :tada:   Thanks @dwsutherland for going above and beyond the call of duty to get this done after midnight :bouquet:

**Comment by dwsutherland** [comment]
> I have written an integration test at [dwsutherland#7](https://github.com/dwsutherland/cylc-flow/pull/7)
> 
> Turned out to be tricky. I couldn't figure out how to successfully test that the job gets put in the data store on the second try

@MetRonnie - Merged in.

Looks like there's nothing in the store yet. I put this:
```
        print(schd.data_store_mgr.data[schd.data_store_mgr.workflow_id]['jobs'])
        print(schd.data_store_mgr.added['jobs'])
        print(schd.data_store_mgr.updated['jobs'])
```
above the test you're trying to run:
```
        assert await gql_query(client, '''
            jobs {
                cyclePoint, name, submitNum
            }
        ''') == {
            'jobs': [{
                'cyclePoint': '1',
                'name': 'one',
                'submitNum': 1
            }]
        }
```
and they were all empty:
```
E           AssertionError: assert {'jobs': []} == {'jobs': [{'c...bmitNum': 1}]}
E             Differing items:
E             {'jobs': []} != {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 1}]}
E             Full diff:
E             - {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 1}]}
E             + {'jobs': []}

tests/integration/test_data_store_mgr.py:372: AssertionError
------------------------------- Captured stdout call -------------------------------
{}
{}
{}

```
but from the log .. the job was submitted .. so perhaps the test happened before it was run or after the job finished (and was deleted).

**Comment by dwsutherland** [comment]
@MetRonnie - Test working now! 🎉 

Just added a 2nd yield to allow the scheduler to do some more processing, and it worked:
```
-------------------------------- Captured stdout call --------------------------------
{'~sutherlander/cit-20220726T150453+0935/integration.test_data_store_mgr/test_ghost_job/fa0642be-0ca3-11ed-8690-cdc6e1fdd4bc//1/one/01': stamp: "~sutherlander/cit-20220726T150453+0935/integration.test_data_store_mgr/test_ghost_job/fa0642be-0ca3-11ed-8690-cdc6e1fdd4bc//1/one/01@1658813395.5770588"
id: "~sutherlander/cit-20220726T150453+0935/integration.test_data_store_mgr/test_ghost_job/fa0642be-0ca3-11ed-8690-cdc6e1fdd4bc//1/one/01"
submit_num: 1
state: "submitted"
task_proxy: "~sutherlander/cit-20220726T150453+0935/integration.test_data_store_mgr/test_ghost_job/fa0642be-0ca3-11ed-8690-cdc6e1fdd4bc//1/one"
submitted_time: "2022-07-26T15:04:55+09:35"
job_id: "130831"
job_runner_name: "background"
platform: "localhost"
job_log_dir: "/home/sutherlander/cylc-run/cit-20220726T150453+0935/integration.test_data_store_mgr/test_ghost_job/fa0642be-0ca3-11ed-8690-cdc6e1fdd4bc/log/job/1/one/01"
environment: "{}"
directives: "{}"
param_var: "{}"
name: "one"
cycle_point: "1"
}
{}
{}
```

Thanks

**Comment by dwsutherland** [comment]
hmm.. new test seems flaky

**Comment by dwsutherland** [comment]
> hmm.. new test seems flaky

Ok looks like that's done it

**Comment by dwsutherland** [comment]
Also, just to confirm, with the decrement commented out:
```
            elif status == TASK_STATUS_PREPARING:
                # put back to be readied again.
                status = TASK_STATUS_WAITING
                # Re-prepare same submit.
                #itask.submit_num -= 1
```
the test fails
```
E           AssertionError: assert {'jobs': [{'c...bmitNum': 2}]} == {'jobs': [{'c...bmitNum': 1}]}
E             Differing items:
E             {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 2}]} != {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 1}]}
E             Full diff:
E             - {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 1}]}
E             ?                                                           ^
E             + {'jobs': [{'cyclePoint': '1', 'name': 'one', 'submitNum': 2}]}
E             ?
```
So we're good 👍

**Comment by MetRonnie** [comment]
I was hoping to avoid being reliant on sleep durations for waiting for it to appear in the data store, may need to revisit this post-8.0.0 otherwise the test could end up being flaky

**Comment by dwsutherland** [comment]
> 

Well, the problem is the workflow needs time to run to a point where there's a job... And that's exactly what your ascyncio sleep was doing (along with yielding control), because if you yield for too long then the workflow will complete before you run the tests.. So I had to extend the run time of the workflow with sleep.

**Comment by MetRonnie** [comment]
Ok after wrestling with bash syntax I have managed to convert it into a non-flaky functional test: https://github.com/dwsutherland/cylc-flow/pull/9

Sorry for the revert

**Review by MetRonnie — APPROVED** [review]
(I am happy with the codebase changes)

**Review by oliver-sanders — APPROVED** [review]

**Comment by hjoliver** [comment]
:tada: nice work all

**Pull request merged**
