### PR TITLE
absolute trigger data-store prune fix

### LINKED ISSUE #3553: job pool pruning problem with absolute trigger
Finished `foo`'s never get pruned here:
```
[scheduling]
   cycling mode = integer
   initial cycle point = 1
   final cycle point = 10
   [[graph]]
         R1 = start
         P1 = "start[^] => foo"
[runtime]
   [[root]]
       script = sleep 2
```
shot1

Strangely, adding another task downstream of `foo` fixes the problem (`start[^] => foo => bar`):
shot2

### PR DESCRIPTION
**Pull request by dwsutherland**
These changes close #3553 

image

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (pre-release fix).
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
Thanks @dwsutherland, that was quick and easy! (evidently).   I'll try to understand the context a bit more before approving.

**Comment by dwsutherland** [comment]
> Thanks @dwsutherland, that was quick and easy! (evidently). I'll try to understand the context a bit more before approving.

Just two lines of code changed .. I was using the wrong set operations, `union` returns a new set while `update` modifies existing.

**Comment by hjoliver** [comment]
Two approvals :tada:

**Comment by oliver-sanders** [comment]
Wow that was a simple fix!

**Comment by dwsutherland** [comment]
> Wow that was a simple fix!

Embarrassingly so 😅

**Pull request merged**
