### PR TITLE
GH Actions: add mail

### LINKED ISSUE #3599: actions: mail tests
Setup `mail` on GitHub Actions to allow dependent tests to run.

Follow-on from: #3548 

See previous aborted attempt: https://github.com/cylc/cylc-flow/pull/3548/commits/a0e07ab871ef014a11ca7191be2b0630a42c28ca

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #3599 

**Requirements check-list**
- [X] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [X] Contains logically grouped changes (else tidy your branch by rebase).
- [X] Does not contain off-topic changes (use other PRs for other changes).

- [X] Does not need tests

- [X] No change log entry required (invisible to users).

- [X] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
I don't get what's going on with the mail tests
```
==== /tmp/runner/cylctb-20200626T152246Z/events/29-task-event-mail-1/smtpd.log-contains-ok.stderr ====
Missing lines:
b'retry: 1/t1/01'
b'see: http://localhost/stuff/runner/cylctb-20200626T152246Z/events/29-task-event-mail-1/'
Test File:
DebuggingServer started at Fri Jun 26 15:25:05 2020
	Local addr: ('localhost', 8025)
	Remote addr:('localhost', 25)
```

**Comment by oliver-sanders** [comment]
This is what I got with the initial GH Actions PR.

The only thing in the mail log is this:

```
DebuggingServer started at Fri Jun 26 15:25:05 2020
	Local addr: ('localhost', 8025)
	Remote addr:('localhost', 25)
```

Which infers that messages aren't getting through.

**Comment by MetRonnie** [comment]
Is it something to do with the mocking of an SMTP server daemon?
https://github.com/cylc/cylc-flow/blob/154b4996197be1f3090d017ce1c288f52d3fea98/tests/lib/bash/test_header#L621-L649

**Comment by MetRonnie** [comment]
Aha, so I removed the use of `mock_smtpd_init` in `tests/events/29-task-event-mail-1.t` and the emails are going through to the runner's mailbox (arrow inserted by me):
```
==== /tmp/runner/cylctb-20200701T160104Z/events/29-task-event-mail-1/foo.txt-contains-ok.stderr ====
Missing lines:
b'retry: 1/t1/01'
b'see: http://localhost/stuff/runner/cylctb-20200701T160104Z/events/29-task-event-mail-1/'
Test File:
"/var/mail/runner": 2 messages 2 new
>N   1 runner@fv-az88.5hv Wed Jul  1 16:00  13/634   Setup mail
 N   2 notifications@fv-a Wed Jul  1 16:02  19/982   [1/t1/01 retry] cylctb-20    <-- Here!

Held 2 messages in /var/mail/runner
```
(the test still fails because it's still grepping for the email body in the output of the `mail` command which just shows the inbox)

**Comment by MetRonnie** [comment]
Findings after doing some more debugging:

- The `[runtime][<task>][events]mail smtp` setting in a <del>suite.rc</del> flow.cylc file is used by Cylc to set the environment variable `smtp` (to `localhost:8025` in this case).
- To mock the SMTP server, we do `python3 -u -m smtpd -c DebuggingServer -d -n localhost:8025`, which sets up an SMTP server listening for mail received on port 8025
- According to https://linux.die.net/man/1/mail

  > Normally, `mailx` invokes sendmail(8) directly to transfer messages. If the `smtp` variable is set, a SMTP connection to the server specified by the value of this variable is used instead. If the SMTP server does not use the standard port, a value of `server:port` can be given, with `port` as a name or as a number.

  This works fine on the Met Office RHEL7 machiens (e.g. `export smtp='localhost:8025'; mail -s "Foo" <username> <<< "Hello world"`). That email ends up in the SMTP DebuggingServer's stdout.

  However, on the GitHub Actions Ubuntu runner, using mailutils (acquired by `sudo apt-get install -y mailutils`), the same `mail ...` command as above just sends the email to the runner's inbox, bypassing the SMTP DebuggingServer for some reason

This was tested out on this workflow run: https://github.com/MetRonnie/spork/runs/999279066?check_suite_focus=true

**Comment by MetRonnie** [comment]
Also tried using [`smtp-sink` ](http://www.postfix.org/smtp-sink.1.html) instead of the Python `smtpd` but it's exactly the same problem - the mail just bypasses that and goes into the mailbox (on GH Actions; again it works fine on my Met Officel machine).

So the problem must lie in something like how ports are handled on github actions, it seems?

**Comment by hjoliver** [comment]
This seems to be about sending mail to the external world on GH Actions CI failures, but might be useful?

https://github.com/jsiwek/ci-email-action#ci-email-action

**Comment by MetRonnie** [comment]
> This seems to be about sending mail to the external world on GH Actions CI failures, but might be useful?
> 
> https://github.com/jsiwek/ci-email-action#ci-email-action
> 
> (maybe not, its a special `notify:` action?)

It says it's for the `check_suite` event only, which only seems to be useful for GitHub Apps from what I can tell. In any case, for this issue we need to capture the mail; we don't want to actually send it

**Review by kinow — COMMENTED** [review]
I was curious at this as I never used the e-mail functionality in Cylc. From what I understood, that's for events in the workflow, where you can send notifications.

@MetRonnie not sure if helpful, but I got the functional tests for e-mails in Cylc passing locally with the following:

- Removed the for-loop in test-header, and specified the SMTPD port to fixed `8025` (not sure why trying so many ports?)
- Moved a Python script to my path (`~/bin/mail`)

```bash
(venv) kinow@ranma:~/Development/python/workspace/cylc-flow$ CYLC_TEST_DEBUG=true ./etc/bin/run-functional-tests tests/functional/events/29-task-event-mail-1.t 
[16:02:41] tests/functional/events/29-task-event-mail-1.t .. ok    12955 ms ( 0.00 usr  0.00 sys +  5.31 cusr  0.55 csys =  5.86 CPU)
[16:02:51]
All tests successful.
Files=1, Tests=4, 14 wallclock secs ( 0.02 usr  0.00 sys +  5.31 cusr  0.55 csys =  5.88 CPU)
Result: PASS
```

Here's my diff from `master`

```
diff --git a/tests/functional/lib/bash/test_header b/tests/functional/lib/bash/test_header
index 2afdefef2..bde3e954f 100644
--- a/tests/functional/lib/bash/test_header
+++ b/tests/functional/lib/bash/test_header
@@ -657,33 +657,30 @@ __PYTHON__
 }
 
 mock_smtpd_init() {  # Logic borrowed from Rose
-    local SMTPD_PORT=
-    for SMTPD_PORT in 8025 8125 8225 8325 8425 8525 8625 8725 8825 8925; do
-        local SMTPD_HOST="localhost:${SMTPD_PORT}"
-        local SMTPD_LOG="${TEST_DIR}/smtpd.log"
-        python3 -u -m 'smtpd' -c 'DebuggingServer' -d -n "${SMTPD_HOST}" \
-            1>"${SMTPD_LOG}" 2>&1 &
-        local SMTPD_PID="$!"
-        while ! grep -q 'DebuggingServer started' "${SMTPD_LOG}" 2>'/dev/null'
-        do
-            if ps "${SMTPD_PID}" 1>/dev/null 2>&1; then
-                sleep 1
-            else
-                rm -f "${SMTPD_LOG}"
-                unset SMTPD_HOST SMTPD_LOG SMTPD_PID
-                break
-            fi
-        done
-        if [[ -n "${SMTPD_PID:-}" ]]; then
-            # Variables used by tests
-            # shellcheck disable=SC2034
-            TEST_SMTPD_HOST="${SMTPD_HOST}"
-            # shellcheck disable=SC2034
-            TEST_SMTPD_LOG="${SMTPD_LOG}"
-            TEST_SMTPD_PID="${SMTPD_PID}"
+    local SMTPD_PORT=8025
+    local SMTPD_HOST="localhost:${SMTPD_PORT}"
+    local SMTPD_LOG="${TEST_DIR}/smtpd.log"
+    python3 -u -m 'smtpd' -c 'DebuggingServer' -d -n "${SMTPD_HOST}" \
+        1>"${SMTPD_LOG}" 2>&1 &
+    local SMTPD_PID="$!"
+    while ! grep -q 'DebuggingServer started' "${SMTPD_LOG}" 2>'/dev/null'
+    do
+        if ps "${SMTPD_PID}" 1>/dev/null 2>&1; then
+            sleep 1
+        else
+            rm -f "${SMTPD_LOG}"
+            unset SMTPD_HOST SMTPD_LOG SMTPD_PID
             break
         fi
     done
+    if [[ -n "${SMTPD_PID:-}" ]]; then
+        # Variables used by tests
+        # shellcheck disable=SC2034
+        TEST_SMTPD_HOST="${SMTPD_HOST}"
+        # shellcheck disable=SC2034
+        TEST_SMTPD_LOG="${SMTPD_LOG}"
+        TEST_SMTPD_PID="${SMTPD_PID}"
+    fi
 }
 
 mock_smtpd_kill() {  # Logic borrowed from Rose

```

And here's my (hack-ish?) `mail` replacement

```python
#!/usr/bin/env python3

import argparse
import smtplib
import sys

parser = argparse.ArgumentParser(description='Cylc functional tests mail command.')
parser.add_argument('-s', metavar='subject', dest='subject', type=str, help='e-mail subject')
parser.add_argument('-r', metavar='reply_to', dest='sender', type=str, help='e-mail reply-to address')
parser.add_argument('to', metavar='to', type=str, help='e-mail destination address')
parser.add_argument('body', metavar='body', nargs='?', type=argparse.FileType('r'), default=sys.stdin, help='e-mail body')

args = parser.parse_args()

port = 8025
smtp_server = "localhost"
sender_email = args.sender
receiver_email = args.to
message = f"""\
Subject: {args.subject}

{args.body.read()}"""

# https://realpython.com/python-send-email/
with smtplib.SMTP(smtp_server, port) as server:
    server.sendmail(sender_email, receiver_email, message)

```

I found it easier than installing `mailutils` or other packages in my box.

Cheers
Bruno

**Comment by oliver-sanders** [comment]
> (not sure why trying so many ports?)

Probably incase they are in use.

**Comment by MetRonnie** [comment]
> not sure if helpful, but I got a functional test for e-mail sending in Cylc passing locally with the following

I've tried to get that working on github actions but it keeps saying `mail: command not found`. This is what I've tried: https://github.com/MetRonnie/spork/commit/c1ac3422a344de6cd93e0bf9b0fff883c2ce844c

**Comment by kinow** [comment]
> > not sure if helpful, but I got a functional test for e-mail sending in Cylc passing locally with the following
> 
> I've tried to get that working on github actions but it keeps saying `mail: command not found`. This is what I've tried: [MetRonnie/spork@c1ac342](https://github.com/MetRonnie/spork/commit/c1ac3422a344de6cd93e0bf9b0fff883c2ce844c)

Huh, had a quick look, and looks like `/home/runner/work/spork/spork/.github/bin` is in the `$PATH`. Did you `chmod u+x .github/bin/mail `?

**Comment by MetRonnie** [comment]
> Huh, had a quick look, and looks like `/home/runner/work/spork/spork/.github/bin` is in the `$PATH`. Did you `chmod u+x .github/bin/mail `?

Forgot to checkout the repo!!

**Comment by MetRonnie** [comment]
Unfortunately still not working:
```
Traceback (most recent call last):
  File "/home/runner/work/spork/spork/.github/bin/mail", line 25, in <module>
    with smtplib.SMTP(smtp_server, port) as server:
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 308, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by kinow** [comment]
> Unfortunately still not working:
> 
> ```
> Traceback (most recent call last):
>   File "/home/runner/work/spork/spork/.github/bin/mail", line 25, in <module>
>     with smtplib.SMTP(smtp_server, port) as server:
>   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 253, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 339, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/smtplib.py", line 308, in _get_socket
>     return socket.create_connection((host, port), timeout,
>   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/socket.py", line 808, in create_connection
>     raise err
>   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/socket.py", line 796, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> ```

I think the SMTP server and client probably are not agreeing on host+port?

Might be easier to test with the existing functions in that `test_header` file. Here's a quick test: https://github.com/cylc/cylc-flow/compare/master...kinow:add-mail-tests (added `push` to `on` to test the action). Built over here: https://github.com/kinow/cylc-flow/runs/1036479605?check_suite_focus=true

Looking at the logs of one of the jobs:

```
2020-08-27T12:34:09.5414232Z [12:34:09] tests/f/events/18-suite-event-mail.t ............................................. ok    26408 ms ( 0.00 usr  0.03 sys + 20.74 cusr  1.90 csys = 22.67 CPU)
2020-08-27T12:29:37.5358576Z [12:29:37] tests/f/events/13-task-event-mail-globalcfg.t ..................... ok    57232 ms ( 0.03 usr  0.00 sys + 36.34 cusr  3.57 csys = 39.94 CPU)
2020-08-27T12:31:34.8000502Z [12:31:34] tests/f/events/19-suite-event-mail-globalcfg.t .................... ok    22241 ms ( 0.02 usr  0.01 sys + 48.57 cusr  4.73 csys = 53.33 CPU)
2020-08-27T12:39:39.9313262Z [12:39:39] tests/f/events/09-task-event-mail.t ............................... ok    51000 ms ( 0.02 usr  0.03 sys + 56.17 cusr  5.50 csys = 61.72 CPU)
2020-08-27T12:29:09.7839027Z [12:29:09] tests/f/events/29-task-event-mail-1.t .......................... ok    37651 ms ( 0.02 usr  0.01 sys + 21.12 cusr  2.20 csys = 23.35 CPU)
...
```

I think that `29-task-event-mail` is the one I tried before, and it would only run if `mail` was present.

**Comment by MetRonnie** [comment]
@kinow You've done it! 🥇 

(It wasn't working for me because of silly mistakes that are difficult to debug on GH Actions)

**Comment by MetRonnie** [comment]
I've cherry-picked Bruno's commit with a few changes to let it still try different ports in case 8025 is busy. Tests seem to pass!
```
[16:49:30] tests/f/events/18-suite-event-mail.t ... ok   31775 ms ( 0.00 usr  0.01 sys + 15.48 cusr  1.61 csys = 17.10 CPU)
```

**Comment by oliver-sanders** [comment]
```
[16:49:30] tests/f/events/18-suite-event-mail.t ............................................. ok    31775 ms ( 0.00 usr  0.01 sys + 15.48 cusr  1.61 csys = 17.10 CPU)
```

**Review by kinow — APPROVED** [review]

**Comment by hjoliver** [comment]
Brilliant :tada:

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
