### PR TITLE
Workflow config changes:  environment, hold after point

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes partially address #3696

- `[cylc][environment]` -> obsolete
- `[scheduling]hold after point` -> `[scheduling]hold after cycle point`

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No changelog entry needed (entry will be written for completed #3696 changes before next release)
- [x] No documentation update required (docs will be updated after #3696 is closed)
- [x] No dependency changes.

### CODE REVIEW

**Comment by MetRonnie** [comment]
I've noticed users frequently have this in their `suite.rc`:
```ini
[cylc]
    [[environment]]
        CYLC_VERSION=7.8.6
        ROSE_ORIG_HOST=vld123
        ROSE_SITE=
        ROSE_VERSION=2019.01.3
{# Rose Configuration Insertion: Done #}
```
I take it this is not needed in Cylc 8?

**Review by wxtim — APPROVED** [review]
🎉

**Comment by oliver-sanders** [comment]
> I take it this is not needed in Cylc 8?

Yeah, Rose/Cylc add this environment automatically, overriding it in this way is unnecessary and potentially slightly dangerous, however, old habits die hard.

We will restate this in the run up to Cylc8.

**Comment by oliver-sanders** [comment]
Adding the blocked label whist we evaluate the usage of rogue environment variables defined in Rose configurations, will hopefully remove shortly, sorry.

**Comment by oliver-sanders** [comment]
Ok, I think we have now agreed a way forward on the Rose side, bypassing `[cylc][environment]` sorry for the delay.

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
Fixed merge conflict (also, I had missed out a deprecation test for `[cylc][environment]`)

**Comment by oliver-sanders** [comment]
Whoever spots it first, whack the merge button once the tests pass.

**Pull request merged**
