### PR TITLE
remove lines which break.

### PR DESCRIPTION
**Pull request by wxtim**
sibling: https://github.com/cylc/cylc-rose/pull/34

Test fix associated with https://github.com/cylc/cylc-rose/pull/34
This is a small change with no associated Issue.

- [x] Appropriate tests are included (unit and/or functional).

- [x] No change log entry required (testing fix).

- [x] No documentation update required.

- [x] No dependency changes.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I also get a failure on tests/functional/cylc-install/03-file-transfer.t

**Comment by wxtim** [comment]
> I also get a failure on tests/functional/cylc-install/03-file-transfer.t

I thought that I had fixed that - I have now.

**Review by datamel — APPROVED** [review]
I have checked this branch out (with the partner cylc-rose pr) and run the tests. I have also rebased onto master (cylc reinstall is now merged) and the tests pass. 
I have confirmed that the fixed tests are broken on master. 
Approved and thanks for fixing @wxtim.

**Comment by datamel** [comment]
Test failures will be fixed once sibling is merged as they pass when both prs are checked out for me locally.

**Review by oliver-sanders — APPROVED** [review]

**Comment by oliver-sanders** [comment]
merged the sibling PR, waiting for the tests to go through...

**Comment by hjoliver** [comment]
(Tests passed)

**Pull request merged**
