### PR TITLE
Fix bug in use of job runner command template.

### LINKED ISSUE #4987: job runner comand template not being used
There are some functional tests that purport to test this, but they require job runner `at`, so perhaps no one is running them at the moment.
```console
$ git grep "job runner command template" tests/*functional
tests/flakyfunctional/job-submission/19-chatty.t:        job runner command template = talkingnonsense %(job)s
tests/functional/cylc-poll/02-task-submit-failed.t:        job runner command template = at noon tomorrow
tests/functional/job-submission/09-activity-log-host-bad-submit.t:        job runner command template = at non
tests/functional/job-submission/16-timeout.t:        job runner command template = sleep 30
tests/functional/reload/20-stop-point.t:        job runner command template = sleep 5
tests/functional/restart/05-submit-failed.t:        job runner command template = at oh-no
```

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #4987

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.

- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Already covered by existing tests.
- [ ] Does not need tests (why?).

- [ ] Appropriate change log entry included.
- [ ] No change log entry required (why? e.g. invisible to users).

- [ ] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/XXXX.
- [ ] (7.8.x branch) I have updated the documentation in this PR branch.
- [ ] No documentation update required.

- [ ] [if bugfix] PRs raised to both master and the relevant bugfix branch.

### CODE REVIEW

**Comment by hjoliver** [comment]
The first commit fixes access to the global config item.

However, there's another problem, it's only used if the `job runner` has no built-in `submit` method.

DRAFT while I sort that out.

**Comment by hjoliver** [comment]
The dodgy logic: https://github.com/cylc/cylc-flow/blob/master/cylc/flow/job_runner_mgr.py#L689-L740

**Comment by MetRonnie** [comment]
Sorry, accidentally deleted 8.0.x!

**Comment by MetRonnie** [comment]
I'm closing this as it is not correct. `job_runner_cmd_tmpl` is consistently used as the key in the `submit_opts` dict
 
https://github.com/cylc/cylc-flow/blob/7e96003f6a0225cf135036bc6642dd4928499dbd/cylc/flow/job_runner_mgr.py#L688

**Pull request closed without merging**
