### PR TITLE
file parsing: check for CWD existence

### LINKED ISSUE #5688: cylc commands from a directory that does not exist should not cause failures (generally)
### Description

Running `cylc` commands from a directory that no longer exists causes failures. I suggest that whether the directory you are currently in exists or not should not matter (maybe there are some commands it does matter, but many should not, e.g. `scan`, `tui`).

### Reproducible Example

```
$ d=$(mktemp -d)
$ cd "$d"
$ rmdir "$d"
$ cylc scan
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<_AsyncPipe._generate() done, defined at /home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/async_u
til.py:148> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/async_util.py", line 151, in _generate
    async for item in gen.func(*gen.args, **gen.kwargs):
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/network/scan.py", line 222, in scan
    max_depth = glbl_cfg().get(['install', 'max depth'])
                ^^^^^^^^^^
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/cfgspec/glbl_cfg.py", line 22, in glbl_cfg
    return GlobalConfig.get_inst(cached=cached)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1882, in get_inst
    cls._DEFAULT.load()
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1909, in load
    self._load(fname, conf_type)
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1889, in _load
    self.loadcfg(fname, conf_type)
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/parsec/config.py", line 80, in loadcfg
    sparse = parse(
             ^^^^^^
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/parsec/fileparse.py", line 565, in parse
    flines = read_and_proc(fpath, template_vars, opts=opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/miniconda3/envs/cylc-8.2.0/lib/python3.11/site-packages/cylc/flow/parsec/fileparse.py", line 404, in read_and_proc
    odir = os.getcwd()
           ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
```

### Expected Behaviour

Current directory not existing should not cause failure in many commands.

### Potential Fix

For the `cylc scan` case at least, the below snippet removes the failure and produces correct results. I cannot comment if this change would have flow on impacts to other commands.

```
$ diff fileparse.py fileparse.modded.py
404c404,407
<     odir = os.getcwd()
---
>     try:
>         odir = os.getcwd()
>     except FileNotFoundError:
>         odir = None
503c506,507
<     os.chdir(odir)
---
>     if odir is not None:
>         os.chdir(odir)
```

Although there are two error messages still printed to command line which I'm unsure the origin of and ideally wouldn't exist either.

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory                                                         
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

### PR DESCRIPTION
**Pull request by hjoliver**
Close #5688 

But note https://github.com/cylc/cylc-flow/issues/5688#issuecomment-1679921665 

Is it worth doing this?

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX. [not needed]
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by hjoliver** [comment]
Yes that's what I found too (see the associated issue) - but @ColemanTom claims it works in his environment, which would be some kind of an improvement. Can you comment Tom?

**Comment by ColemanTom** [comment]
```
[tc2375@gadi-login-03 ~]$ mkdir tmpdir
[tc2375@gadi-login-03 ~]$ cd tmpdir
[tc2375@gadi-login-03 tmpdir]$ cylc scan
rewind/run7 gadi-login-03.gadi.nci.org.au:43067 186324
rewind/run6 gadi-login-03.gadi.nci.org.au:43031 94705
rewind/run3 gadi-login-03.gadi.nci.org.au:43053 3954261
[tc2375@gadi-login-03 tmpdir]$ rm -fr ~/tmpdir
[tc2375@gadi-login-03 tmpdir]$ cylc scan
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ERROR: error getting working directory name: no such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<_AsyncPipe._generate() done, defined at /g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/async_util.py:148> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/async_util.py", line 151, in _generate
    async for item in gen.func(*gen.args, **gen.kwargs):
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/network/scan.py", line 222, in scan
    max_depth = glbl_cfg().get(['install', 'max depth'])
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/cfgspec/glbl_cfg.py", line 22, in glbl_cfg
    return GlobalConfig.get_inst(cached=cached)
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1903, in get_inst
    cls._DEFAULT.load()
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1930, in load
    self._load(fname, conf_type)
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/cfgspec/globalcfg.py", line 1910, in _load
    self.loadcfg(fname, conf_type)
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/parsec/config.py", line 80, in loadcfg
    sparse = parse(
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/parsec/fileparse.py", line 565, in parse
    flines = read_and_proc(fpath, template_vars, opts=opts)
  File "/g/data/dp9/tc2375/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/parsec/fileparse.py", line 404, in read_and_proc
    odir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
[tc2375@gadi-login-03 tmpdir]$ vi ~/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/cylc/flow/parsec/fileparse.py
[tc2375@gadi-login-03 tmpdir]$ cylc scan
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ERROR: error getting working directory name: no such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
rewind/run3 gadi-login-03.gadi.nci.org.au:43053 3954261
rewind/run7 gadi-login-03.gadi.nci.org.au:43067 186324
rewind/run6 gadi-login-03.gadi.nci.org.au:43031 94705
```

**Comment by ColemanTom** [comment]
cylc version also works for me with this change.

```
$ cylc version
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ERROR: error getting working directory name: no such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
8.2.1
```

**Comment by ColemanTom** [comment]
What is your PYTHONPATH? There is a detailed discussion [here](https://forum.snapcraft.io/t/python-pkg-resources-only-works-in-certain-paths/978/9) about this issue. If you have a trailing or leading `:` in your PYTHONPATH, then the CWD will get added to your `sys.path`, or if you do an interactive call to Python. 

```
$ ~/miniconda3/envs/cylc-8.2.0/bin/python ~/script.py
['/home/username', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python39.zip', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/lib-dynload', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages']
/home/username/script.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
$ ~/miniconda3/envs/cylc-8.2.0/bin/python -c 'import sys; print(sys.path); import pkg_resources'
['', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python39.zip', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/lib-dynload', '/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages']
<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2075, in find_distributions
    importer = get_importer(path_item)
  File "/home/username/miniconda3/envs/cylc-8.2.0/lib/python3.9/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1608, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 162, in _path_isdir
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by ColemanTom** [comment]
Other comment, based on the above output, pkg_resources is deprecated. Can `importlib.resources` and/or `importlib.metadata` be used instead? They don't have the pkg_resources issue you identified above.

**Comment by oliver-sanders** [comment]
Strange.

> What is your PYTHONPATH

Unset (I don't use PYTHONPATH)

I would expect any difference in behaviour is likely down to Python version 

```
$ python --version
Python 3.9.16
$ pip list | grep setuptools
setuptools                     68.0.0
$ pip list | grep import
importlib-metadata             6.8.0
importlib-resources            6.0.0
```

**Comment by ColemanTom** [comment]
```
$ python --version
Python 3.9.17
$ pip list | grep 'setuptools\|import'
importlib-metadata        6.8.0
importlib-resources       6.0.1
setuptools                68.0.0
```

Installing matching versions to yours, and I don't get failures whether I run a script or do `python -c` approach I showed above.

I should perhaps note, it works for me on two completely different platforms, one an HPC login node, an another a VM, maintained by completely different organisations.

**Comment by oliver-sanders** [comment]
I've matched your versions but cannot get this to succeed on two different vms and three different filesystems!

**Comment by oliver-sanders** [comment]
There's no harm in us accepting this change, however, it doesn't look like this is behaviour you can rely on (especially as we cannot reproduce your results so cannot test this) so sanitising working practices to avoid chopping off the branch you're standing on is going to be the safer option. I'm surprised that more commands don't fail under these circumstances as a wide range of filesystem operations are going to fail.

**Comment by hjoliver** [comment]
OK I've clarified and commented the code, and added a unit test. @oliver-sanders - can you do a quick review and merge it?

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
