### PR TITLE
protobuf 3.12 optional fields pre-release

### LINKED ISSUE #3589: Update Protobuf to 3.12+ - Fields with default value not set in deltas
**Problem:**
(from Riot)

Scalar fields like bool, int, string (...etc) have default values (False, 0, “”), however   , at the receiving end you cannot tell whether a field was intentionally set to the default... 

For example:
```
>>> from cylc.flow.data_messages_pb2 import PbWorkflow
>>> var1 = PbWorkflow(id='foo', host='', port=0)
>>> var1.ListFields()
[(<google.protobuf.pyext._message.FieldDescriptor object at 0x7fa3ac80edd0>, 'foo')]
>>> var1
id: "foo"
```
I posted my frustrations in a long standing issue here:
https://github.com/protocolbuffers/protobuf/issues/359
(This changed with proto2 => proto3)

This means things like `latestMessage`, `isHeldTotal`,  `port`  (etc..) have to either always send the data value from UIS data-store or only send the non-default... Unacceptable, as there’s no option in proto3 to have alternate defaults...

I/we don’t want clunky workarounds..

**Solution(s):**

1) A developer from Protobuf responded (fairly quickly); 
https://github.com/protocolbuffers/protobuf/issues/359#issuecomment-623050883
and referenced an upcoming release feature to fix this:
https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
(which looks like it's in `master`)
```
syntax = "proto3";
package example;

message MyMessage {
  // No presence:
  int32 not_tracked = 1;

  // Explicit presence:
  optional int32 tracked = 2;
}
```
With the `protoc` run with option `--experimental_allow_proto3_optional`..
This is suppose to be available via release from 3.12 or later..

2) I don’t think it’ll be hard to change (heck we could probably even pickle GraphQL ObjectTypes if we wanted or just use dict)..

This issue came to light when working with the delta subscription PRs:
https://github.com/cylc/cylc-flow/pull/3500
https://github.com/cylc/cylc-uiserver/pull/118
And can be addressed at any point with option 1) (and the availability of `protobuf=3.12.*`), however anything more drastic should wait until after they go in.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by dwsutherland**
These changes close #3589 

Held icons no longer linger in WUI/TUI  🎉 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by dwsutherland** [comment]
All fields set as optional where needed, so if any are set (to any value) that will be read as set by the receiver ...

We can reassess individual field behaviour once/if the protobuf mixing issue (above) is fixed, otherwise I don't see any harm in being intentional/explicit about which fields are set and which to clear (i.e. `field.Clear()`)

**Comment by hjoliver** [comment]
Should this go in before the delta-PRs?  (Does it matter?)

**Comment by dwsutherland** [comment]
> Should this go in before the delta-PRs? (Does it matter?)

Yes, can go in first, if there are conflicts delta-PR to resolve.

**Comment by dwsutherland** [comment]
> I tried cylc hold five foo.*, but the icon worked the same for both master and this branch?

Strange, they don't disappear after release on `master` for me. Did the UI Server re-install with `3.12.0rc1`?

**Comment by kinow** [comment]
>Strange, they don't disappear after release on master for me. Did the UI Server re-install with 3.12.0rc1?

Could be my suite that's too simple maybe (five, running jobs with sleep 2). I re-installed the Cylc Flow module only. UI Server was still on `master`.

**Comment by dwsutherland** [comment]
> > Strange, they don't disappear after release on master for me. Did the UI Server re-install with 3.12.0rc1?
> 
> Could be my suite that's too simple maybe (five, running jobs with sleep 2). I re-installed the Cylc Flow module only. UI Server was still on `master`.

It's only the old tasks who's `isHeld` doesn't change from `true`.. So if they disappear to quickly, then yeah, we wouldn't notice it.

**Comment by hjoliver** [comment]
I can get "stuck" hold icons in `cylc tui` on master on a slightly more complex suite. It's hard to know exactly how to reproduce, but a few hold release cycles will result in a few of them.

**Comment by dwsutherland** [comment]
> I can get "stuck" hold icons in `cylc tui` on master on a slightly more complex suite. It's hard to know exactly how to reproduce, but a few hold release cycles will result in a few of them.

Yes, you should get lingering held icons for `cylc tui` on master.. But after reinstalling with this branch, they should disappear on release.

**Comment by dwsutherland** [comment]
Ah I think I know why... I had a workaround in place that set the held and reloaded booleans back to False on delta application:

https://github.com/cylc/cylc-flow/blob/37e676e8c1235adb5b61229678b7bc9c31ee1b48/cylc/flow/data_store_mgr.py#L142-L143

https://github.com/cylc/cylc-flow/blob/37e676e8c1235adb5b61229678b7bc9c31ee1b48/cylc/flow/data_store_mgr.py#L155-L156

Can get rid of them now..

**Comment by hjoliver** [comment]
> Approved in principle.

Merging in practice :grin:

**Pull request merged**
