### PR TITLE
Fix coverage

### PR DESCRIPTION
**Pull request by MetRonnie**
This is a small change with no associated Issue.

- Apparently coverage doesn't work properly with pytest if you don't `pip install -e` (editable mode)
- Switched from the deprecated Codecov bash uploader to Codecov's dedicated GH Action

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Does not need tests.
- [x] No change log entry required
- [x] No documentation update required.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Looks good to me! Codecov bot hasn't commented yet, but maybe it's slow today, or maybe the GH action needs a parameter for that? Not a blocker IMO.

Checked the Codecov page, and it's showing +4% increase for this PR. Good job @MetRonnie ! https://app.codecov.io/gh/cylc/cylc-flow/compare/4348

**Comment by MetRonnie** [comment]
> Codecov bot hasn't commented yet, but maybe it's slow today, or maybe the GH action needs a parameter for that?

We have bot commenting switched off in `codecov.yml`. Is it something we want to turn on?

**Comment by oliver-sanders** [comment]
> We have bot commenting switched off in codecov.yml. Is it something we want to turn on?

NO!

**Review by oliver-sanders — APPROVED** [review]
I have absolutely no idea why this would help, nothing in the codecov docs to suggest it would, however, it does appear to bump the coverage score.

My only guess is that uploading a mix of `pip install` and `pip install -e` reports could cause issues, however, that doesn't make much sense as the file paths are all correctly identified in the reports :confused:.

No reason not to do this, should remember to test non-editable installs manually whenever making changes that impact packaging.

**Pull request merged**
