### PR TITLE
xtriggers: improve parser

### LINKED ISSUE #5575: xtriggers and values with a comma breaks Cylc
### Description

I've tested this in both Cylc7 and Cylc8 and it exists for both.
If you have a value which contains a `,`, 

### Reproducible Example

See the below snippet. First, I show validate works without a `,` in the message.
Next I put a comma in, and show it fails to validate.

NOTE: I modified the `validate.py` file to print out the values before it tries to `_coerce_type` them for reference.
You can see that the message was split on a comma.

```bash

$ cat flow.cylc
#!jinja2
{%  set A = 'Hello world' %}
[scheduler]
   allow implicit tasks=True
[scheduling]
    initial cycle point = 20200101
    [[xtriggers]]
        B = workflow_state("basic", task="b", point="%(point)s", message="{{A}}")
    [[ graph]]
        P1D = """
            @B => b
        """
$ cylc validate $PWD
"basic"
"b"
"%(point)s"
"Hello world"
Valid for cylc-8.1.3
$ vi flow.cylc
$ cylc validate $PWD
"basic"
"b"
"%(point)s"
"Hello
Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1052, in _coerce_type
    val = int(value)
ValueError: invalid literal for int() with base 10: '"Hello'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1055, in _coerce_type
    val = float(value)
ValueError: could not convert string to float: '"Hello'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/terminal.py", line 232, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 132, in main
    _main(parser, options, workflow_id)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 136, in _main
    asyncio.run(wrapped_main(parser, options, workflow_id))
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 154, in wrapped_main
    cfg = WorkflowConfig(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/config.py", line 308, in __init__
    self.pcfg = RawWorkflowConfig(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/cfgspec/workflow.py", line 2042, in __init__
    self.loadcfg(fpath, "workflow definition")
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/config.py", line 86, in loadcfg
    self.validate(sparse)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/config.py", line 96, in validate
    return self.validator(sparse, self.spec)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1139, in cylc_config_validate
    return CylcConfigValidator().validate(cfg_root, spec_root)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 230, in validate
    cfg[key] = self.coercers[specval.vdr](value, keys + [key])
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1031, in coerce_xtrigger
    kwargs[key.strip()] = cls._coerce_type(val.strip())
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1063, in _coerce_type
    val = cls.strip_and_unquote([], value)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 539, in strip_and_unquote
    raise IllegalValueError("string", keys, value)
cylc.flow.parsec.exceptions.IllegalValueError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/bin/cylc", line 10, in <module>
    sys.exit(main())
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 656, in main
    execute_cmd(command, *cmd_args)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 286, in execute_cmd
    entry_point.resolve()(*args)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/terminal.py", line 241, in wrapper
    EXC_EXIT.format(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/exceptions.py", line 240, in __str__
    msg += itemstr(self.keys[:-1], self.keys[-1], value=self.value)
IndexError: list index out of range

```

### Expected Behaviour

A comma in a value should not break xtriggers.
At minimum, a way to escape a comma here, but not have the escape character passed into the xtrigger itself.

### LINKED ISSUE #5576: Debug print of xtriggers with a trailing comma in the flow.cylc definition is odd
### Problem

I don't know this causes any problems, but if you put an xtrigger in, like `workflow_state('b', task='c', point='%(point)s', message='hi',)` (NOTE the trailing comma), and play a workflow with `--debug` on, the debug output in a workflow log will have an oddity.

`2023-06-13T15:18:59+10:00 DEBUG - ['cylc', 'function-run', 'workflow_state', '["b", ""]', '{"task": "c", "point": "20200101T0000Z", "message": "hi"}', '/home/user/cylc-run/basic-workflow/run1']`

I'm unsure if it still runs fine, or if it fails, I've not explored it any further. If it is what Cylc passes to python functions, it would cause problems as I don't believe it is valid python syntax. If it isn't what is passed through, it could be cleaned in the logs to make it look more accurate.

Why is this a problem? If you have a long xtrigger like below, which is spread over multiple lines (think black style formatting), a trailing whitespace can be desirable to make diffs less verbose as adding a new entry at the end does not require modifying two lines, only one, again like many auto-formatters do for python code.

```
trigger( \
    a=a, \
   b=b, \
  ....
  z=z,
): PT2M
```

NOTE: Same behaviour exists in Cylc7 and Cylc8.

### Proposed Solution

If the last item in the comma split is an empty list, ignore it.

### PR DESCRIPTION
**Pull request by oliver-sanders**
Tolerate comas within strings and equals signs withing kwarg strings.

* Closes #5575
* Closes #5576

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch (we are skipping 8.1.5)

### CODE REVIEW

**Comment by ColemanTom** [comment]
I did a quick test of your function and it seems to work well for my tests. Obviously some unit tests to confirm a variety of cases have been tested would be good, but I'm sure you have that on the way. Thanks for the quick action on this one, it will help simplify some of the xtriggers we have.

**Review by hjoliver — APPROVED** [review]
Looks good, tested. Perhaps you could add a few more cases to the doctests (e.g. no trailing comma, whitespace).

**Comment by oliver-sanders** [comment]
Doctests for `parse_xtrig_arglist` already have examples with/without trailing comma. Whitespace doesn't influence the approach used.

**Comment by hjoliver** [comment]
> Whitespace doesn't influence the approach used.

We could potential break it by changing the approach in the future. However, no biggie in this case.

**Comment by oliver-sanders** [comment]
Added a (pointless :grin:) whitespace test and rebased.

**Comment by oliver-sanders** [comment]
No, that shouldn't work because xtrigger signatures don't support all Python types (e.g. Lists):

https://github.com/cylc/cylc-flow/blob/e550ca4c48e69a7daecad20d74522855a8caf016/cylc/flow/parsec/validate.py#L1108-L1136

**Comment by ColemanTom** [comment]
> No, that shouldn't work because xtrigger signatures don't support all Python types (e.g. Lists):
> 
> https://github.com/cylc/cylc-flow/blob/e550ca4c48e69a7daecad20d74522855a8caf016/cylc/flow/parsec/validate.py#L1108-L1136
> 
> More info: https://github.com/cylc/cylc-flow/issues/5588

I've not looked, but are these limitations covered in the documentation?

**Comment by hjoliver** [comment]
> I've not looked, but are these limitations covered in the documentation?

Yes: 

https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/external-triggers.html#custom-trigger-functions

> integer, float, boolean, and string arguments will be recognized and passed to the function as such

And you could probably use `json.loads()` internally to deserialize lists etc., if necessary.

**Comment by oliver-sanders** [comment]
https://github.com/cylc/cylc-flow/issues/5588

**Review by wxtim — APPROVED** [review]

**Pull request merged**
