### PR TITLE
Logging: say command actioned instead of succeeded

### PR DESCRIPTION
**Pull request by MetRonnie**
```
INFO - Command succeeded: poll_tasks(['1/foo'])
```

"Succeeded" is perhaps too strong a word. What's happened is the command finished without any uncaught exceptions but it doesn't mean that it necessarily did what the user expected (e.g. in this case there were no available hosts which is logged in a separate debug message).

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] No dependency changes
- [x] Tests updated
- [x] No changelog entry as tiny change
- [x] No docs update needed
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by oliver-sanders — APPROVED** [review]
Might lean towards "completed" rather than "done".

**Comment by MetRonnie** [comment]
Actually I might lean towards "processed" or "submitted" because some commands e.g. reload don't truly finish until the next main loop iteration

**Comment by oliver-sanders** [comment]
We used to say "command queued", not sure what happened to that.

**Comment by MetRonnie** [comment]
That also gets logged but was demoted to debug a while ago

**Comment by oliver-sanders** [comment]
> some commands e.g. reload don't truly finish until the next main loop iteration

Note the proper solution to this will come with https://github.com/cylc/cylc-flow/issues/3329

**Review by hjoliver — APPROVED** [review]
Good, but for the wording, how about "Command actioned".

That says the command action was started but does not necessarily imply it finished yet. 

(Whereas "done" and "completed" imply it finished; and "processed" doesn't necessarily imply it even started).

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
