### PR TITLE
all job messages each delta

### PR DESCRIPTION
**Pull request by dwsutherland**
Closes https://github.com/cylc/cylc-ui/issues/1145

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Covered by existing tests.

### CODE REVIEW

**Review by wxtim — APPROVED** [review]
- [x] Legit fix
- [x] Code makes sense
- [x] Fixes problem described

**Comment by dwsutherland** [comment]
> But does this want to be an 8.0.4 PR/Milestone? (Happy to cherry pick this onto the other branch if you agree)

I can locally cherry-pick, and change target branches.

**Comment by dwsutherland** [comment]
> > But does this want to be an 8.0.4 PR/Milestone? (Happy to cherry pick this onto the other branch if you agree)
> 
> I can locally cherry-pick, and change target branches.

Done.

**Comment by dwsutherland** [comment]
I think the coverage failure was because of the change in branch base after pushing.. (it passed before, and job messaging is well tested)

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
