### PR TITLE
Record all broadcast values in xtrigger return signature

### LINKED ISSUE #3275: xtriggers: only first broadcast results recorded
**Describe the bug**

Only the first (by [ordering](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)) key-value item from the dictionary of results in the success ``return`` signature of an xtrigger gets broadcast actually gets passed on to dependent tasks, when all items are meant to be passed on. For example, with if an xtrigger call returns ``(True, {"ONE": "one", "TWO": "two", "THREE": "three"})``, only ``"ONE": "one"`` is passed via an environment variable ``<xtrigger_name>_ONE=one``.

See below for a concrete example.

NB: I have checked & observed that the problem is not present for regular (non-xtrigger) broadcasts, just for broadcasts  made by any xtrigger.

**Release version(s) and/or repository branch(es) affected?**
This bug had been tested for, & found to present, for both ``8.0a0`` & ``7.8.3``.

**Steps to reproduce the bug**

1. Set up an xtrigger which always succeeds to return a `results`` dict with multiple items, e.g:
```python
def succeed(*args):
    return (True, {"ONE": "one", "TWO": "two", "THREE": "three"})
```
2. Apply it in a simple dummy suite, e.g the one in the docs [here](https://cylc.github.io/doc/built-sphinx-single/index.html#echo), with ``echo_1 = echo(...)`` replaced by ``succeeding = succeed(*args)``, where ``succeed.py`` is under ``<suite-dir>/lib/python``.

3. Observe the suite log to only show that the environment variable for the first key, "ONE", has been broadcast:
```console
2019-08-06T19:43:10+01:00 INFO - [foo.20190806T1943+01] -health check settings: submission timeout=None
2019-08-06T19:43:11+01:00 INFO - Broadcast set:
	+ [foo.20190806T2043+01] [environment]succeeding_ONE=one
2019-08-06T19:43:11+01:00 INFO - [foo.20190806T2043+01] -submit-num=01, owner@host= ...
```

4. Switch the ordering of the ``results`` dict & observe that the suite log display changes accordingly, e.g. after moving ``"TWO:"two"`` to the front (to be the zeroth item):
```console
2019-08-06T19:43:57+01:00 INFO - [foo.20190806T1943+01] -health check settings: submission timeout=None
2019-08-06T19:43:58+01:00 INFO - Broadcast set:
	+ [foo.20190806T2043+01] [environment]succeeding_TWO=two
2019-08-06T19:43:58+01:00 INFO - [foo.20190806T2043+01] -submit-num=01, owner@host=...
```

**Expected behavior**
All defined key-value items specified in a (valid) ``results`` dict get passed to tasks depending on the xtrigger.

**Screenshots**

The 'broadcasts list' page on Cylc Review also supports this, e.g. at step 3 above it shows:

broadcasts_scr

### PR DESCRIPTION
**Pull request by sadielbartholomew**
These changes close #3275.

Using the example xtrigger from the Issue above I now see in the suite log, as expected:

```console
2019-08-06T20:05:28+01:00 INFO - Broadcast set:
	+ [foo.20190806T2005+01] [environment]succeeding_ONE=one
	+ [foo.20190806T2005+01] [environment]succeeding_TWO=two
	+ [foo.20190806T2005+01] [environment]succeeding_THREE=three
2019-08-06T20:05:28+01:00 INFO - [foo.20190806T2005+01] -submit-num=01, owner@host=...
```

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
Confirmed this results in all broadcast values getting logged (and doesn't not break the broadcast to dependent jobs, which was actually working fine!).

**Comment by hjoliver** [comment]
@sadielbartholomew - I'll change the title of this PR and the original Issue to reflect the fact that this was only a logging problem.

**Comment by hjoliver** [comment]
> and doesn't not break the broadcast to dependent jobs, which was actually working fine!

Seems somewhat remarkable that this fixed the logging but did not break the broadcast :thinking:

**Comment by hjoliver** [comment]
@sadielbartholomew - your change here essentially treats N-item xtrigger return values as N separate  broadcasts of single environment variables, instead of a single broadcast of an N-item environment dict. The broadcast code is actually designed to handle the latter (as evidenced by the fact that the actual broadcast was working correctly, if not the logging). So arguably, it is the logging (/broadcast report) code that should be changed here ... although it probably doesn't really much either way.  We might need @matthewrmshin to chime in on this (as author of the broadcast report code, as I recall).

**Comment by sadielbartholomew** [comment]
Great thanks @hjoliver, I've largely responded in https://github.com/cylc/cylc-flow/issues/3275#issuecomment-518954399, to add further notes on the problem itself, but just to add:

> So arguably, it is the logging (/broadcast report) code that should be changed here ...

I agree; now you have pinpointed the fault, I will change it rather than make changes in another area that fix it essentially by bypassing the problem 😄. I'll then look at the tests to see if we can cover the (xtrigger) broadcast logging in a way to catch this.

**Comment by matthewrmshin** [comment]
It is not just logging, but also the database `broadcast_states` record, which is loaded on restart.

The fix here is good (within context). For historical reason, broadcasts settings come in as a list of nested dict, with each nested layer containing a single `key: value` pair. So, the method that writes the string for logging and database recording expects this data structure:

```python
[
    {'environment': {'ONE': 'one'}},
    {'environment': {'TWO', 'two'}},
    {'environment': {'THREE', 'three'}},
]
```

Alternatively, we can try to modernise/modify this function (which may be a bigger can of worms):

https://github.com/cylc/cylc-flow/blob/cd3b5260caf355d7a1191ca9a1d242a611a70b7c/cylc/flow/broadcast_report.py#L57-L87

**Comment by hjoliver** [comment]
@matthewrmshin - OK I'm happy with that. I was just flagging the fact that the code that "does the broadcast" (i.e., in the case of broadcast environment variables, writes the variables to the job environments) does handle a single dict of multiple items (like a task environment section of of suite the config dict). However, in this comment:
> ... it probably doesn't really much either way because I don't think there's actually any other context - at the moment at least - in which we can broadcast multiple settings at once...

I was noting that all other uses of broadcast (i.e. setting multiple items at once using `cylc broadcast`) do actually result in a list of single-item dicts as your function expects.  

So I agree - let's stick with @sadielbartholomew 's change then, and avoid opening another can of worms :+1:

**Comment by hjoliver** [comment]
> It is not just logging, but also the database broadcast_states record, which is loaded on restart.

Right, I hadn't noticed that!

**Comment by hjoliver** [comment]
Note this should be back-ported to 7.8.x, and makes a good reason to release 7.8.4 before too long.

**Comment by hjoliver** [comment]
> It is not just logging, but also the database broadcast_states record, which is loaded on restart.

Worth adding a test on DB contents then, after a broadcast (could add this to the suite-state xtrigger test?).

**Comment by sadielbartholomew** [comment]
>So, the method that writes the string for logging and database recording expects this data structure:

That's the impression I got from doing a ``git grep "put_broadcast"`` under ``cylc/flow`` & looking from that into current usage, which I seen to log okay in dummy suites doing standard broadcasting, hence the solution I put in & then was happy enough with after seeing it work under testing.

>  let's stick with @sadielbartholomew 's change then, and avoid opening another can of worms

I'm happy to go with this too, especially since we have a lot going on otherwise! We can leave the worms for later.

> Note this should be back-ported to 7.8.x

Noted, I will open a counterpart PR to ``7.8.x`` once this is nearly at the merge stage.

**Comment by sadielbartholomew** [comment]
So there's just the multi-broadcast DB test to add in (as well as a change log entry), I believe. I'll start on that after lunch. Thanks, both, for your guidance.

**Comment by sadielbartholomew** [comment]
In the new commit I added two sub-tests, under the existing suite state xtrigger test modules as Hilary suggested, to check that multiple (& all for a test case task in question) xtrigger broadcasts get recorded as they should, in the log & in the database.

The two tests pass on this branch, but fail on master, so they capture the problem as required.
```console
$ etc/bin/run-functional-tests.sh -v flakytests/xtriggers/01-suite_state.t

ok 1 - 01-suite_state-val-up
ok 2 - 01-suite_state-val
ok 3 - 01-suite_state-run-fail
ok 4 - log-grep-ok
ok 5 - suite_state.out-contains-ok
ok 6 - job-contains-ok
not ok 7 - log-contains-ok
not ok 8 - db-broadcast-states.out-contains-ok

    stdout and stderr stored in: /var/tmp/sbarth/cylctb-20190807T155459Z/xtriggers/01-suite_state
Failed 2/8 subtests 
[16:56:14]

Test Summary Report
-------------------
flakytests/xtriggers/01-suite_state.t (Wstat: 0 Tests: 8 Failed: 2)
  Failed tests:  7-8
Files=1, Tests=8, 74 wallclock secs ( 0.02 usr  0.01 sys + 16.10 cusr  6.14 csys = 22.27 CPU)
Result: FAIL
```

(Just noticed there is one shellchecker issue raised via Travis CI, I just need to go in address that).

**Comment by sadielbartholomew** [comment]
Testing all passing, so this should be good to go in now, unless anyone has more feedback. Thanks.

**Comment by sadielbartholomew** [comment]
I'm sorting out a back port for this now & will raise it as a PR shortly.

**Pull request merged**
