### PR TITLE
Conf.move logging to scheduler section

### PR DESCRIPTION
**Pull request by wxtim**
These changes partially address #3696

They have  an upstream PR dependency #3907 

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.

Change log and documentation to be consilidated for this change as part of #3696 .

### CODE REVIEW

**Comment by kinow** [comment]
@wxtim is it ready for review, or still pending discussion or some work?

**Comment by kinow** [comment]
https://www.youtube.com/watch?v=2VIvzDKsOaQ

**Comment by MetRonnie** [comment]
Oops! Just realised I did the same change as part of #3943

**Comment by wxtim** [comment]
I'd kept it draft whilst it was broken.

@MetRonnie  Did it whilst I was working on other things.

**Pull request closed without merging**
