### PR TITLE
Update protobuf version 3.15.*

### PR DESCRIPTION
**Pull request by dwsutherland**
This is a small change with no associated Issue.

The generated python module hasn't really changed at all..
However, the option `--experimental_allow_proto3_optional` is no longer needed, as it the default behaviour for `optional` fields now:
https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] No change log entry required (invisible to users).
- [x] No documentation update required.
- [ ] Created an issue at [cylc-flow conda-forge repository](https://github.com/conda-forge/cylc-flow-feedstock) with version changes (if you changed dependencies in `setup.py`, see `recipe/meta.yaml`).

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Changelog for 15 confirms it's not necessary to use the experimental anymore. File re-compiled, everything looks good. Pending only CI to pass :+1: thanks @dwsutherland !

**Review by kinow — COMMENTED** [review]
@dwsutherland 

```
=========================== short test summary info ============================
FAILED tests/integration/test_scan_api.py::test_format_tree - IndexError: lis...
FAILED tests/integration/test_scan_api.py::test_format_rich - assert 0 == 1
================== 2 failed, 71 passed, 20 warnings in 44.68s ==================
```

**Comment by dwsutherland** [comment]
@kinow  - The protobuf version on conda forge, you already have this draft PR up:
https://github.com/conda-forge/cylc-flow-feedstock/pull/13

Should we just update that?

**Comment by kinow** [comment]
> @kinow - The protobuf version on conda forge, you already have this draft PR up:
> [conda-forge/cylc-flow-feedstock#13](https://github.com/conda-forge/cylc-flow-feedstock/pull/13)
> 
> Should we just update that?

Yup, feel free to update that one or, if easier, to create a new one (you can refer to that one for the check list, bump meta build number, etc if you'd like)

**Comment by dwsutherland** [comment]
Don't know why those tests are failing... Works for me:
```
(flow) sutherlander@cortex-vbox:cylc-flow$ pytest -n 5 tests/integration/test_scan_api.py 
===================================== test session starts ======================================
platform linux -- Python 3.7.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/sutherlander/.envs/flow/bin/python
cachedir: .pytest_cache
rootdir: /home/sutherlander/cylc/cylc-flow, configfile: pytest.ini
plugins: asyncio-0.14.0, cov-2.11.1, xdist-2.2.0, forked-1.3.0
[gw0] linux Python 3.7.5 cwd: /home/sutherlander/cylc/cylc-flow
[gw1] linux Python 3.7.5 cwd: /home/sutherlander/cylc/cylc-flow
[gw2] linux Python 3.7.5 cwd: /home/sutherlander/cylc/cylc-flow
[gw3] linux Python 3.7.5 cwd: /home/sutherlander/cylc/cylc-flow
[gw4] linux Python 3.7.5 cwd: /home/sutherlander/cylc/cylc-flow
[gw1] Python 3.7.5 (default, Apr 19 2020, 20:18:17)  -- [GCC 9.2.1 20191008]
[gw0] Python 3.7.5 (default, Apr 19 2020, 20:18:17)  -- [GCC 9.2.1 20191008]
[gw2] Python 3.7.5 (default, Apr 19 2020, 20:18:17)  -- [GCC 9.2.1 20191008]
[gw3] Python 3.7.5 (default, Apr 19 2020, 20:18:17)  -- [GCC 9.2.1 20191008]
[gw4] Python 3.7.5 (default, Apr 19 2020, 20:18:17)  -- [GCC 9.2.1 20191008]
gw0 [7] / gw1 [7] / gw2 [7] / gw3 [7] / gw4 [7]
scheduling tests via LoadScopeScheduling

tests/integration/test_scan_api.py::test_state_filter 
[gw1] [ 14%] PASSED tests/integration/test_scan_api.py::test_state_filter 
tests/integration/test_scan_api.py::test_name_filter 
[gw1] [ 28%] PASSED tests/integration/test_scan_api.py::test_name_filter 
tests/integration/test_scan_api.py::test_name_sort 
[gw1] [ 42%] PASSED tests/integration/test_scan_api.py::test_name_sort 
tests/integration/test_scan_api.py::test_format_json 
[gw1] [ 57%] PASSED tests/integration/test_scan_api.py::test_format_json 
tests/integration/test_scan_api.py::test_format_tree 
[gw1] [ 71%] PASSED tests/integration/test_scan_api.py::test_format_tree 
tests/integration/test_scan_api.py::test_format_rich 
[gw1] [ 85%] PASSED tests/integration/test_scan_api.py::test_format_rich 
tests/integration/test_scan_api.py::test_scan_cleans_stuck_contact_files 
[gw1] [100%] PASSED tests/integration/test_scan_api.py::test_scan_cleans_stuck_contact_files
```

**Comment by kinow** [comment]
Strange, you are on the same version of Python as that failed job (3.7). I looked at the 3.14 and 3.15 changelog, found nothing that could justify that test failing? Let me kick it at least once :rofl:

**Comment by dwsutherland** [comment]
> > @kinow - The protobuf version on conda forge, you already have this draft PR up:
> > [conda-forge/cylc-flow-feedstock#13](https://github.com/conda-forge/cylc-flow-feedstock/pull/13)
> > Should we just update that?
> 
> Yup, feel free to update that one or, if easier, to create a new one (you can refer to that one for the check list, bump meta build number, etc if you'd like)

What about this one:
```
{% set name = "cylc-flow" %}
{% set version = "8.0a2" %}

package:
  name: {{ name|lower }}
```
change to `8.0a3` or `8.0b0`? or leave it for a separate PR?

**Comment by kinow** [comment]
> > > @kinow - The protobuf version on conda forge, you already have this draft PR up:
> > > [conda-forge/cylc-flow-feedstock#13](https://github.com/conda-forge/cylc-flow-feedstock/pull/13)
> > > Should we just update that?
> > 
> > 
> > Yup, feel free to update that one or, if easier, to create a new one (you can refer to that one for the check list, bump meta build number, etc if you'd like)
> 
> What about this one:
> 
> ```
> {% set name = "cylc-flow" %}
> {% set version = "8.0a2" %}
> 
> package:
>   name: {{ name|lower }}
> ```
> 
> change to `8.0a3` or `8.0b0`? or leave it for a separate PR?

You can modify that there if you'd like. It won't be merged until the release, so we will have time to review and change it again if necessary.

**Comment by dwsutherland** [comment]
> Strange, you are on the same version of Python as that failed job (3.7). I looked at the 3.14 and 3.15 changelog, found nothing that could justify that test failing? Let me kick it at least once 🤣

The only thing I can think of is perhaps the underlying protobuf library (3.15.6) caused it ... But we'd see more wide spread changes surely ...

**Comment by dwsutherland** [comment]
> > > > @kinow - The protobuf version on conda forge, you already have this draft PR up:
> > > > [conda-forge/cylc-flow-feedstock#13](https://github.com/conda-forge/cylc-flow-feedstock/pull/13)
> > > > Should we just update that?
> > > 
> > > 
> > > Yup, feel free to update that one or, if easier, to create a new one (you can refer to that one for the check list, bump meta build number, etc if you'd like)
> > 
> > 
> > What about this one:
> > ```
> > {% set name = "cylc-flow" %}
> > {% set version = "8.0a2" %}
> > 
> > package:
> >   name: {{ name|lower }}
> > ```
> > 
> > 
> > change to `8.0a3` or `8.0b0`? or leave it for a separate PR?
> 
> You can modify that there if you'd like. It won't be merged until the release, so we will have time to review and change it again if necessary.

Sure ok, thanks.

**Comment by kinow** [comment]
Huh, failed again

```

=========================== short test summary info ============================
FAILED tests/integration/test_scan_api.py::test_format_tree - IndexError: lis...
FAILED tests/integration/test_scan_api.py::test_format_rich - assert 0 == 1
================== 2 failed, 71 passed, 20 warnings in 51.48s ==================
```

**Comment by dwsutherland** [comment]
> Huh, failed again
> 
> ```
> 
> =========================== short test summary info ============================
> FAILED tests/integration/test_scan_api.py::test_format_tree - IndexError: lis...
> FAILED tests/integration/test_scan_api.py::test_format_rich - assert 0 == 1
> ================== 2 failed, 71 passed, 20 warnings in 51.48s ==================
> ```

python 3.7.5 vs 3.7.10? lol

**Comment by kinow** [comment]
> > Huh, failed again
> > ```
> > 
> > =========================== short test summary info ============================
> > FAILED tests/integration/test_scan_api.py::test_format_tree - IndexError: lis...
> > FAILED tests/integration/test_scan_api.py::test_format_rich - assert 0 == 1
> > ================== 2 failed, 71 passed, 20 warnings in 51.48s ==================
> > ```
> 
> python 3.7.5 vs 3.7.10? lol

Or maybe something else in the environment on GH actions, or maybe the way the tests are executed? :confused:

**Comment by oliver-sanders** [comment]
The docker swarm stuff is installed using the deps in `conda-environment.yml`. Interestingly they all passed even with the different version.

**Comment by oliver-sanders** [comment]
Those test failures may suggest cylc scan is failing to detect workflows?

**Comment by dwsutherland** [comment]
> Those test failures may suggest cylc scan is failing to detect workflows?

Yeah, it could mean the workflows crashed for some reason.. As the scan doesn't have anything to do with `protobuf` (if that's causing the issue)

**Comment by dwsutherland** [comment]
I give up.. it passed this time.. I only updated the `conda-environment.yml`.. Is that used by the "fast tests"?
Will look.

**Comment by dwsutherland** [comment]
@oliver-sanders - ready to go? I suppose ... lol

**Comment by kinow** [comment]
> I give up.. it passed this time.. I only updated the `conda-environment.yml`.. Is that used by the "fast tests"?
> Will look.

I think fast tests job doesn't use that? Functional tests job does, when it creates the docker container they load the dependencies from this env: https://github.com/cylc/cylc-flow/blob/2ec8cbb2287f4ffdf55dbabb55dcc84610137d54/.github/workflows/test_functional.yml#L134-L140

**Review by kinow — APPROVED** [review]

**Comment by oliver-sanders** [comment]
> I think fast tests job doesn't use that? Functional tests job does,

Yep.

**Comment by oliver-sanders** [comment]
Not managed to reproduce, hoping it doesn't come back, keep an eye out for the next few days.

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
