### PR TITLE
Fix some functional tests that don't run on GH Actions

### PR DESCRIPTION
**Pull request by MetRonnie**
This is a small change with no associated Issue.

**Requirements check-list**
- [x] blah blah...

### CODE REVIEW

**Comment by MetRonnie** [comment]
One test I'm not sure how to fix: https://github.com/cylc/cylc-flow/blob/af770d4a4c2dc08e187a8d7766ba72f4189ac8e3/tests/functional/platforms/02-host-to-platform-upgrade.t#L52-L55

> grep: ~/cylc-run/cylctb-20210119T155714Z/f/platforms/02-host-to-platform-upgrade/log/job/1/upgradeable_cylc7_settings/NN/job.out: No such file or directory

Seems to be because `job.out` only exists on the remote host, not the local filesystem. But I'm not sure what to do about that

**Review by datamel — APPROVED** [review]
All passing now, thanks @MetRonnie

**Comment by datamel** [comment]
> One test I'm not sure how to fix:
> 
> https://github.com/cylc/cylc-flow/blob/af770d4a4c2dc08e187a8d7766ba72f4189ac8e3/tests/functional/platforms/02-host-to-platform-upgrade.t#L52-L55
> 
> > grep: ~/cylc-run/cylctb-20210119T155714Z/f/platforms/02-host-to-platform-upgrade/log/job/1/upgradeable_cylc7_settings/NN/job.out: No such file or directory
> 
> Seems to be because `job.out` only exists on the remote host, not the local filesystem. But I'm not sure what to do about that

Yes, this is failing locally for me but passing on GH actions.

**Comment by oliver-sanders** [comment]
> Seems to be because job.out only exists on the remote host, not the local filesystem.

What platform is this failing for?

* If it is `fs:shared` then the local and remote should be the same filesystem.
  * If the file appears on one host and not another the FS is lagging badly.
  * Try a `sleep 5`, if that fixes it we know what the problem is (an `fsync` is the standard solution).
* If it is `fs:indep` then this means job log retrieval is failing (suite log may enlighten).

**Comment by datamel** [comment]
> > Seems to be because job.out only exists on the remote host, not the local filesystem.
> 
> What platform is this failing for?
> 
> * If it is `fs:shared` then the local and remote should be the same filesystem.
>   
>   * If the file appears on one host and not another the FS is lagging badly.
>   * Try a `sleep 5`, if that fixes it we know what the problem is (an `fsync` is the standard solution).
> * If it is `fs:indep` then this means job log retrieval is failing (suite log may enlighten).

It is failing to return job.out from exvc.. for me. Adding `[remote]retrieve job logs = True` to the flow.cylc returns it (although the `-f` also needs stripping from hostname command), so perhaps it is not mixing old and new correctly.

**Comment by MetRonnie** [comment]
Strange, considering that setting is already in the global config for the test: https://github.com/cylc/cylc-flow/blob/af770d4a4c2dc08e187a8d7766ba72f4189ac8e3/tests/functional/platforms/02-host-to-platform-upgrade.t#L26-L30

**Review by wxtim — APPROVED** [review]
- [x] Seem sensible.
- [x] Run locally.

**Comment by MetRonnie** [comment]
It seems that `$CYLC_TEST_PLATFORM` evaluates as `_remote_background_indep_poll`, so the global config gets
`[platforms][_remote_background_indep_poll]retrieve job logs = True` added to it in the test. But this doesn't work.

However, if I instead set `retrieve job logs` to True in **`_remote_at_indep_poll`**, then the `job.out` gets successfully retrieved

**Pull request merged**
