### PR TITLE
[pre-commit] Add configuration file for pre-commit and flake8

### PR DESCRIPTION
**Pull request by sgaist**
These changes partially address https://github.com/cylc/cylc-admin/issues/64

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (This change is related to code styling/validation.).
- [x] No change log entry required (why? e.g. This change concerns only developers).
- [X] No documentation update required.

### CODE REVIEW

**Comment by sgaist** [comment]
I just realised that a documentation update might be in order for developers/new comers.

One thing that must be decided is how the cleanup shall be done.

For example:
- per-file when one should be modified ? -> some may not be changed before a long time
- once on all the code base ? -> might break pull request already submitted.
- other ?

**Comment by kinow** [comment]
I think linter and unit tests are passing. You can leave the functional tests failures apart @sgaist. They are not deterministic. I will kick Travis a few times until they pass, and try to review this one today too. Thanks!

**Comment by kinow** [comment]
Travis happy, Codacy happy. Codecov can be ignored (small change in a Python file for linter, no tests required) :+1:

**Comment by sgaist** [comment]
@kinow Sorry, I missed the notification.

For adding pre-commit to the test dependencies, will pre-commit be run as part of the test suite ? If so then yes, it makes sense.

The documentation update content will partly depend on the answer to the above.

**Comment by kinow** [comment]
> For adding pre-commit to the test dependencies, will pre-commit be run as part of the test suite ? If so then yes, it makes sense.

It won't run as part of the test suite. Only for the commit hook. I think this is a good point to move it to somewhere else.

> The documentation update content will partly depend on the answer to the above.

Maybe we could have a new dependency group `dev`? With just the `pre-commit` dependency for now? And include it as part of `all`.

**Comment by sgaist** [comment]
@kinow I made the modification you requested.

One thing that still needs be done is to ensure the configuration of black/flake8 matches the style you would like to use within Cylc. For example the line length, the position of the binary operator, etc.

**Comment by hjoliver** [comment]
meeting: consider replacing this with enforcing flake8 compliance via tests?

**Comment by sgaist** [comment]
Do you mean run flake8 by hand in a dedicated test ?

**Comment by hjoliver** [comment]
> Do you mean run flake8 by hand in a dedicated test ?

Sorry @sgaist - I'll have to remind myself of the context here. We have project meeting tonight, will try to make a decision on this.

**Comment by sgaist** [comment]
I have worked on several projects that are currently using [tox](https://tox.readthedocs.io/en/latest/) to run the usual code testing but also have dedicated environment to run flake8 and black checks.

I think it's a tool worth considering.

In any case, both pre-commit and tests can make sense put together. The former for the developer to be able to directly apply cleanups, checks, etc on commit (if not manually run while developing) and the later to ensure it has been done before merging.

**Comment by hjoliver** [comment]
@sgaist - there was still some minor disagreement in the ranks on whether or not running flake8 in pre-commit is a good thing (e.g. it is common to commit temporary/intermediate changes locally that will likely fail) ... however we decided to go ahead with it in the end. So, thanks for this PR, and apologies for the long delay!   Do you want to update the branch? `setup.py` conflicts now;  it's probably an easy fix, but I'll volunteer if you like since the delay was not your fault...

**Comment by sgaist** [comment]
No problem, I'll update it.

I am wondering if there was not a small misunderstanding on the workflow with pre-commit. It's a tool that must be explicitly installed by the developer in order to be active. You can couple it with code quality tests so you can ensure that if someone does not use pre-commit, they will still have the tests to scream about the standards you want to use.

For example, in a small side project I have worked on, I am using [tox](https://tox.readthedocs.io/en/latest/) for handling the tests and one of the environment does just run code quality checks that include flake8, black, bandit and isort. I also have a pre-commit configuration file so that I have the best of both worlds.

**Comment by hjoliver** [comment]
> It's a tool that must be explicitly installed by the developer in order to be active. You can couple it with code quality tests so you can ensure that if someone does not use pre-commit, they will still have the tests to scream about the standards you want to use.

I was wondering about that but hadn't got around to trying it - thanks for clarifying, it sounds ideal.

**Comment by hjoliver** [comment]
@sgaist - thanks for you work here, and apologies for the 1-year delay!  

I've rebased your branch and made a new PR out of it, to finish it off without bothering you, so I'll close this as superseded. (But your commits will still go in, on the new PR).

**Pull request closed without merging**
