### PR TITLE
tui: bug fixes

### PR DESCRIPTION
**Pull request by oliver-sanders**
tui: add offline commands

* Add support for the play and clean commands.

zmq client: raise WorkflowStoped not ClientTimeout

* WorkflowClient could raise ClientTimeout for stopped workflows.
* Closes https://github.com/cylc/cylc-flow/issues/4654

tui: disable mutations for stopped workflows

* Closes https://github.com/cylc/cylc-flow/issues/4647

tui: fix context menu for cycle points

* Closes https://github.com/cylc/cylc-flow/issues/4629.
* Also adds the node ID to the context menu.

> **Note:** This PR includes a sneaky enhancement (offline) which shouldn't really be going into a
> RC release.
> It's small enough and Tui as an experimental interface is supplementary enough I think its ok, but happy to cherry-pick and delay to 8.0.1.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Tui has no test framework for live testing at the moment
- [ ] Appropriate change log entry included.
- [ ] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
Poking tests

**Review by MetRonnie — APPROVED** [review]
Tested out manually, fixes the reported bugs.

Only thing is there is a delay of a couple of seconds between hitting enter on one of the offline commands in the menu and the menu closing

**Comment by oliver-sanders** [comment]
That's the time it takes for the command to run (blocking).

**Review by wxtim — COMMENTED** [review]
✅  Can confirm that this definitely fixes #4654 , #4647 and #4629.

I'm concerned about the bug shown below, although it might want spinning into a new bug report:

https://user-images.githubusercontent.com/26465611/155713548-47d2bce2-0619-4522-911c-f21859b9df59.mp4

Essentially - `stop` returns control to you before the mutation finishes, and you can bring back the menu and ask for stop a second time after the workflow has stopped, and this causes a crash with traceback. Mentioned here rather than  a separate issue because traceback refers to Exception raised by code in this PR.

@oliver-sanders  your choice whether you want to fix or log this bug. I'm otherwise happy enough that this answers its original purpose that it can go in.

**Comment by oliver-sanders** [comment]
^ there

**Review by wxtim — APPROVED** [review]

**Review by MetRonnie — COMMENTED** [review]
Cannot reproduce the bug Tim identified with the latest commit.

(Oh, it's already been merged!)

**Pull request merged**
