### PR TITLE
jinja2: removed excessive context from Jinja2 raise/assert statements

### PR DESCRIPTION
**Pull request by oliver-sanders**
User request: Make the Jinja2 `raise` / `assert` exceptions cleaner.

The `raise` and `assert` helpers are used by some workflow developers to allow validation of inputs / environment, e.g:

```ini
#!jinja2

{{ assert(SITE is defined, 'Please define the SITE variable') }}
```

The workflow developer configures the condition and a user-friendly message to display.

Unfortunately, that message gets lost in the resulting message:

```console
$ cylc val .
Jinja2Error: Jinja2 Assertion Error: message
File /var/tmp/tmp.F4DJDykBo2/flow.cylc
  #!Jinja2
  
  {{ assert(SITE is defined, 'message') }}	<-- Exception
```

This scary looking error makes it look like something is genuinely wrong:
* The traceback looks like program code, it's not something the user is expected to understand.
* The `Jinja2Error` exception makes it look like an error.

This PR changes the exception from Jinja2Error to InputError and remove the extraneous context:

```console
$ cylc val .
InputError: message
(add --verbose for more context)
```

The full exception is still available to workflows developers in verbose mode (can be helpful in tracking down the location of the `assert` / `raise` statement that caused the error).

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] Changelog entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by hjoliver — COMMENTED** [review]
Looks good, couple of related but simple test failures.

**Comment by hjoliver** [comment]
`tests/f/jinja2/10-builtin-functions.t ` failing

**Comment by oliver-sanders** [comment]
(Dammit, thought I'd removed that)

**Review by hjoliver — APPROVED** [review]

**Comment by wxtim** [comment]
This breaks Cylc Rose tests. Spin it off as an issue and assign to me, or fix it and put up your own PR.

**Review by wxtim — APPROVED** [review]
This is a really, really good idea IMO.

**Comment by oliver-sanders** [comment]
> This breaks Cylc Rose tests. I'll fix it and put a PR up after lunch

Of course, I completely forgot those tests were using `assert`!

**Comment by oliver-sanders** [comment]
Merging with two approvals.

**Pull request merged**
