### PR TITLE
conda: remove unused deps

### PR DESCRIPTION
**Pull request by oliver-sanders**
Matches https://github.com/conda-forge/cylc-flow-feedstock/pull/19/files

* These deps aren't used anywhere so can be safely removed.
* Deps are used for the remote docker images which provides us with a basic test on GHA.
* I have built the env and run basic tests to confirm everything works locally.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.py` and
  `conda-environment.yml`.
- [x] Already covered by existing tests.
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Almost all CI tests passed. Just waiting for final ones before hitting merge :+1: thanks!!!

**Comment by kinow** [comment]
Strange, not much progress from the last time I had a look. @oliver-sanders feel free to merge it if the build passes and I haven't merged it (probably gone to bed :sleeping_bed: :smile: )

**Comment by oliver-sanders** [comment]
AH actions has been queueing jobs for a long time over the past few days, dunno what's up, I had to cancel and re-trigger a bunch of jobs yesterday to get them to go through.

Nothing flagged on https://www.githubstatus.com/

**Comment by oliver-sanders** [comment]
cancelled + retriggered the functional tests ...

**Comment by oliver-sanders** [comment]
Tests passed, approved here and on cylc-flow-feedstock

**Pull request merged**
