### PR TITLE
added metadata section to platforms and platform groups config

### LINKED ISSUE #4528: Add Metadata to Platforms
Add a metadata section to platforms so that users can do `cylc config -i [platforms]` to get information on platforms and usage.

For example I anticipate local usage to include details of maximum memory and "CPU"'s allowed on a platform.

[Copied from conversation on Element](https://matrix.to/#/!hwZqSYihGPuhDdIzIP:matrix.org/$1637628839316531Hdgzu:matrix.org?via=matrix.org]

[I've put this under 8.x because it's not a breaking change to the config]

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by wxtim**
These changes close #4528 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` and `conda-environment.yml`.
- [x] Does not need tests (Config change).
- [x] Appropriate change log entry included.
- [x] No documentation update required, yet. See #4557

### CODE REVIEW

**Review by hjoliver — COMMENTED** [review]
Looks good. Just wondering about a few things though:
- worth putting the common descriptive text in a string constant?
- would a short-cut option would be useful (e.g. `--describe-platforms`) that just prints platform names and metadata?
- there's no internal use for this, so I wonder if a single `meta` (or `description`?) items would suffice, rather than a section for multiple arbitrary items?  (I suppose it's possible that individual items that can be extracted separately could be useful at a site ... e.g. `cost per cpu hour` or something?).

**Comment by wxtim** [comment]
>     * worth putting the common descriptive text in a string constant?

Yes

>     * would a short-cut option would be useful (e.g. `--describe-platforms`) that just prints platform names and metadata?

I think so; see https://github.com/cylc/cylc-flow/issues/4557 - I'm think that I'm going to take your comment as a yes to the question in that ticket.

>     * there's no internal use for this, so I wonder if a single `meta` (or `description`?) item would suffice, rather than a section for multiple arbitrary items?  (I suppose it's possible that individual items that can be extracted separately could be useful at a site ... e.g. `cost per cpu hour` or something?).

It would, but I think it's reasonable to leave it open ended - examples might include
```ini
[meta]
description = """
Our Cluster.
"""
url=http://somedocs.internalwebsite.com
max-memory-request=200G
max-cpu-request=12
```

Though to be honest, I'm not completely convinced that this is required.

**Comment by wxtim** [comment]
@hjoliver : I think I've now 
- added the description field.
- justified my decision to leave other fields open ended: Just because Cylc has no internal use for formally defined fields doesn't mean that someone else can't use them. For example, my personal workflows repo has [a script](https://github.com/wxtim/workflows/blob/master/.github/workflows/readmemaker) which GH actions uses to extract metadata and dump it in the repo `README.md`.
- Created a new ticket to discuss the platform listing.

**Comment by hjoliver** [comment]
> added the description field.

I think you might have misinterpreted my comment on this, which was:
> worth putting the common descriptive text in a string constant?

I meant, this descriptive text is identical for platform and group:
```
                Allows writers of platform configurations to add information
                about platform usage. There are no-preset items because
                Cylc does not use any platform metadata internally.

                Users can then see information about defined platforms using::

                   cylc config -i [platforms]

                .. seealso::
                   :ref:`AdminGuide.PlatformConfigs`
```

... so, it should really be stored in a string constant to avoid the duplication.

Also, *There are no-preset items* is now not true since you've added a preset `description` item (which I don't think we need, if going with the arbitrary metadata solution).

**Comment by wxtim** [comment]
@hjoliver  - completely got the wrong end of the stick here - have pushed another commit which hopefully hits nearer the mark.

**Review by hjoliver — APPROVED** [review]
That's got it, thanks @wxtim

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
