### PR TITLE
data-store graph walk restricted

### LINKED ISSUE #5435: efficiency: increment_graph_window
Re-issue of: https://github.com/cylc/cylc-flow/issues/5315

The scaling of `increment_graph_window` has improved, but is still severe enough to prevent some Cylc 7 workflows from being able to run with Cylc8.

See Element for discussion:

https://matrix.to/#/!gMuCeOJBhYqgWDGwnR:matrix.org/$1679999387176196Xelev:matrix.org?via=matrix.org

### Description

For the workflow `a => b<x>` there are `x + 1` tasks and `x` dependencies.

However, for `x=700` the `increment_graph_window` function is called in excess of 3'000'000 times.

### Reproducible Example

```ini
[task parameters]
   m = 0..7000
[scheduling]
   [[queues]]
      [[[default]]]
         limit = 4
   [[graph]]
      R1 = "a => b<m>"
[runtime]
   [[a, b<m>]]
```

```console
$ cylc play <id> --profile --no-detach
```

Run this for a few mins, when you get bored ctrl+c it, then:

```console
$ pip install snakeviz
$ snakeviz ~/cylc-run/<id>/log/scheduler/profile.prof
```

### Expected Behaviour

It should take seconds, not minutes to spawn the 700 tasks in this workflow.

### PR DESCRIPTION
**Pull request by dwsutherland**
closes #5435

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Covered by existing tests.
- [ ] `CHANGES.md` entry included if this is a change that can affect users
- [ ] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Have repeated the reported result, this reduces the number of calls of `increment_graph_window` from `49021002/7001` to `14002/7001` for the example in #5435 :tada:. Doubtless the single biggest complexity reduction for cylc-flow in a single change ever! There are 7001 tasks in the workflow causing the 7001 original calls, each makes two recursive calls giving the 14002 which makes sense.

The revised algorithm seems to be producing the same results, these screenshots come from the same workflow, installed & run under `upstream/8.1.x` and `dwsutherland/graph-walk-efficiency` with the same operations performed on both. The graph view displays the same results:

Screenshot from 2023-04-20 11-49-25
Screenshot from 2023-04-20 11-49-38

**Comment by dwsutherland** [comment]
The only down side is; increasing the window size will no longer flesh out the entire workflow graph, it will only show the the direct ancestors/descendants of active nodes.

But obviously, no down sides with `n=1` .. And all the tests passed, so nothing missing there.

If we're happy with this trade-off, perhaps we should get this one in and work on the no-rewalk change separately.

**Comment by oliver-sanders** [comment]
Ah, right, this has removed the ability to generate the n>=1 window?

**Comment by oliver-sanders** [comment]
From a bit of experimentation with this pattern:

```
a => b<N> => c
```

The number of times `increment_graph_window` is called (recursive) scales according to:

| Before | After
| --- | --- |
| **2N^2** + 3N + 1 | 5N + 1 |

This change removes the N^2 term which is the nasty one.

The factor of 5 in the new solution is a little odd, not sure where that's coming from. Would be great to reduce it if possible, but linear scaling is the important bit for now.

The lack of cousins in the graph window isn't great, however, this doesn't affect the N=1 window (default) and we don't currently make it easy for users to switch the n-window in the GUI so this shouldn't have any impact right now.

**Review by oliver-sanders — APPROVED** [review]
I think the performance is well worth the caveats, we can always improve later, thanks @dwsutherland!

**Comment by oliver-sanders** [comment]
(can drop in a changelog later)

**Comment by hjoliver** [comment]
> we don't currently make it easy for users to switch the n-window in the GUI so this shouldn't have any impact right now.

Ha, note https://github.com/cylc/cylc-ui/issues/1281

**Comment by hjoliver** [comment]
>  I think the performance is well worth the caveats, we can always improve later, thanks @dwsutherland!

Agreed, fantastic.

> The only down side is; increasing the window size will no longer flesh out the entire workflow graph, it will only show the the direct ancestors/descendants of active nodes.

This may be OK for the n-window.  For n=cycle (or cycle-window?) we shouldn't need to walk out from active tasks.

**Comment by hjoliver** [comment]
On my laptop, it took 15s to spawn 7000 tasks on this branch vs 400s on master :tada:

**Review by hjoliver — APPROVED** [review]
Great, merging this now to get it in 8.1.3

@dwsutherland - as a small follow-up could you just add some code comments to explain the current functionality and the "cousins problem"?

**Comment by hjoliver** [comment]
(I'll push a hot-fix change log entry for this)

**Pull request merged**
