### PR TITLE
Modernise 'cylc dump -t' print format.

### PR DESCRIPTION
**Pull request by hjoliver**
This has been annoying me forever.

Master 🤮: 
```
$ cylc dump -t bug --flows
foo, 100, running, not-held, not-queued, not-runahead, [1]
foo, 101, waiting, not-held, not-queued, runahead, [1]
foo, 96, running, not-held, not-queued, not-runahead, [1]
foo, 97, running, not-held, not-queued, not-runahead, [1]
foo, 98, running, not-held, not-queued, not-runahead, [1]
foo, 99, running, not-held, not-queued, not-runahead, [1]
```

This branch:
```
$ cylc dump -t bug --flows
91/foo:running flows=[1]
92/foo:running flows=[1]
93/foo:running flows=[1]
94/foo:running flows=[1]
95/foo:running flows=[1]
96/foo:waiting (runahead) flows=[1]
```

**QUESTION**: is it OK to make the new format the default? 
(As I have done, with `-l/--legacy` to generate the old format)

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] Changelog entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Review by oliver-sanders — APPROVED** [review]
LGTM

**Review by dwsutherland — APPROVED** [review]
Looks good.. We adding a legacy format to avoid changing all the tests? 
I guess someone might like it (or use it) 😆

**Comment by hjoliver** [comment]
> Looks good.. We adding a legacy format to avoid changing all the tests? I guess someone might like it (or use it) 😆

Not so much adding it, but keeping it just in case anyone is relying on it. (Not trying to avoid changing the tests, honest!)

**Comment by dwsutherland** [comment]
I don't know how the patch coverage has been calculated? I wouldn't have thought there would be many indirect losses from this change...

**Comment by hjoliver** [comment]
From a quick look on Codecov, I don't get it:

Screenshot (17)

The yellow ("partial") lines are covered by my integration test, and the red (not-covered) lines are not changed on this branch.

**Comment by oliver-sanders** [comment]
To turn those yellow lines green we need a test that makes the `if` fall in either direction, e.g. at least one task which is held and one task which is not held.

**Comment by hjoliver** [comment]
At first glance I thought it was odd because those `if` blocks don't have an `else` clause. But the do-nothing option does affect the following logic of course - so that explains it, thanks!  I'll extend the tests...

**Comment by hjoliver** [comment]
Patch coverage now 100% 🎉

**Pull request merged**
