### PR TITLE
Protobuf 4.24

### PR DESCRIPTION
**Pull request by dwsutherland**
Protobuf upgrade to 4.24.4:
https://github.com/protocolbuffers/protobuf/releases/tag/v24.4
https://github.com/protocolbuffers/protobuf/releases/tag/v24.0

Support for Python 3.7 is dropped at 4.25.0

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I think this should be raised on the master branch?

**Comment by oliver-sanders** [comment]
(FYI, we're checking compatibility with an old platform, will get back soon)

**Comment by oliver-sanders** [comment]
(new version installs fine because protobuf falls back to the Python backend)

**Review by oliver-sanders — APPROVED** [review]

**Review by MetRonnie — APPROVED** [review]
Tested interacting with a workflow started under this branch (after pip installing) using a pre-running UIS

**Pull request merged**
