### PR TITLE
Give Cylc Lint it's own chunk of changelog

### PR DESCRIPTION
**Pull request by wxtim**
**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I'm not sure why we would treat `cylc lint` differently to any other Cylc CLI tool?

**Comment by wxtim** [comment]
> I'm not sure why we would treat `cylc lint` differently to any other Cylc CLI tool?

Because it reflects a style guide rather than functional guide. Not to bothered. Close if you don't want it.

**Comment by oliver-sanders** [comment]
There are other tools which are "non-functional" too. I don't think we need a top-level section for `cylc lint`.

**Comment by MetRonnie** [comment]
I'm with Oliver on this, voting to close

**Pull request closed without merging**
